# zedBSD lightweight desktop taskbar
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,zshell,zshell,*,n,basic,userland/X11/zshell/main.c userland/X11/libX11/xlib.c,y,x11-applications,,))
