# SPARC V9 build composition.
include platform/sparcv9/vmunix.mk
include platform/sparcv9/bootloader.mk
include platform/sparcv9/rootfs.mk
include platform/sparcv9/disk-image.mk
include platform/sparcv9/run.mk
include platform/sparcv9/toolchain.mk
