# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent FreeBSD build of imageview; source membership mirrors the target package.
KEILAND_FREEBSD_IMAGEVIEW_SOURCES := userland/desktop/imageview/main.c \
	userland/desktop/imageview/present.c \
	userland/desktop/imageview/menu.c \
	userland/desktop/imageview/titlebar.c \
	userland/desktop/imageview/glass.c \
	userland/desktop/imageview/view.c \
	userland/desktop/imageview/draw.c \
	userland/desktop/imageview/image.c \
	userland/desktop/imageview/folder.c \
	userland/desktop/imageview/canvas.c \
	userland/desktop/imageview/text.c \
	userland/desktop/imageview/touch.c \
	userland/desktop/imageview/share.c \
	userland/desktop/files/trash.c \
	userland/desktop/files/apps.c \
	userland/desktop/files/mounts.c \
	userland/desktop/artwork/mark.c \
	userland/desktop/picture/picture.c
$(eval $(call KEILAND_FREEBSD_PROGRAM,imageview,bin,$(KEILAND_FREEBSD_IMAGEVIEW_SOURCES),libkeiland.so libtruetype.so libpng-compat.so libjpeg-compat.so libgif-compat.so libz-compat.so libwayland-client.so libvulkan.so.1,-lm))
