#!/bin/sh
# ws140: builds rtld-many (rtld-many.c) and its libraries on the host with the target's clang, against BUILD's libc.so:
#   libmany00.so .. libmany39.so     many-lib.c, many_value_NN() returns NN+1; rtld-many is linked with all 40
#   libleaf000.so .. libleaf119.so   many-lib.c, leaf_value_NNN() returns NNN+1
#   libhub0.so .. libhub2.so         many-hub.c, each linked with 40 leaves (000-039, 040-079, 080-119)
#   libtlsdesc.so                    300 TLS variables (generated), each reached through its own TLSDESC (U3)
#   libmany-long-name-...-ws140.so   many-lib.c, long_value() returns 77; its name is longer than 64 bytes (U3)
#   libphdr.so                       many-lib.c, phdr_value() returns 55, padded to more than 16 program headers (U3)
#   libtls00.so .. libtls39.so       many-tls.c, a TLS variable starting at NN+1; even ones through TLSDESC (p002)
#   dynload/libpathmod.so            many-lib.c, path_value() returns 66; in a directory no search reaches, dlopened
#                                    by its path (T1-495: Python's extension modules)
# and puts them all in OUT/../rtld-many.tar (ustar, for the guest's pax).  rtld-many.sh runs it in the guest.
#
#   plan/tools/rtld/build-many.sh BUILD OUT      (BUILD has dynamic/libc.so; OUT is made afresh: a link to a new
#                                               directory, plan/tools/fresh-out.sh)
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
set -eu
cd "$(dirname -- "$0")/../../.."
[ $# -eq 2 ] || { echo "usage: build-many.sh BUILD OUT" >&2; exit 2; }
build=$1
out=$2
tests=plan/tools/rtld
long_name=libmany-long-name-past-the-old-sixty-four-byte-limit-of-the-loader-ws140.so
tlsdesc_count=300
sysroot=$PWD/build/amd64/sysroot
cc="$PWD/build/llvm/bin/clang --target=x86_64-unknown-zedbsd --sysroot=$sysroot"
cflags="-nostdinc -I. -Iinclude -isystem $sysroot/usr/include -DHAL_ARCH_AMD64 -DKERN_USER_ABI_LP64 -DKERN_DYNAMIC_LIBC
 -m64 -march=x86-64 -mno-red-zone -O2 -ffreestanding -fPIC -fno-builtin -fno-stack-protector -Wall -Wextra -Werror"
ldshared="-m64 -nostdlib -shared -Wl,--hash-style=gnu,-z,now,-z,relro"
[ -f "$build/dynamic/libc.so" ] || { echo "build-many: no $build/dynamic/libc.so" >&2; exit 1; }
. plan/tools/fresh-out.sh
fresh_out "$out"
mkdir -p "$out/obj" "$out/dynload"

# library NAME SYMBOL NUMBER [DEPENDENCY...]: one many-lib.c library.
library() {
	name=$1
	symbol=$2
	number=$3
	shift 3
	$cc $cflags -DMANY_SYMBOL="$symbol" -DMANY_NUMBER="$number" -c $tests/many-lib.c -o "$out/obj/$name.o"
	$cc $ldshared -Wl,-soname,"$name" "$out/obj/$name.o" "$@" -o "$out/$name"
}

# The 40 direct dependencies and the 120 leaves.
i=0
while [ $i -lt 40 ]; do
	library "$(printf 'libmany%02d.so' $i)" "$(printf 'many_value_%02d' $i)" $((i + 1))
	i=$((i + 1))
done
i=0
while [ $i -lt 120 ]; do
	library "$(printf 'libleaf%03d.so' $i)" "$(printf 'leaf_value_%03d' $i)" $((i + 1))
	i=$((i + 1))
done

# The hubs, each with 40 leaves as its DT_NEEDED entries (lld adds each -l without --as-needed).
$cc $cflags -c $tests/many-hub.c -o "$out/obj/many-hub.o"
hub=0
while [ $hub -lt 3 ]; do
	leaves=
	i=$((hub * 40))
	while [ $i -lt $((hub * 40 + 40)) ]; do
		leaves="$leaves -l:$(printf 'libleaf%03d.so' $i)"
		i=$((i + 1))
	done
	$cc $ldshared -Wl,-soname,libhub$hub.so "$out/obj/many-hub.o" -L"$out" $leaves -o "$out/libhub$hub.so"
	hub=$((hub + 1))
done

# The TLSDESC library: global (preemptible) variables, so each access is a TLSDESC of its own symbol.
source=$out/obj/tlsdesc-lib.c
{
	printf '/* Generated by plan/tools/rtld/build-many.sh: %s TLS variables, each through a TLSDESC. */\n\n' $tlsdesc_count
	i=0
	while [ $i -lt $tlsdesc_count ]; do
		printf '__thread int tlsdesc_var_%03d = %d;\n' $i $((i + 1))
		i=$((i + 1))
	done
	printf '\nlong tlsdesc_sum(void);\nvoid tlsdesc_add(void);\n\n'
	printf '/*\n * Adds up the variables.\n */\nlong\ntlsdesc_sum(\n\tvoid)\n{\n\tlong total;\n\n\t/* Each through its descriptor. */\n\ttotal = 0;\n'
	i=0
	while [ $i -lt $tlsdesc_count ]; do
		printf '\ttotal += tlsdesc_var_%03d;\n' $i
		i=$((i + 1))
	done
	printf '\n\t/* The sum. */\n\treturn total;\n}\n\n'
	printf '/*\n * Adds one to each variable.\n */\nvoid\ntlsdesc_add(\n\tvoid)\n{\n\t/* Each through its descriptor. */\n'
	i=0
	while [ $i -lt $tlsdesc_count ]; do
		printf '\ttlsdesc_var_%03d++;\n' $i
		i=$((i + 1))
	done
	printf '}\n'
} > "$source"
$cc $cflags -mtls-dialect=gnu2 -ftls-model=global-dynamic -c "$source" -o "$out/obj/tlsdesc-lib.o"
$cc $ldshared -Wl,-soname,libtlsdesc.so "$out/obj/tlsdesc-lib.o" -o "$out/libtlsdesc.so"
descriptors=$(build/llvm/bin/llvm-readelf -r "$out/libtlsdesc.so" | grep -c 'R_X86_64_TLSDESC' || true)
echo "build-many: libtlsdesc.so TLSDESC relocations=$descriptors"
[ "$descriptors" -ge $tlsdesc_count ] || { echo "build-many: too few TLSDESC relocations" >&2; exit 1; }

# The long name and the extra program headers.
library "$long_name" long_value 77
library libphdr.so phdr_value 55
python3 $tests/phdr-pad.py "$out/libphdr.so" 24
phnum=$(build/llvm/bin/llvm-readelf -h "$out/libphdr.so" | sed -n 's/.*Number of program headers: *//p')
echo "build-many: libphdr.so program headers=$phnum"
[ "$phnum" -gt 16 ] || { echo "build-many: too few program headers" >&2; exit 1; }

# The library dlopened by its path, outside the search path.
$cc $cflags -DMANY_SYMBOL=path_value -DMANY_NUMBER=66 -c $tests/many-lib.c -o "$out/obj/libpathmod.so.o"
$cc $ldshared -Wl,-soname,libpathmod.so "$out/obj/libpathmod.so.o" -o "$out/dynload/libpathmod.so"

# The TLS libraries: the even ones reach their variable through TLSDESC, the odd ones through __tls_get_addr.
i=0
while [ $i -lt 40 ]; do
	name=$(printf 'libtls%02d.so' $i)
	dialect=
	[ $((i % 2)) -eq 0 ] && dialect=-mtls-dialect=gnu2
	$cc $cflags $dialect -DMANY_SYMBOL="$(printf 'tls_address_%02d' $i)" -DMANY_NUMBER=$((i + 1)) \
	    -c $tests/many-tls.c -o "$out/obj/$name.o"
	$cc $ldshared -Wl,-soname,"$name" "$out/obj/$name.o" -o "$out/$name"
	i=$((i + 1))
done
tlsdesc_even=$(build/llvm/bin/llvm-readelf -r "$out/libtls00.so" | grep -c 'R_X86_64_TLSDESC' || true)
tlsget_odd=$(build/llvm/bin/llvm-readelf -r "$out/libtls01.so" | grep -c 'R_X86_64_DTPMOD64' || true)
echo "build-many: libtls00.so TLSDESC=$tlsdesc_even libtls01.so DTPMOD64=$tlsget_odd"
[ "$tlsdesc_even" -ge 1 ] && [ "$tlsget_odd" -ge 1 ] || { echo "build-many: the TLS libraries use the wrong access" >&2; exit 1; }

# The program, linked like dyntest (platform/amd64/vmunix.mk) with the 40 libraries before libc.so.
$cc $cflags -c $tests/rtld-many.c -o "$out/obj/rtld-many.o"
direct=
i=0
while [ $i -lt 40 ]; do
	direct="$direct -l:$(printf 'libmany%02d.so' $i)"
	i=$((i + 1))
done
$cc -m64 -nostdlib -pie -Wl,--no-relax -Wl,--hash-style=sysv,-z,now,-z,relro,-z,separate-code \
    -Wl,-z,stack-size=0x100000,--allow-shlib-undefined -Wl,--dynamic-linker=/lib/ld.so \
    "$sysroot/usr/lib/crt1.o" "$out/obj/rtld-many.o" -L"$out" $direct \
    -L"$build/dynamic" -Wl,-rpath-link,"$build/dynamic" -l:libc.so -o "$out/rtld-many"
needed=$(build/llvm/bin/llvm-readelf -d "$out/rtld-many" | grep -c NEEDED)
echo "build-many: rtld-many NEEDED=$needed"
[ "$needed" -eq 41 ] || { echo "build-many: rtld-many should have 41 DT_NEEDED entries" >&2; exit 1; }

# One archive for the guest.
(cd "$out" && tar --format=ustar -cf ../rtld-many.tar ./*.so ./dynload/libpathmod.so rtld-many)
echo "build-many: $(dirname -- "$out")/rtld-many.tar"
