/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * The RDNSS servers merged into resolv.conf (ws177-p045): the text of
 * the file as it is, the servers networkd put there before and those it
 * wants there now give the text to write, when anything changes.
 */

#include "userland/base/networkd/resolver6.h"

#include <stdio.h>
#include <string.h>

/* The first comment line networkd gives a file that has none. */
#define RESOLVER6_HEAD	"# Generated by networkd"

/* The lines of the file read: the first comment, the others, and the name servers' lines. */
struct resolver6_file {
	char head[RESOLVER6_LINE];
	char lines[RESOLVER6_LINES][RESOLVER6_LINE];
	unsigned line_count;
	char named[RESOLVER6_LINES][RESOLVER6_LINE];
	unsigned named_count;
	int has_search;
	int present[RESOLVER6_SERVERS];
	int dropped;
};

static void resolver6_read(const char *current, size_t length, const struct resolver6_servers *owned, const struct resolver6_servers *wanted, struct resolver6_file *file);
static void resolver6_line(const char *line, unsigned number, const struct resolver6_servers *owned, const struct resolver6_servers *wanted, struct resolver6_file *file);
static int resolver6_listed(const struct resolver6_servers *servers, const char *text);
static int resolver6_put(char *output, size_t capacity, size_t *used, const char *prefix, const char *text);

/*
 * Merges the servers networkd wants into the text of resolv.conf: the
 * servers it put there before and no longer wants are taken out, those it
 * wants and the file lacks are added after the file's own (three servers
 * at most, each once), and the search list is added when the file has
 * none.  The first comment line, the other lines and the other servers
 * stay.  now_owned is given the wanted servers the result lists that are
 * networkd's (added now, or before).  Returns 1 with the text to write in
 * output, 0 when the file needs no change, or -1 when the text does not
 * fit.
 */
int
resolver6_merge(
	const char *current,
	size_t length,
	const struct resolver6_servers *owned,
	const struct resolver6_servers *wanted,
	const char *search,
	char *output,
	size_t capacity,
	struct resolver6_servers *now_owned)
{
	struct resolver6_file file;
	const char *head;
	int appended[RESOLVER6_SERVERS];
	unsigned index;
	unsigned listed;
	size_t used;
	int search_added;
	int changed;
	int status;
	int ours;

	/* The file's lines, and which wanted servers it lists. */
	resolver6_read(current, length, owned, wanted, &file);

	/* The wanted servers it lacks, after its own, while there is room. */
	changed = file.dropped;
	listed = file.named_count;
	for (index = 0; index < wanted->count; index++) {
		appended[index] = 0;
		if (file.present[index] || listed >= RESOLVER6_SERVERS)
			continue;
		appended[index] = 1;
		listed++;
		changed = 1;
	}

	/* The search list, when the file has none. */
	search_added = 0;
	if (!file.has_search && search != NULL && search[0] != '\0') {
		search_added = 1;
		changed = 1;
	}

	/* The servers that are networkd's now: added, or listed and put there before. */
	now_owned->count = 0;
	for (index = 0; index < wanted->count; index++) {
		ours = appended[index];
		if (file.present[index]) {
			status = resolver6_listed(owned, wanted->text[index]);
			if (status)
				ours = 1;
		}

		/* Kept as networkd's. */
		if (ours)
			(void)snprintf(now_owned->text[now_owned->count++], RESOLVER6_SERVER_TEXT, "%s", wanted->text[index]);
	}

	/* Nothing changes. */
	if (!changed)
		return 0;

	/* The text: the first comment, the search list added, the other lines, the servers kept, the servers added. */
	used = 0;
	output[0] = '\0';
	head = RESOLVER6_HEAD;
	if (file.head[0] != '\0')
		head = file.head;
	status = resolver6_put(output, capacity, &used, "", head);
	if (status == 0 && search_added)
		status = resolver6_put(output, capacity, &used, "search ", search);
	for (index = 0; index < file.line_count && status == 0; index++)
		status = resolver6_put(output, capacity, &used, "", file.lines[index]);
	for (index = 0; index < file.named_count && status == 0; index++)
		status = resolver6_put(output, capacity, &used, "", file.named[index]);
	for (index = 0; index < wanted->count && status == 0; index++) {
		if (appended[index])
			status = resolver6_put(output, capacity, &used, "nameserver ", wanted->text[index]);
	}

	/* It did not fit. */
	if (status != 0)
		return -1;

	/* Succeeded: the text to write. */
	return 1;
}

/* Reads the file's text line by line into its parts. */
static void
resolver6_read(
	const char *current,
	size_t length,
	const struct resolver6_servers *owned,
	const struct resolver6_servers *wanted,
	struct resolver6_file *file)
{
	char line[RESOLVER6_LINE];
	const char *start;
	const char *end;
	size_t offset;
	size_t size;
	unsigned number;

	/* Nothing yet. */
	memset(file, 0, sizeof(*file));

	/* Each line, cut to the longest kept. */
	offset = 0;
	number = 0;
	while (offset < length) {
		start = current + offset;
		end = memchr(start, '\n', length - offset);
		size = length - offset;
		if (end != NULL)
			size = (size_t)(end - start);
		offset += size + 1U;
		if (size >= sizeof(line))
			size = sizeof(line) - 1U;
		memcpy(line, start, size);
		line[size] = '\0';
		resolver6_line(line, number, owned, wanted, file);
		number++;
	}
}

/* Sorts one line of the file: the first comment, a name server (kept or dropped), the search list, or another. */
static void
resolver6_line(
	const char *line,
	unsigned number,
	const struct resolver6_servers *owned,
	const struct resolver6_servers *wanted,
	struct resolver6_file *file)
{
	char value[RESOLVER6_LINE];
	size_t span;
	unsigned index;
	int theirs;
	int same;
	int want;

	/* The first line's comment. */
	if (number == 0U && line[0] == '#') {
		(void)snprintf(file->head, sizeof(file->head), "%s", line);
		return;
	}

	/* A name server: its value up to a blank. */
	same = strncmp(line, "nameserver", 10);
	if (same == 0 && (line[10] == ' ' || line[10] == '\t')) {
		span = strspn(line + 10, " \t");
		(void)snprintf(value, sizeof(value), "%s", line + 10 + span);
		span = strcspn(value, " \t\r");
		value[span] = '\0';

		/* One networkd put there and no longer wants goes. */
		theirs = resolver6_listed(owned, value);
		want = resolver6_listed(wanted, value);
		if (theirs && !want) {
			file->dropped = 1;
			return;
		}

		/* Otherwise it stays, and a wanted one is there already. */
		for (index = 0; index < wanted->count; index++) {
			same = strcmp(wanted->text[index], value);
			if (same == 0)
				file->present[index] = 1;
		}

		/* Kept as it is. */
		if (file->named_count < RESOLVER6_LINES)
			(void)snprintf(file->named[file->named_count++], RESOLVER6_LINE, "%s", line);
		return;
	}

	/* The search list, and any other line. */
	same = strncmp(line, "search", 6);
	if (same == 0 && (line[6] == ' ' || line[6] == '\t'))
		file->has_search = 1;
	if (file->line_count < RESOLVER6_LINES)
		(void)snprintf(file->lines[file->line_count++], RESOLVER6_LINE, "%s", line);
}

/* Tells whether a server's text is one of a list. */
static int
resolver6_listed(
	const struct resolver6_servers *servers,
	const char *text)
{
	unsigned index;
	int same;

	/* Each one. */
	for (index = 0; index < servers->count; index++) {
		same = strcmp(servers->text[index], text);
		if (same == 0)
			return 1;
	}

	/* Not listed. */
	return 0;
}

/* Puts a line (a prefix, a text and a newline) at the end of the output; 0, or -1 when it does not fit. */
static int
resolver6_put(
	char *output,
	size_t capacity,
	size_t *used,
	const char *prefix,
	const char *text)
{
	int count;

	/* The line after what is there. */
	count = snprintf(output + *used, capacity - *used, "%s%s\n", prefix, text);
	if (count < 0 || (size_t)count >= capacity - *used)
		return -1;

	/* Succeeded. */
	*used += (size_t)count;
	return 0;
}
