include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,sync,sync,*,y,basic,userland/base/sync/main.c,y,base,,))
