# zedBSD Unicode VT100 terminal
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,xzedterm,xzedterm,*,n,basic,userland/X11/xzedterm/main.c userland/X11/libX11/xlib.c,y,X11,,))
