include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,uudecode,uudecode,*,y,basic,userland/base/uudecode/main.c userland/base/common/uucodec.c,y,base,,))
