# WS021 production-shaped i386 PC-98 build.
ZEDBSD_MENU_VERSION := 3
ZEDBSD_PLATFORM := pc98
ZEDBSD_ARCHITECTURE := i386
ZEDBSD_BOARD := pc98
ZEDBSD_VARIANT := default

CONFIG_KERNEL_TEST_CHECKPOINTS := n
CONFIG_BUF_CACHE_KIB := 0
CONFIG_DRIVER_NE2000 := y
CONFIG_DRIVER_PCI_UHCI := n
CONFIG_DRIVER_PCI_EHCI := n
CONFIG_DRIVER_PCI_XHCI := n
CONFIG_DRIVER_PCI_NVME := n
CONFIG_DRIVER_USB_STORAGE := n
CONFIG_DRIVER_USB_CDC_NCM := n
CONFIG_DRIVER_GRAPHICS := y
CONFIG_DRIVER_LGY98 := n

include plan/ws021-llvm-toolchain/tests/config-common-userland.mk
