include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,tabs,tabs,*,y,basic,userland/base/tabs/main.c userland/base/common/terminfo.c,y,base,base/terminfo,))
