/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * Numeric declarations selected from virglrenderer 1.1.0 Venus protocol.
 * Copyright 2020 Google LLC; SPDX-License-Identifier: MIT.
 * See LICENSE-PROTOCOL for the retained upstream license.
 */

/*
 * Maintained protocol IDs, no renderer implementation is included.
 */

#ifndef VULKAN_OPCODES_H
#define VULKAN_OPCODES_H

/* Identifies commands in pinned Venus wire-format 1. */
enum vulkan_opcode {
	VULKAN_OPCODE_vkCreateInstance = 0,
	VULKAN_OPCODE_vkDestroyInstance = 1,
	VULKAN_OPCODE_vkEnumeratePhysicalDevices = 2,
	VULKAN_OPCODE_vkGetPhysicalDeviceFeatures = 3,
	VULKAN_OPCODE_vkGetPhysicalDeviceFormatProperties = 4,
	VULKAN_OPCODE_vkGetPhysicalDeviceImageFormatProperties = 5,
	VULKAN_OPCODE_vkGetPhysicalDeviceProperties = 6,
	VULKAN_OPCODE_vkGetPhysicalDeviceQueueFamilyProperties = 7,
	VULKAN_OPCODE_vkGetPhysicalDeviceMemoryProperties = 8,
	VULKAN_OPCODE_vkGetInstanceProcAddr = 9,
	VULKAN_OPCODE_vkGetDeviceProcAddr = 10,
	VULKAN_OPCODE_vkCreateDevice = 11,
	VULKAN_OPCODE_vkDestroyDevice = 12,
	VULKAN_OPCODE_vkEnumerateInstanceExtensionProperties = 13,
	VULKAN_OPCODE_vkEnumerateDeviceExtensionProperties = 14,
	VULKAN_OPCODE_vkEnumerateInstanceLayerProperties = 15,
	VULKAN_OPCODE_vkEnumerateDeviceLayerProperties = 16,
	VULKAN_OPCODE_vkGetDeviceQueue = 17,
	VULKAN_OPCODE_vkQueueSubmit = 18,
	VULKAN_OPCODE_vkQueueWaitIdle = 19,
	VULKAN_OPCODE_vkDeviceWaitIdle = 20,
	VULKAN_OPCODE_vkAllocateMemory = 21,
	VULKAN_OPCODE_vkFreeMemory = 22,
	VULKAN_OPCODE_vkMapMemory = 23,
	VULKAN_OPCODE_vkUnmapMemory = 24,
	VULKAN_OPCODE_vkFlushMappedMemoryRanges = 25,
	VULKAN_OPCODE_vkInvalidateMappedMemoryRanges = 26,
	VULKAN_OPCODE_vkGetDeviceMemoryCommitment = 27,
	VULKAN_OPCODE_vkBindBufferMemory = 28,
	VULKAN_OPCODE_vkBindImageMemory = 29,
	VULKAN_OPCODE_vkGetBufferMemoryRequirements = 30,
	VULKAN_OPCODE_vkGetImageMemoryRequirements = 31,
	VULKAN_OPCODE_vkGetImageSparseMemoryRequirements = 32,
	VULKAN_OPCODE_vkGetPhysicalDeviceSparseImageFormatProperties = 33,
	VULKAN_OPCODE_vkQueueBindSparse = 34,
	VULKAN_OPCODE_vkCreateFence = 35,
	VULKAN_OPCODE_vkDestroyFence = 36,
	VULKAN_OPCODE_vkResetFences = 37,
	VULKAN_OPCODE_vkGetFenceStatus = 38,
	VULKAN_OPCODE_vkWaitForFences = 39,
	VULKAN_OPCODE_vkCreateSemaphore = 40,
	VULKAN_OPCODE_vkDestroySemaphore = 41,
	VULKAN_OPCODE_vkCreateEvent = 42,
	VULKAN_OPCODE_vkDestroyEvent = 43,
	VULKAN_OPCODE_vkGetEventStatus = 44,
	VULKAN_OPCODE_vkSetEvent = 45,
	VULKAN_OPCODE_vkResetEvent = 46,
	VULKAN_OPCODE_vkCreateQueryPool = 47,
	VULKAN_OPCODE_vkDestroyQueryPool = 48,
	VULKAN_OPCODE_vkGetQueryPoolResults = 49,
	VULKAN_OPCODE_vkCreateBuffer = 50,
	VULKAN_OPCODE_vkDestroyBuffer = 51,
	VULKAN_OPCODE_vkCreateBufferView = 52,
	VULKAN_OPCODE_vkDestroyBufferView = 53,
	VULKAN_OPCODE_vkCreateImage = 54,
	VULKAN_OPCODE_vkDestroyImage = 55,
	VULKAN_OPCODE_vkGetImageSubresourceLayout = 56,
	VULKAN_OPCODE_vkCreateImageView = 57,
	VULKAN_OPCODE_vkDestroyImageView = 58,
	VULKAN_OPCODE_vkCreateShaderModule = 59,
	VULKAN_OPCODE_vkDestroyShaderModule = 60,
	VULKAN_OPCODE_vkCreatePipelineCache = 61,
	VULKAN_OPCODE_vkDestroyPipelineCache = 62,
	VULKAN_OPCODE_vkGetPipelineCacheData = 63,
	VULKAN_OPCODE_vkMergePipelineCaches = 64,
	VULKAN_OPCODE_vkCreateGraphicsPipelines = 65,
	VULKAN_OPCODE_vkCreateComputePipelines = 66,
	VULKAN_OPCODE_vkDestroyPipeline = 67,
	VULKAN_OPCODE_vkCreatePipelineLayout = 68,
	VULKAN_OPCODE_vkDestroyPipelineLayout = 69,
	VULKAN_OPCODE_vkCreateSampler = 70,
	VULKAN_OPCODE_vkDestroySampler = 71,
	VULKAN_OPCODE_vkCreateDescriptorSetLayout = 72,
	VULKAN_OPCODE_vkDestroyDescriptorSetLayout = 73,
	VULKAN_OPCODE_vkCreateDescriptorPool = 74,
	VULKAN_OPCODE_vkDestroyDescriptorPool = 75,
	VULKAN_OPCODE_vkResetDescriptorPool = 76,
	VULKAN_OPCODE_vkAllocateDescriptorSets = 77,
	VULKAN_OPCODE_vkFreeDescriptorSets = 78,
	VULKAN_OPCODE_vkUpdateDescriptorSets = 79,
	VULKAN_OPCODE_vkCreateFramebuffer = 80,
	VULKAN_OPCODE_vkDestroyFramebuffer = 81,
	VULKAN_OPCODE_vkCreateRenderPass = 82,
	VULKAN_OPCODE_vkDestroyRenderPass = 83,
	VULKAN_OPCODE_vkGetRenderAreaGranularity = 84,
	VULKAN_OPCODE_vkCreateCommandPool = 85,
	VULKAN_OPCODE_vkDestroyCommandPool = 86,
	VULKAN_OPCODE_vkResetCommandPool = 87,
	VULKAN_OPCODE_vkAllocateCommandBuffers = 88,
	VULKAN_OPCODE_vkFreeCommandBuffers = 89,
	VULKAN_OPCODE_vkBeginCommandBuffer = 90,
	VULKAN_OPCODE_vkEndCommandBuffer = 91,
	VULKAN_OPCODE_vkResetCommandBuffer = 92,
	VULKAN_OPCODE_vkCmdBindPipeline = 93,
	VULKAN_OPCODE_vkCmdSetViewport = 94,
	VULKAN_OPCODE_vkCmdSetScissor = 95,
	VULKAN_OPCODE_vkCmdSetLineWidth = 96,
	VULKAN_OPCODE_vkCmdSetDepthBias = 97,
	VULKAN_OPCODE_vkCmdSetBlendConstants = 98,
	VULKAN_OPCODE_vkCmdSetDepthBounds = 99,
	VULKAN_OPCODE_vkCmdSetStencilCompareMask = 100,
	VULKAN_OPCODE_vkCmdSetStencilWriteMask = 101,
	VULKAN_OPCODE_vkCmdSetStencilReference = 102,
	VULKAN_OPCODE_vkCmdBindDescriptorSets = 103,
	VULKAN_OPCODE_vkCmdBindIndexBuffer = 104,
	VULKAN_OPCODE_vkCmdBindVertexBuffers = 105,
	VULKAN_OPCODE_vkCmdDraw = 106,
	VULKAN_OPCODE_vkCmdDrawIndexed = 107,
	VULKAN_OPCODE_vkCmdDrawIndirect = 108,
	VULKAN_OPCODE_vkCmdDrawIndexedIndirect = 109,
	VULKAN_OPCODE_vkCmdDispatch = 110,
	VULKAN_OPCODE_vkCmdDispatchIndirect = 111,
	VULKAN_OPCODE_vkCmdCopyBuffer = 112,
	VULKAN_OPCODE_vkCmdCopyImage = 113,
	VULKAN_OPCODE_vkCmdBlitImage = 114,
	VULKAN_OPCODE_vkCmdCopyBufferToImage = 115,
	VULKAN_OPCODE_vkCmdCopyImageToBuffer = 116,
	VULKAN_OPCODE_vkCmdUpdateBuffer = 117,
	VULKAN_OPCODE_vkCmdFillBuffer = 118,
	VULKAN_OPCODE_vkCmdClearColorImage = 119,
	VULKAN_OPCODE_vkCmdClearDepthStencilImage = 120,
	VULKAN_OPCODE_vkCmdClearAttachments = 121,
	VULKAN_OPCODE_vkCmdResolveImage = 122,
	VULKAN_OPCODE_vkCmdSetEvent = 123,
	VULKAN_OPCODE_vkCmdResetEvent = 124,
	VULKAN_OPCODE_vkCmdWaitEvents = 125,
	VULKAN_OPCODE_vkCmdPipelineBarrier = 126,
	VULKAN_OPCODE_vkCmdBeginQuery = 127,
	VULKAN_OPCODE_vkCmdEndQuery = 128,
	VULKAN_OPCODE_vkCmdResetQueryPool = 129,
	VULKAN_OPCODE_vkCmdWriteTimestamp = 130,
	VULKAN_OPCODE_vkCmdCopyQueryPoolResults = 131,
	VULKAN_OPCODE_vkCmdPushConstants = 132,
	VULKAN_OPCODE_vkCmdBeginRenderPass = 133,
	VULKAN_OPCODE_vkCmdNextSubpass = 134,
	VULKAN_OPCODE_vkCmdEndRenderPass = 135,
	VULKAN_OPCODE_vkCmdExecuteCommands = 136,
	VULKAN_OPCODE_vkEnumerateInstanceVersion = 137,
	VULKAN_OPCODE_vkGetDeviceQueue2 = 155,
	VULKAN_OPCODE_vkSetReplyCommandStreamMESA = 178,
	VULKAN_OPCODE_vkSeekReplyCommandStreamMESA = 179,
	VULKAN_OPCODE_vkExecuteCommandStreamsMESA = 180
};

#endif
