/* Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib */
#ifndef ZEDBSD_FEATURES_H
#define ZEDBSD_FEATURES_H

/* zedBSD currently targets the POSIX.1-2008 base API plus selected R2 work. */
#define _POSIX_VERSION 200809L
#define _POSIX2_VERSION 200809L
#define _POSIX_JOB_CONTROL 1
#define _POSIX_THREADS 200809L
#define _POSIX_THREAD_ATTR_STACKSIZE 200809L
#define _POSIX_THREAD_PROCESS_SHARED 200809L
#define _POSIX_REALTIME_SIGNALS 200809L
#define _POSIX_SHARED_MEMORY_OBJECTS 200809L
#define _POSIX_SEMAPHORES 200809L
#define _POSIX_MESSAGE_PASSING 200809L
#define _POSIX_THREAD_SAFE_FUNCTIONS (-1)
#define _POSIX_THREAD_PRIO_INHERIT (-1)
#define _POSIX_THREAD_PRIO_PROTECT (-1)
#define _POSIX_ASYNCHRONOUS_IO (-1)
#define _POSIX_PRIORITIZED_IO (-1)
#define _POSIX_TIMERS (-1)
#define _POSIX_TYPED_MEMORY_OBJECTS (-1)

#endif
