# zedBSD — a scriptable bootstrap environment.
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib
#
# Layout:
#   include/          public HAL and kernel interfaces
#   src/hal/          HAL and board support implementation
#   src/kern/         platform-neutral kernel services
#   userland/base/       base-system programs and libc glue
#   userland/comp/       compilers
#   userland/X11/        X11 servers and applications
#   userland/packages/   optional language runtimes, editors, and packages
#   libc/             freestanding libc subset
#   src/softfloat/    soft-float support built from vendor GCC/musl sources
#   platform/<arch>/  per-architecture targets (IPLs, stages, console)
#
# The target is selected exclusively by config.mk, generated by menuconfig.
# Each target delegates to a platform Makefile and places its artifacts below
# build/<platform>/.  Architecture-neutral host artifacts stay shared at the
# top of build/ (build/host-noct, build/releases).

AS := as
LD := ld
OBJCOPY := objcopy
CC := gcc
HOSTCC ?= cc
PYTHON ?= python3
.DEFAULT_GOAL := disk-image

-include config.mk

# menuconfig and help remain available before the first configuration is
# saved.  Every build target requires the target information from config.mk.
ZEDBSD_CONFIG_OPTIONAL_GOALS := menuconfig help
ifeq ($(strip $(ZEDBSD_PLATFORM)),)
ifneq ($(filter-out $(ZEDBSD_CONFIG_OPTIONAL_GOALS),$(MAKECMDGOALS)),)
$(error config.mk is missing or invalid; run 'make menuconfig')
endif
ifeq ($(strip $(MAKECMDGOALS)),)
$(error config.mk is missing or invalid; run 'make menuconfig')
endif
endif

ZEDBSD_PLATFORM_DIR := $(strip \
	$(if $(filter i386,$(ZEDBSD_PLATFORM)),pcat,\
	$(if $(filter rpi4,$(ZEDBSD_PLATFORM)),arm64,\
	$(if $(filter sun4u,$(ZEDBSD_PLATFORM)),sparcv9,\
	$(ZEDBSD_PLATFORM)))))
PLATFORM_MAKEFILE := platform/$(ZEDBSD_PLATFORM_DIR)/Makefile
ifeq ($(wildcard $(PLATFORM_MAKEFILE)),)
ifneq ($(strip $(ZEDBSD_PLATFORM)),)
$(error Unsupported ZEDBSD_PLATFORM '$(ZEDBSD_PLATFORM)' in config.mk)
endif
endif
BUILD := build/$(ZEDBSD_PLATFORM_DIR)

CONFIG_DRIVER_NE2000 ?= y
CONFIG_DRIVER_LGY98 ?= y
CONFIG_DRIVER_GRAPHICS ?= y
CONFIG_DRIVER_PCI_UHCI ?= y
CONFIG_DRIVER_PCI_EHCI ?= y
CONFIG_DRIVER_USB_STORAGE ?= y
CONFIG_KERNEL_TEST_CHECKPOINTS ?= n
CONFIG_BUF_CACHE_KIB ?= 0

# Optional packages install commands and directly executable payloads here.
ZEDBSD_PACKAGE_BINDIR := /usr/bin

# Userland packages register themselves from userland/**/Makefile.  Kernel
# makefiles provide ABI-specific link rules, while package ownership, source
# paths and menu metadata live with each program.
USERLAND_PACKAGES :=
define ZEDBSD_USERLAND_PACKAGE
USERLAND_PACKAGES += $(1)
USERLAND_$(1)_LABEL := $(2)
USERLAND_$(1)_PLATFORMS := $(3)
USERLAND_$(1)_DEFAULT := $(4)
USERLAND_$(1)_CLASS := $(5)
USERLAND_$(1)_SOURCES := $(6)
USERLAND_$(1)_SELECTABLE := $(7)
USERLAND_$(1)_MENU := $(8)
USERLAND_$(1)_PACKAGE := $(9)
USERLAND_$(1)_REQUIRE := $(10)
endef
# userland/noct is an upstream source submodule, not a zedBSD package tree.
USERLAND_PACKAGE_MAKEFILES := $(filter-out userland/noct/%, $(sort \
	$(wildcard userland/*/Makefile) \
	$(wildcard userland/*/*/Makefile) \
	$(wildcard userland/*/*/*/Makefile)))
include $(USERLAND_PACKAGE_MAKEFILES)
ZEDBSD_ALL_USER_PROGRAMS := $(foreach program,$(USERLAND_PACKAGES),\
	$(if $(filter y,$(USERLAND_$(program)_SELECTABLE)),$(program)))
USERLAND_BASIC_PROGRAMS := $(foreach program,$(USERLAND_PACKAGES),\
	$(if $(filter basic,$(USERLAND_$(program)_CLASS)),$(program)))
USERLAND_NETWORK_PROGRAMS := $(foreach program,$(USERLAND_PACKAGES),\
	$(if $(filter network,$(USERLAND_$(program)_CLASS)),$(program)))
ZEDBSD_USER_PROGRAMS ?= $(ZEDBSD_ALL_USER_PROGRAMS)

# Package dependencies are named by their stable path below
# userland/packages (for example, editors/remacs -> lang/noct).  Resolve the
# paths back to registered program names even when config.mk was hand-edited.
user_program_dependency_names = $(strip $(foreach program,$(1),\
	$(foreach requirement,$(USERLAND_$(program)_REQUIRE),\
		$(foreach candidate,$(USERLAND_PACKAGES),\
			$(if $(filter $(requirement),$(USERLAND_$(candidate)_PACKAGE)),\
				$(candidate))))))
ZEDBSD_USER_PROGRAMS_DEPS_1 := $(sort $(ZEDBSD_USER_PROGRAMS) \
	$(call user_program_dependency_names,$(ZEDBSD_USER_PROGRAMS)))
ZEDBSD_USER_PROGRAMS_DEPS_2 := $(sort $(ZEDBSD_USER_PROGRAMS_DEPS_1) \
	$(call user_program_dependency_names,$(ZEDBSD_USER_PROGRAMS_DEPS_1)))
ZEDBSD_USER_PROGRAMS_DEPS_3 := $(sort $(ZEDBSD_USER_PROGRAMS_DEPS_2) \
	$(call user_program_dependency_names,$(ZEDBSD_USER_PROGRAMS_DEPS_2)))
override ZEDBSD_USER_PROGRAMS := $(ZEDBSD_USER_PROGRAMS_DEPS_3)
# A saved configuration may be reused after changing targets.  Do not let
# packages selected for another ABI become impossible prerequisites of the
# current root filesystem (PC/AT i386 is named "pcat" by the build system).
ZEDBSD_USER_PLATFORM := $(ZEDBSD_PLATFORM)
override ZEDBSD_USER_PROGRAMS := $(foreach program,$(ZEDBSD_USER_PROGRAMS),\
	$(if $(filter * $(ZEDBSD_USER_PLATFORM),\
		$(USERLAND_$(program)_PLATFORMS)),$(program)))
# Essential administrative tools are present even when an older config.mk
# predates their package registration.
override ZEDBSD_USER_PROGRAMS := $(sort $(ZEDBSD_USER_PROGRAMS) blkid hostname)
# Xzed cannot operate without the kernel graphics character device.  Keep
# hand-edited and older saved configurations from producing an unusable
# userland/kernel combination.
ifneq ($(filter Xzed,$(ZEDBSD_USER_PROGRAMS)),)
override CONFIG_DRIVER_GRAPHICS := y
endif
ZEDBSD_MISSING_PACKAGE_REQUIREMENTS := $(sort \
	$(foreach program,$(ZEDBSD_USER_PROGRAMS),\
		$(foreach requirement,$(USERLAND_$(program)_REQUIRE),\
			$(if $(filter $(requirement),\
				$(foreach candidate,$(USERLAND_PACKAGES),\
					$(USERLAND_$(candidate)_PACKAGE))),,\
				$(requirement)))))
ifneq ($(strip $(ZEDBSD_MISSING_PACKAGE_REQUIREMENTS)),)
$(error Unknown userland package dependencies: \
	$(ZEDBSD_MISSING_PACKAGE_REQUIREMENTS))
endif
USERLAND_SELECTED_BASIC_PROGRAMS = $(filter $(ZEDBSD_USER_PROGRAMS),\
	$(USERLAND_BASIC_PROGRAMS))
USERLAND_SELECTED_NETWORK_PROGRAMS = $(filter $(ZEDBSD_USER_PROGRAMS),\
	$(USERLAND_NETWORK_PROGRAMS))

# $(1): object tree prefix, $(2): registered package name.
define ZEDBSD_USERLAND_OBJECTS
$(patsubst %.c,$(1)/%.o,$(filter %.c,$(USERLAND_$(2)_SOURCES))) \
$(patsubst %.S,$(1)/%.o,$(filter %.S,$(USERLAND_$(2)_SOURCES)))
endef

.PHONY: list-user-programs
list-user-programs:
	@$(foreach program,$(ZEDBSD_ALL_USER_PROGRAMS),printf '%s|%s|%s|%s|%s|%s|%s\n' \
		'$(program)' '$(USERLAND_$(program)_LABEL)' \
		'$(USERLAND_$(program)_PLATFORMS)' \
		'$(USERLAND_$(program)_DEFAULT)' \
		'$(USERLAND_$(program)_MENU)' \
		'$(USERLAND_$(program)_PACKAGE)' \
		'$(USERLAND_$(program)_REQUIRE)';)

.PHONY: menuconfig
menuconfig:
	@$(PYTHON) tools/menuconfig.py --output config.mk

.PHONY: help list-targets
help:
	@printf '%s\n' \
		'zedBSD build interface' \
		'' \
		'  make             Build a disk image' \
		'  make menuconfig  Configure the build in config.mk' \
		'  make disk-image  Build a disk image' \
		'  make world       Build vmunix and rootfs' \
		'  make rootfs      Build rootfs' \
		'  make vmunix      Build the kernel' \
		'  make run         Build a disk image and start QEMU' \
		'  make toolchain   Build the toolchain' \
		'  make help        Show this summary'

list-targets:
	@printf 'Primary targets:\n'; \
		for target in $(ZEDBSD_PRIMARY_TARGETS); do printf '  %s\n' "$$target"; done
	@printf 'Support targets:\n'; \
		for target in $(ZEDBSD_SUPPORT_TARGETS); do printf '  %s\n' "$$target"; done
	@printf 'Focused checks:\n'; \
		for target in $(ZEDBSD_CHECK_TARGETS); do printf '  %s\n' "$$target"; done

ZEDBSD_CONFIG_CPPFLAGS := \
	-DCONFIG_DRIVER_NE2000=$(if $(filter y,$(CONFIG_DRIVER_NE2000)),1,0) \
	-DCONFIG_DRIVER_LGY98=$(if $(filter y,$(CONFIG_DRIVER_LGY98)),1,0) \
	-DCONFIG_DRIVER_GRAPHICS=$(if $(filter y,$(CONFIG_DRIVER_GRAPHICS)),1,0) \
	-DCONFIG_DRIVER_PCI_UHCI=$(if $(filter y,$(CONFIG_DRIVER_PCI_UHCI)),1,0) \
	-DCONFIG_DRIVER_PCI_EHCI=$(if $(filter y,$(CONFIG_DRIVER_PCI_EHCI)),1,0) \
	-DCONFIG_DRIVER_USB_STORAGE=$(if $(filter y,$(CONFIG_DRIVER_USB_STORAGE)),1,0) \
	-DCONFIG_BUF_CACHE_KIB=$(CONFIG_BUF_CACHE_KIB)
ifeq ($(CONFIG_KERNEL_TEST_CHECKPOINTS),y)
ZEDBSD_CONFIG_CPPFLAGS += -DZEDBSD_TEST_CHECKPOINTS
endif

BUILD_TOOLS_DIR := tools/build
ZEDBSD_PRIMARY_TARGETS := menuconfig vmunix bootloader rootfs-bin rootfs-usr \
	rootfs world disk-image run toolchain
ZEDBSD_SUPPORT_TARGETS := help list-targets check clean distclean
ZEDBSD_CHECK_TARGETS := check libc-host-test softfloat-host-test \
	check-disk-image \
	libc-opcode-check softfloat-opcode-check uapi-abi-layout-check \
	posix-header-check posix-api-matrix-check susv4-header-check \
	susv4-libc-host-test crypt-host-test userland-command-host-test \
	ufs1-format-host-test ufs2-format-host-test ufs1-format-python-test \
	ufs2-format-python-test overlay-journal-format-host-test

# Scripts invoked from make receive the configured architecture and build tree.
export ZEDBSD_ARCH := $(ZEDBSD_ARCHITECTURE)
export ZEDBSD_BUILD_DIR := $(CURDIR)/$(BUILD)

ASFLAGS := --32
ZEDBSD_CPPFLAGS := -nostdinc -Iinclude -Iinclude/uapi -Isrc -I. -I$(BUILD) -Ilibc/include \
	$(ZEDBSD_CONFIG_CPPFLAGS)
ifeq ($(ZEDBSD_ARCHITECTURE),i386)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_I386
else ifeq ($(ZEDBSD_ARCHITECTURE),amd64)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_AMD64
else ifeq ($(ZEDBSD_ARCHITECTURE),arm64)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_ARM64
else ifeq ($(ZEDBSD_ARCHITECTURE),sparcv9)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_SPARCV9
else ifeq ($(ZEDBSD_ARCHITECTURE),m68k)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_M68K
endif
ZEDBSD_CFLAGS := -m32 -march=i386 -Os -ffreestanding -fno-pic -fno-pie \
	-fno-stack-protector -fno-asynchronous-unwind-tables \
	-fno-unwind-tables -Wall -Wextra -Werror

include libc/libc.mk
include src/softfloat/softfloat.mk
include noct.mk

KERN_NET_SOURCES := \
	src/kern/net/packet-buf.c \
	src/kern/net/net-device.c \
	src/kern/net/core.c \
	src/kern/net/socket.c \
	src/kern/net/socket-file.c \
	src/kern/net/unix-socket.c \
	src/kern/net/packet-socket.c \
	src/kern/net/checksum.c \
	src/kern/net/ethernet.c \
	src/kern/net/route.c \
	src/kern/net/inet-socket.c \
	src/kern/net/arp.c \
	src/kern/net/ipv4.c \
	src/kern/net/icmp.c \
	src/kern/net/udp.c \
	src/kern/net/tcp.c
KERN_NET_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_NET_SOURCES))

KERN_UFS1_SOURCES := \
	src/kern/block-identity.c \
	src/kern/ufs1/ufs1-endian.c \
	src/kern/ufs1/ufs1-super.c \
	src/kern/ufs1/ufs1-vfs.c
KERN_UFS1_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_UFS1_SOURCES))
KERN_UFS2_SOURCES := \
	src/kern/ufs2/ufs2-super.c \
	src/kern/ufs2/ufs2-vfs.c
KERN_UFS2_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_UFS2_SOURCES))
KERN_UFS_CONSISTENCY_SOURCES := \
	src/kern/ufs/ufs-journal.c \
	src/kern/ufs/ufs-softdep.c \
	src/kern/ufs/ufs-snapshot.c
KERN_UFS_CONSISTENCY_OBJS := $(patsubst %.c,$(BUILD)/%.o,\
	$(KERN_UFS_CONSISTENCY_SOURCES))
KERN_ACL_SOURCES := src/kern/posix-acl.c
KERN_ACL_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_ACL_SOURCES))
KERN_QUOTA_SOURCES := src/kern/quota.c
KERN_QUOTA_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_QUOTA_SOURCES))

# ----------------------------------------------------------------------
# Generic compile rules.  Per-object flag overrides use target-specific
# variables; header dependencies come from -MMD.

OBJ_CPPFLAGS = $(ZEDBSD_CPPFLAGS)
OBJ_CFLAGS = $(ZEDBSD_CFLAGS)
OBJ_CC = $(CC)

$(BUILD)/%.o: %.S
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(OBJ_CC) $(OBJ_CPPFLAGS) $(OBJ_CFLAGS) -MMD -MP -c $< -o $@

$(ZEDBSD_LIBC_OBJECTS): OBJ_CC = $(ZEDBSD_LIBC_CC)
$(ZEDBSD_LIBC_OBJECTS): OBJ_CPPFLAGS = $(ZEDBSD_LIBC_CPPFLAGS)
$(ZEDBSD_LIBC_OBJECTS): OBJ_CFLAGS = $(ZEDBSD_LIBC_CFLAGS)

# ----------------------------------------------------------------------
# Architecture-neutral host tests.  Platform makefiles append their own
# binaries to HOST_TEST_BINARIES and phony run targets to CHECK_RUN_TARGETS.

HOST_TEST_CC := $(HOSTCC) -std=c11 -O2 -Wall -Wextra -Werror -I. -Iinclude/uapi

# Compile the public headers in both supported data models.  These are object
# fixtures rather than host executables so the ILP32 check does not depend on
# the host having 32-bit startup objects or libraries installed.
UAPI_ABI_TEST_FLAGS := -std=c11 -Wall -Wextra -Werror -nostdinc \
	-Ilibc/include -Iinclude/uapi -Iinclude

$(BUILD)/tests/uapi-abi-ilp32.o: tests/uapi-abi-layout.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -m32 $(UAPI_ABI_TEST_FLAGS) -c $< -o $@

$(BUILD)/tests/uapi-abi-lp64.o: tests/uapi-abi-layout.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -m64 $(UAPI_ABI_TEST_FLAGS) -DZEDBSD_USER_ABI_LP64 \
		-c $< -o $@

uapi-abi-layout-check: $(BUILD)/tests/uapi-abi-ilp32.o \
	$(BUILD)/tests/uapi-abi-lp64.o
	@echo "zedBSD ILP32/LP64 UAPI layout check: PASS"

$(BUILD)/tests/posix-header-ilp32.o: tests/posix-header-compile.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -m32 $(UAPI_ABI_TEST_FLAGS) -c $< -o $@

$(BUILD)/tests/posix-header-lp64.o: tests/posix-header-compile.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -m64 $(UAPI_ABI_TEST_FLAGS) -DZEDBSD_USER_ABI_LP64 \
		-c $< -o $@

posix-header-check: $(BUILD)/tests/posix-header-ilp32.o \
	$(BUILD)/tests/posix-header-lp64.o
	@echo "zedBSD POSIX ILP32/LP64 public-header check: PASS"

$(BUILD)/tests/susv4-header-ilp32.o: tests/susv4-header-compile.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -m32 $(UAPI_ABI_TEST_FLAGS) -c $< -o $@

$(BUILD)/tests/susv4-header-lp64.o: tests/susv4-header-compile.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -m64 $(UAPI_ABI_TEST_FLAGS) -DZEDBSD_USER_ABI_LP64 \
		-c $< -o $@

susv4-header-check: $(BUILD)/tests/susv4-header-ilp32.o \
	$(BUILD)/tests/susv4-header-lp64.o
	@echo "zedBSD SUSv4/XSI ILP32/LP64 public-header check: PASS"

susv4-uapi-review-check: plan/susv4-uapi-audit.csv \
	tools/susv4-uapi-review.py
	$(PYTHON) tools/susv4-uapi-review.py plan/susv4-uapi-audit.csv

posix-api-matrix-check: tests/posix-r2-api.csv \
	tools/check-posix-api-matrix.py
	$(PYTHON) tools/check-posix-api-matrix.py

$(BUILD)/tests/fat-host-test: tests/fat-host-test.c \
	src/kern/fs.c src/kern/fat.c src/kern/fat-lfn.c src/kern/fat16.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/fs.c src/kern/fat.c \
		src/kern/fat-lfn.c src/kern/fat16.c $< -o $@

$(BUILD)/tests/fat-write-host-test: tests/fat-write-host-test.c \
	src/kern/fs.c src/kern/fat.c src/kern/fat-lfn.c src/kern/fat16.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/fs.c src/kern/fat.c \
		src/kern/fat-lfn.c src/kern/fat16.c $< -o $@

$(BUILD)/tests/fat32-host-test: tests/fat32-host-test.c \
	src/kern/fs.c src/kern/fat.c src/kern/fat-lfn.c src/kern/fat16.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/fs.c src/kern/fat.c \
		src/kern/fat-lfn.c src/kern/fat16.c $< -o $@

$(BUILD)/tests/env-host-test: tests/env-host-test.c src/kern/env.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -Wall -Wextra -Werror -I. -Iinclude -Isrc src/kern/env.c $< -o $@

$(BUILD)/tests/user-noct-memory-host-test: \
	tests/user-noct-memory-host-test.c userland/packages/lang/noct/runtime/memory.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc \
		userland/packages/lang/noct/runtime/memory.c $< -o $@

$(BUILD)/tests/heap-context-host-test: tests/heap-context-host-test.c \
	libc/heap.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) libc/heap.c $< -o $@

$(BUILD)/tests/elf-host-test: tests/elf-host-test.c src/kern/elf.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -DHAL_ARCH_I386 -Iinclude -Isrc src/kern/elf.c $< -o $@

$(BUILD)/tests/elf-m68k-host-test: tests/elf-m68k-host-test.c src/kern/elf.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -DHAL_ARCH_M68K -DZEDBSD_USER_ABI_M68K -Iinclude -Isrc \
		src/kern/elf.c $< -o $@

$(BUILD)/tests/m68k-mmu-host-test: tests/m68k-mmu-host-test.c \
	src/hal/m68k/mmu030.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc $< -o $@

$(BUILD)/tests/m68k-space-host-test: tests/m68k-space-host-test.c \
	src/hal/m68k/space.c src/hal/m68k/space.h src/hal/m68k/mmu030.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/hal/m68k/space.c $< -o $@

$(BUILD)/tests/x68k-memory-map-host-test: \
	tests/x68k-memory-map-host-test.c \
	src/hal/m68k/bsp-x68k/memory-map.c \
	src/hal/m68k/bsp-x68k/memory-map.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc \
		src/hal/m68k/bsp-x68k/memory-map.c $< -o $@

$(BUILD)/tests/x68k-handoff-host-test: tests/x68k-handoff-host-test.c \
	src/hal/m68k/bsp-x68k/handoff.c src/hal/m68k/bsp-x68k/bsp.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc \
		src/hal/m68k/bsp-x68k/handoff.c $< -o $@

$(BUILD)/tests/x68k-mmio-host-test: tests/x68k-mmio-host-test.c \
	src/hal/m68k/bsp-x68k/mmio.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc $< -o $@

$(BUILD)/tests/x68k-keyboard-host-test: \
	tests/x68k-keyboard-host-test.c \
	src/hal/m68k/bsp-x68k/keyboard-map.c \
	src/hal/m68k/bsp-x68k/keyboard-map.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc \
		src/hal/m68k/bsp-x68k/keyboard-map.c $< -o $@

$(BUILD)/tests/m68k-exception-host-test: \
	tests/m68k-exception-host-test.c src/hal/m68k/exception.c \
	src/hal/m68k/exception.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/hal/m68k/exception.c $< -o $@

$(BUILD)/tests/m68k-fpu-frame-host-test: \
	tests/m68k-fpu-frame-host-test.c src/hal/m68k/fpu.c src/hal/m68k/fpu.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/hal/m68k/fpu.c $< -o $@

$(BUILD)/tests/x68k-partition-host-test: \
	tests/x68k-partition-host-test.c src/kern/x68k/partition.c \
	include/kern/x68k-partition.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/x68k/partition.c $< -o $@

$(BUILD)/tests/x68k-scsi-host-test: tests/x68k-scsi-host-test.c \
	drivers/x68k-mb89352.c drivers/x68k-mb89352.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc drivers/x68k-mb89352.c $< -o $@

$(BUILD)/tests/x68k-scsi-disk-host-test: \
	tests/x68k-scsi-disk-host-test.c drivers/x68k-spc-disk.c \
	drivers/x68k-spc-disk.h drivers/x68k-mb89352.c \
	drivers/x68k-mb89352.h tests/disk-host-stubs.c src/kern/buf.c \
	src/kern/sysctl.c src/kern/klog.c src/kern/disk.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -pthread -Iinclude -Isrc -Ilibc/include \
		drivers/x68k-mb89352.c drivers/x68k-spc-disk.c \
		src/kern/buf.c src/kern/sysctl.c src/kern/klog.c src/kern/disk.c \
		tests/disk-host-stubs.c $< -o $@

$(BUILD)/tests/sched-host-test: tests/sched-host-test.c src/kern/sched.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Dtid_t=int -DZEDBSD_SCHED_TEST -Iinclude -Isrc \
		src/kern/sched.c $< -o $@

$(BUILD)/tests/concurrency-host-test: tests/concurrency-host-test.c \
	src/kern/lock.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -pthread -Dtid_t=int -Iinclude -Isrc \
	src/kern/lock.c $< -o $@

$(BUILD)/tests/smp-contract-host-test: tests/smp-contract-host-test.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Dtid_t=int -Iinclude -Isrc $< -o $@

$(BUILD)/tests/ufs1-format-host-test: tests/ufs1-format-host-test.c \
	src/kern/ufs1/ufs1-endian.c src/kern/ufs1/ufs1-super.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/ufs1/ufs1-endian.c \
		src/kern/ufs1/ufs1-super.c $< -o $@

ufs1-format-host-test: $(BUILD)/tests/ufs1-format-host-test
	@$(BUILD)/tests/ufs1-format-host-test

$(BUILD)/tests/ufs2-format-host-test: tests/ufs2-format-host-test.c \
	src/kern/ufs1/ufs1-endian.c src/kern/ufs2/ufs2-super.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/ufs1/ufs1-endian.c \
		src/kern/ufs2/ufs2-super.c $< -o $@

ufs2-format-host-test: $(BUILD)/tests/ufs2-format-host-test
	@$(BUILD)/tests/ufs2-format-host-test

$(BUILD)/tests/ufs-consistency-host-test: tests/ufs-consistency-host-test.c \
	$(KERN_UFS_CONSISTENCY_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc $(KERN_UFS_CONSISTENCY_SOURCES) $< -o $@

$(BUILD)/tests/ufs1-test.img: tools/build/make-ufs-test-image.py \
	tools/build/ufs1_format.py
	@mkdir -p $(dir $@)
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) tools/build/make-ufs-test-image.py \
		--format ufs1 --size-mib 4 $@

$(BUILD)/tests/ufs1-multicg-test.img: tools/build/make-ufs-test-image.py \
	tools/build/ufs1_format.py
	@mkdir -p $(dir $@)
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) tools/build/make-ufs-test-image.py \
		--format ufs1 --size-mib 16 --cylinder-groups 4 $@

$(BUILD)/tests/ufs2-multicg-test.img: tools/build/make-ufs-test-image.py \
	tools/build/ufs2_format.py tools/build/ufs1_format.py
	@mkdir -p $(dir $@)
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) tools/build/make-ufs-test-image.py \
		--format ufs2 --size-mib 16 --cylinder-groups 4 \
		--journal-mib 1 --snapshot-mib 2 $@

$(BUILD)/tests/ufs1-vfs-host-test: tests/ufs1-vfs-host-test.c \
	$(BUILD)/tests/ufs1-test.img $(VFS_CORE_SOURCES) $(KERN_UFS1_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc \
		-DUFS1_TEST_IMAGE='"$(BUILD)/tests/ufs1-test.img"' \
		$(VFS_CORE_SOURCES) $(KERN_UFS1_SOURCES) tests/vfs-host-stubs.c $< -o $@

$(BUILD)/tests/ufs1-multicg-vfs-host-test: tests/ufs1-vfs-host-test.c \
	$(BUILD)/tests/ufs1-multicg-test.img $(VFS_CORE_SOURCES) $(KERN_UFS1_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc \
		-DUFS1_TEST_IMAGE='"$(BUILD)/tests/ufs1-multicg-test.img"' \
		$(VFS_CORE_SOURCES) $(KERN_UFS1_SOURCES) tests/vfs-host-stubs.c $< -o $@

$(BUILD)/tests/ufs2-multicg-vfs-host-test: tests/ufs1-vfs-host-test.c \
	$(BUILD)/tests/ufs2-multicg-test.img $(VFS_CORE_SOURCES) \
	$(KERN_UFS1_SOURCES) $(KERN_UFS2_SOURCES) \
	$(KERN_UFS_CONSISTENCY_SOURCES) $(KERN_QUOTA_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc \
		-DUFS2_TEST_IMAGE='"$(BUILD)/tests/ufs2-multicg-test.img"' \
		$(VFS_CORE_SOURCES) src/kern/ufs1/ufs1-endian.c \
		src/kern/ufs2/ufs2-super.c src/kern/ufs2/ufs2-vfs.c \
		$(KERN_UFS_CONSISTENCY_SOURCES) $(KERN_QUOTA_SOURCES) \
		tests/vfs-host-stubs.c $< -o $@

$(BUILD)/tests/vmspace-host-test: tests/vmspace-host-test.c \
	src/kern/vmspace.c src/kern/vm-object.c tests/vm-sync-host-stubs.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/vmspace.c \
		src/kern/vm-object.c tests/vm-sync-host-stubs.c $< -pthread -o $@

$(BUILD)/tests/vm-commit-host-test: tests/vm-commit-host-test.c \
	src/kern/vm-commit.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/vm-commit.c $< -pthread -o $@

$(BUILD)/tests/swap-host-test: tests/swap-host-test.c src/kern/swap.c \
	tests/spin-host-stubs.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/swap.c \
		tests/spin-host-stubs.c $< -pthread -o $@

$(BUILD)/tests/vm-reclaim-host-test: tests/vm-reclaim-host-test.c \
	src/kern/vm-reclaim.c src/kern/swap.c tests/spin-host-stubs.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/kern/vm-reclaim.c \
		src/kern/swap.c tests/spin-host-stubs.c $< -pthread -o $@

$(BUILD)/tests/packet-buf-host-test: tests/packet-buf-host-test.c \
	src/kern/net/packet-buf.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Ilibc/include \
		src/kern/net/packet-buf.c $< -o $@

$(BUILD)/tests/net-device-host-test: tests/net-device-host-test.c \
	src/kern/net/packet-buf.c src/kern/net/net-device.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Ilibc/include \
		src/kern/net/packet-buf.c src/kern/net/net-device.c $< -o $@

$(BUILD)/tests/packet-socket-host-test: tests/packet-socket-host-test.c \
	tests/net-sync-host-stubs.c \
	src/kern/net/packet-buf.c src/kern/net/net-device.c \
	src/kern/net/socket.c src/kern/net/packet-socket.c \
	src/kern/net/ethernet.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Ilibc/include \
		tests/net-sync-host-stubs.c \
		src/kern/net/packet-buf.c src/kern/net/net-device.c \
		src/kern/net/socket.c src/kern/net/packet-socket.c \
		src/kern/net/ethernet.c $< -o $@

INET_HOST_SOURCES := src/kern/net/packet-buf.c src/kern/net/net-device.c \
	src/kern/net/socket.c src/kern/net/checksum.c src/kern/net/ethernet.c \
	src/kern/net/route.c src/kern/net/inet-socket.c src/kern/net/arp.c \
	src/kern/net/ipv4.c src/kern/net/icmp.c src/kern/net/udp.c \
	src/kern/net/tcp.c

$(BUILD)/tests/inet-stack-host-test: tests/inet-stack-host-test.c \
	tests/net-sync-host-stubs.c $(INET_HOST_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Ilibc/include \
		tests/net-sync-host-stubs.c $(INET_HOST_SOURCES) $< -o $@

$(BUILD)/tests/dhcp-host-test: tests/dhcp-host-test.c userland/base/net/dhcp.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Ilibc/include \
		userland/base/net/dhcp.c $< -o $@

$(BUILD)/tests/dns-host-test: tests/dns-host-test.c \
	userland/base/libc/resolver-dns.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Ilibc/include \
		userland/base/libc/resolver-dns.c $< -o $@

$(BUILD)/tests/crypt-host-test: tests/crypt-host-test.c userland/base/libc/crypt.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -O2 -Wall -Wextra -Werror userland/base/libc/crypt.c $< -o $@

crypt-host-test: $(BUILD)/tests/crypt-host-test
	$(BUILD)/tests/crypt-host-test

$(BUILD)/tests/susv4-libc-host-test: tests/susv4-libc-host-test.c \
	libc/random48.c libc/random.c libc/search.c libc/xsi-crypto.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -O2 -Wall -Wextra -Werror -Ilibc/include \
		libc/random48.c libc/random.c libc/search.c libc/xsi-crypto.c $< -o $@

susv4-libc-host-test: $(BUILD)/tests/susv4-libc-host-test
	$(BUILD)/tests/susv4-libc-host-test
	@echo "zedBSD SUSv4 libc known-answer tests: PASS"

$(BUILD)/tests/blkdev-host-test: tests/blkdev-host-test.c \
	tests/disk-host-stubs.c \
	src/kern/buf.c src/kern/disk.c src/kern/partition.c src/kern/pc98/partition.c \
	src/kern/mbr-partition.c src/kern/pc98/partition-auto.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc src/kern/buf.c src/kern/disk.c src/kern/partition.c \
		src/kern/pc98/partition.c src/kern/mbr-partition.c \
		src/kern/pc98/partition-auto.c tests/disk-host-stubs.c $< -o $@

$(BUILD)/tests/bufcache-host-test: tests/bufcache-host-test.c \
	tests/disk-host-stubs.c src/kern/buf.c src/kern/sysctl.c src/kern/klog.c \
	src/kern/disk.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -pthread -Iinclude -Iinclude/uapi -Isrc src/kern/buf.c \
		src/kern/sysctl.c src/kern/klog.c src/kern/disk.c \
		tests/disk-host-stubs.c $< -o $@

$(BUILD)/tests/checkpoint-host-test: tests/checkpoint-host-test.c \
	tests/disk-host-stubs.c src/kern/test-checkpoint.c src/kern/buf.c \
	src/kern/disk.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -pthread -DZEDBSD_TEST_CHECKPOINTS \
		-Iinclude -Iinclude/uapi -Isrc src/kern/test-checkpoint.c \
		src/kern/buf.c src/kern/disk.c tests/disk-host-stubs.c $< -o $@

$(BUILD)/tests/fault-injection-host-test: tests/fault-injection-host-test.c \
	src/kern/test-fault.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -pthread -DZEDBSD_TEST_FAULTS -Iinclude -Isrc \
		src/kern/test-fault.c $< -o $@

VFS_CORE_SOURCES := src/kern/buf.c src/kern/disk.c src/kern/inode.c src/kern/file.c \
	src/kern/namecache.c src/kern/namei.c src/kern/mount.c src/kern/rootfs.c

$(BUILD)/tests/vfs-host-test: tests/vfs-host-test.c $(VFS_CORE_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc $(VFS_CORE_SOURCES) \
		tests/vfs-host-stubs.c $< -o $@

$(BUILD)/tests/cred-host-test: tests/cred-host-test.c src/kern/cred.c \
	$(KERN_ACL_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Dtid_t=int -Iinclude -Iinclude/uapi -Isrc src/kern/cred.c \
		$(KERN_ACL_SOURCES) $< -o $@

$(BUILD)/tests/quota-host-test: tests/quota-host-test.c $(KERN_QUOTA_SOURCES)
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc $(KERN_QUOTA_SOURCES) $< -o $@

$(BUILD)/tests/ufs-snapshot-host-test: tests/ufs-snapshot-host-test.c \
	src/kern/ufs/ufs-snapshot.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Iinclude/uapi -Isrc \
		src/kern/ufs/ufs-snapshot.c $< -o $@

$(BUILD)/tests/clock-rtc-host-test: tests/clock-rtc-host-test.c \
	src/hal/x86/rtc.c
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iinclude -Isrc src/hal/x86/rtc.c $< -o $@

$(BUILD)/tests/sh-lexer-host-test: tests/sh-lexer-host-test.c \
	userland/base/sh/lexer.c userland/base/sh/lexer.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) userland/base/sh/lexer.c $< -o $@

$(BUILD)/tests/sh-expand-host-test: tests/sh-expand-host-test.c \
	userland/base/sh/expand.c userland/base/sh/expand.h userland/base/sh/lexer.c \
	userland/base/sh/lexer.h userland/base/sh/arithmetic.c userland/base/sh/arithmetic.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) userland/base/sh/lexer.c userland/base/sh/arithmetic.c \
		userland/base/sh/expand.c $< -o $@

$(BUILD)/tests/sh-arithmetic-host-test: tests/sh-arithmetic-host-test.c \
	userland/base/sh/arithmetic.c userland/base/sh/arithmetic.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) userland/base/sh/arithmetic.c $< -o $@

$(BUILD)/tests/sh-alias-host-test: tests/sh-alias-host-test.c \
	userland/base/sh/alias.c userland/base/sh/alias.h userland/base/sh/lexer.c \
	userland/base/sh/lexer.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) userland/base/sh/lexer.c userland/base/sh/alias.c $< -o $@

$(BUILD)/tests/sh-vars-host-test: tests/sh-vars-host-test.c \
	userland/base/sh/vars.c userland/base/sh/vars.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) userland/base/sh/vars.c $< -o $@

$(BUILD)/tests/sh-glob-host-test: tests/sh-glob-host-test.c \
	userland/base/sh/glob.c userland/base/sh/glob.h userland/base/sh/expand.c \
	userland/base/sh/expand.h userland/base/sh/lexer.c userland/base/sh/lexer.h \
	userland/base/sh/arithmetic.c userland/base/sh/arithmetic.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) userland/base/sh/lexer.c userland/base/sh/arithmetic.c \
		userland/base/sh/expand.c \
		userland/base/sh/glob.c $< -o $@

$(BUILD)/tests/libedit-host-test: tests/libedit-host-test.c \
	userland/base/libedit/readline.c userland/base/libedit/readline/readline.h \
	userland/base/libedit/readline/history.h
	@mkdir -p $(dir $@)
	$(HOST_TEST_CC) -Iuserland/base/libedit userland/base/libedit/readline.c $< -o $@

HOST_TEST_BINARIES := $(BUILD)/tests/sh-lexer-host-test \
	$(BUILD)/tests/sh-expand-host-test \
	$(BUILD)/tests/sh-arithmetic-host-test \
	$(BUILD)/tests/sh-alias-host-test \
	$(BUILD)/tests/sh-vars-host-test \
	$(BUILD)/tests/sh-glob-host-test \
	$(BUILD)/tests/libedit-host-test \
	$(BUILD)/tests/blkdev-host-test \
	$(BUILD)/tests/bufcache-host-test \
	$(BUILD)/tests/checkpoint-host-test \
	$(BUILD)/tests/fault-injection-host-test \
	$(BUILD)/tests/vfs-host-test \
	$(BUILD)/tests/ufs1-vfs-host-test \
	$(BUILD)/tests/ufs1-multicg-vfs-host-test \
	$(BUILD)/tests/ufs2-multicg-vfs-host-test \
	$(BUILD)/tests/ufs-consistency-host-test \
	$(BUILD)/tests/cred-host-test \
	$(BUILD)/tests/quota-host-test \
	$(BUILD)/tests/ufs-snapshot-host-test \
	$(BUILD)/tests/clock-rtc-host-test \
	$(BUILD)/tests/fat-host-test \
	$(BUILD)/tests/fat-write-host-test \
	$(BUILD)/tests/fat32-host-test \
	$(BUILD)/tests/env-host-test \
	$(BUILD)/tests/user-noct-memory-host-test \
	$(BUILD)/tests/heap-context-host-test \
	$(BUILD)/tests/elf-host-test \
	$(BUILD)/tests/elf-m68k-host-test \
	$(BUILD)/tests/m68k-mmu-host-test \
	$(BUILD)/tests/m68k-space-host-test \
	$(BUILD)/tests/x68k-memory-map-host-test \
	$(BUILD)/tests/x68k-handoff-host-test \
	$(BUILD)/tests/x68k-mmio-host-test \
	$(BUILD)/tests/x68k-keyboard-host-test \
	$(BUILD)/tests/m68k-exception-host-test \
	$(BUILD)/tests/m68k-fpu-frame-host-test \
	$(BUILD)/tests/x68k-partition-host-test \
	$(BUILD)/tests/x68k-scsi-host-test \
	$(BUILD)/tests/x68k-scsi-disk-host-test \
	$(BUILD)/tests/sched-host-test \
	$(BUILD)/tests/smp-contract-host-test \
	$(BUILD)/tests/concurrency-host-test \
	$(BUILD)/tests/vmspace-host-test \
	$(BUILD)/tests/vm-commit-host-test \
	$(BUILD)/tests/swap-host-test \
	$(BUILD)/tests/vm-reclaim-host-test \
	$(BUILD)/tests/packet-buf-host-test \
	$(BUILD)/tests/net-device-host-test \
	$(BUILD)/tests/packet-socket-host-test \
	$(BUILD)/tests/inet-stack-host-test \
	$(BUILD)/tests/dhcp-host-test \
	$(BUILD)/tests/dns-host-test
CHECK_RUN_TARGETS := libc-host-test softfloat-host-test \
	uapi-abi-layout-check posix-header-check posix-api-matrix-check \
	susv4-header-check susv4-libc-host-test crypt-host-test \
	ufs1-format-host-test ufs2-format-host-test

userland-command-host-test: tests/test-userland-commands-host.sh
	bash tests/test-userland-commands-host.sh

CHECK_RUN_TARGETS += userland-command-host-test

overlay-journal-format-host-test: tests/overlay-journal-format-host-test.py \
	$(BUILD_TOOLS_DIR)/overlay_journal_format.py
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) tests/overlay-journal-format-host-test.py

CHECK_RUN_TARGETS += overlay-journal-format-host-test

ufs1-format-python-test: tests/ufs1-format-host-test.py \
	tools/build/ufs1_format.py tools/build/check-ufs1-image.py
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) tests/ufs1-format-host-test.py

CHECK_RUN_TARGETS += ufs1-format-python-test

ufs2-format-python-test: tests/ufs2-format-host-test.py \
	tools/build/ufs1_format.py tools/build/ufs2_format.py tools/build/check-ufs1-image.py \
	tools/build/check-ufs2-image.py
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) tests/ufs2-format-host-test.py

CHECK_RUN_TARGETS += ufs2-format-python-test

# ----------------------------------------------------------------------
# Architecture-specific rules (artifacts, disk images, QEMU tests,
# milestone verification chains).

# Root filesystem assembly is Make-controlled.  Format-specific encoders and
# validators remain small standalone tools under tools/build; no normal build
# target depends on the legacy scripts directory.
ARCH_IMAGE_DIR := build/arch-images
DATA_IMAGE := build/data.img
SWAP_IMAGE := build/swapfile
DATA_IMAGE_TOOLS := $(BUILD_TOOLS_DIR)/make-data-image.py \
	$(BUILD_TOOLS_DIR)/overlay_journal_format.py \
	$(BUILD_TOOLS_DIR)/ufs1_format.py
ARCH_IMAGE_TOOLS := $(BUILD_TOOLS_DIR)/make-arch-overlay-image.py \
	$(BUILD_TOOLS_DIR)/check-arch-overlay-image.py
ARCH_UFS_IMAGE_TOOLS := $(BUILD_TOOLS_DIR)/make-arch-overlay-ufs.py \
	$(BUILD_TOOLS_DIR)/check-arch-overlay-ufs.py \
	$(BUILD_TOOLS_DIR)/check-ufs1-image.py \
	$(BUILD_TOOLS_DIR)/check_ufs1_import.py \
	$(BUILD_TOOLS_DIR)/ufs1_format.py
ZEDBSD_ACCOUNT_INPUTS := userland/base/etc/passwd userland/base/etc/group \
	userland/base/etc/shadow
ZEDBSD_ACCOUNT_FILES := --file /etc/passwd=userland/base/etc/passwd \
	--file /etc/group=userland/base/etc/group \
	--file /etc/shadow=userland/base/etc/shadow \
	--mode /etc/passwd=0644 --mode /etc/group=0644 \
	--mode /etc/shadow=0400
ZEDBSD_XZED_SESSION_INPUTS := userland/X11/session/startx \
	userland/X11/session/Xzedrc userland/X11/session/zwm.conf
ZEDBSD_XZED_SESSION_FILES := $(if $(filter zwm,$(ZEDBSD_USER_PROGRAMS)),\
	--file /bin/startx=userland/X11/session/startx \
	--file /etc/Xzed/Xzedrc=userland/X11/session/Xzedrc \
	--file /etc/Xzed/zwm.conf=userland/X11/session/zwm.conf \
	--mode /bin/startx=0755 --mode /etc/Xzed/Xzedrc=0755)
ZEDBSD_PACKAGE_INPUTS += $(ZEDBSD_XZED_SESSION_INPUTS)
ZEDBSD_PACKAGE_FILES += $(ZEDBSD_XZED_SESSION_FILES)

$(DATA_IMAGE): $(DATA_IMAGE_TOOLS)
	@mkdir -p $(dir $@)
	PYTHONPATH=$(BUILD_TOOLS_DIR) $(PYTHON) \
		$(BUILD_TOOLS_DIR)/make-data-image.py --output $@

$(SWAP_IMAGE): $(BUILD_TOOLS_DIR)/make-swapfile.py
	@mkdir -p $(dir $@)
	$(PYTHON) $(BUILD_TOOLS_DIR)/make-swapfile.py --size-mib 64 --output $@

# $(1): output, $(2): profile, $(3): prerequisites, $(4): --file arguments.
define ZEDBSD_ARCH_IMAGE_RULE
$(1): $(3) $(ZEDBSD_PACKAGE_INPUTS) $(ARCH_IMAGE_TOOLS)
	@mkdir -p $$(dir $$@)
	$$(PYTHON) $$(BUILD_TOOLS_DIR)/make-arch-overlay-image.py --force \
		--profile $(2) --output $$@ $(4) $(ZEDBSD_PACKAGE_FILES)

$(1)-check: $(1)
	$$(PYTHON) $$(BUILD_TOOLS_DIR)/check-arch-overlay-image.py \
		--profile $(2) --image $$< $(4) $(ZEDBSD_PACKAGE_FILES)
endef

# $(1): output, $(2): profile, $(3): prerequisites, $(4): --file arguments.
define ZEDBSD_ARCH_UFS_IMAGE_RULE
$(1): $(3) $(ZEDBSD_PACKAGE_INPUTS) $(ARCH_UFS_IMAGE_TOOLS)
	@mkdir -p $$(dir $$@)
	PYTHONPATH=$$(BUILD_TOOLS_DIR) $$(PYTHON) \
		$$(BUILD_TOOLS_DIR)/make-arch-overlay-ufs.py --force \
		--profile $(2) --output $$@ $(4) $(ZEDBSD_PACKAGE_FILES)

$(1)-check: $(1)
	PYTHONPATH=$$(BUILD_TOOLS_DIR) $$(PYTHON) \
		$$(BUILD_TOOLS_DIR)/check-arch-overlay-ufs.py \
		--profile $(2) --image $$< $(4) $(ZEDBSD_PACKAGE_FILES)
endef

# $(1): tar output, $(2): prerequisites, $(3): --file/--mode arguments.
# The staging tree is the canonical rootfs artifact.  The tarball is retained
# as a packaging artifact and is produced from that tree.
define ZEDBSD_ROOTFS_TAR_RULE
$(BUILD)/rootfs/.stamp: $(2) $(ZEDBSD_PACKAGE_INPUTS)
	@rm -rf $(BUILD)/rootfs
	@mkdir -p $(BUILD)/rootfs
	@set -- $(3) $(ZEDBSD_PACKAGE_FILES); while test $$$$# -gt 0; do \
		option=$$$$1; specification=$$$$2; shift 2; \
		path=$$$${specification%%=*}; value=$$$${specification#*=}; \
		path=$$$${path#/}; destination=$(BUILD)/rootfs/$$$$path; \
		case $$$$option in \
		--file) mkdir -p "$$$${destination%/*}"; cp -f "$$$$value" "$$$$destination" ;; \
		--mode) chmod "$$$$value" "$$$$destination" ;; \
		*) echo "unknown rootfs option: $$$$option" >&2; exit 2 ;; \
		esac; \
	done
	@touch $$@

$(1): $(BUILD)/rootfs/.stamp
	@rm -f $$@
	@tar -C $(BUILD)/rootfs -czf $$@ .
endef

ifneq ($(strip $(ZEDBSD_PLATFORM)),)
include $(PLATFORM_MAKEFILE)
endif

.PHONY: vmunix rootfs world
world: vmunix rootfs

check: $(HOST_TEST_BINARIES) $(CHECK_RUN_TARGETS)
	@set -e; for test in $(HOST_TEST_BINARIES); do \
		echo "$$test"; $$test; done

clean:
	rm -rf $(BUILD)

distclean:
	rm -rf build

-include $(wildcard $(BUILD)/*.d $(BUILD)/*/*.d $(BUILD)/*/*/*.d \
	$(BUILD)/*/*/*/*.d $(BUILD)/*/*/*/*/*.d \
	$(BUILD)/*/*/*/*/*/*.d $(BUILD)/*/*/*/*/*/*/*.d)

.PHONY: check clean distclean \
	overlay-journal-format-host-test uapi-abi-layout-check \
	posix-header-check posix-api-matrix-check susv4-header-check \
	susv4-libc-host-test crypt-host-test userland-command-host-test \
	ufs1-format-host-test \
	ufs2-format-host-test ufs1-format-python-test ufs2-format-python-test
