# zedBSD — a scriptable bootstrap environment.
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib
#
# Layout:
# include/ public HAL and kernel interfaces
# src/hal/ HAL and board support implementation
# src/kern/ platform-neutral kernel services
# src/drivers/ device and bus driver implementation
# userland/base/ base-system programs and libc glue
# userland/comp/ compilers
# userland/X11/ X11 servers and applications
# userland/firmware/ optional device firmware, selected per device
# userland/packages/ optional language runtimes, editors, and packages
# libc/ freestanding libc subset
# src/libc/ zedBSD integer-only soft-float/compiler runtime
# platform/<arch>/ per-architecture targets (IPLs, stages, console)
#
# The target is selected exclusively by config.mk, generated by menuconfig.
# Each target delegates to a platform Makefile and places its artifacts below
# build/<platform>/. Architecture-neutral host artifacts stay shared at the
# top of build/ (build/host-noct, build/releases).

AS := as
LD := ld
OBJCOPY := objcopy
CC := gcc
HOSTCC ?= cc
HOSTCXX ?= c++
PYTHON ?= python3
ZEDBSD_TOPLEVEL_BUILD := 1
include toolchain/llvm/llvm.mk
# Noct is a userland package and keeps its own build; this only records
# that the build's scripts need the interpreter it produces for the host.
# The package defines NOCT and NOCT_HOST_BUILD_STAMP when it is read.
ZEDBSD_IMAGE_HOST := build/zedimage-host
.DEFAULT_GOAL := disk-image

ZEDBSD_CONFIG ?= config.mk
-include $(ZEDBSD_CONFIG)

# menuconfig and help remain available before the first configuration is
# saved. Every build target requires the target information from config.mk.
ZEDBSD_CONFIG_OPTIONAL_GOALS := menuconfig help list-user-programs \
	menuconfig-host-test rtl8822b-firmware-fixture-cache \
	intelax211-firmware-fixture-cache i915-firmware-fixture-cache \
	download toolchain \
	noct-toolchain-smoke noct-download noct-source \
	noct-target-source-verify noct-host-source noct-host-source-verify \
	llvm-download llvm-source llvm-source-verify llvm-configure llvm-build llvm-toolchain \
	llvm-host-archive toolchain-cache \
	sysroot-amd64 sysroot-i386 sysroots \
	patch openssl-download openssl-source openssh-download openssh-source
ifeq ($(strip $(ZEDBSD_PLATFORM)),)
ifneq ($(filter-out $(ZEDBSD_CONFIG_OPTIONAL_GOALS),$(MAKECMDGOALS)),)
$(error config.mk is missing or invalid; run 'make menuconfig')
endif
ifeq ($(strip $(MAKECMDGOALS)),)
$(error config.mk is missing or invalid; run 'make menuconfig')
endif
endif

ZEDBSD_PLATFORM_DIR := $(strip \
	$(if $(filter i386,$(ZEDBSD_PLATFORM)),pcat,\
	$(if $(filter rpi4,$(ZEDBSD_PLATFORM)),arm64,\
	$(if $(filter sun4u,$(ZEDBSD_PLATFORM)),sparcv9,\
	$(ZEDBSD_PLATFORM)))))
PLATFORM_MAKEFILE := platform/$(ZEDBSD_PLATFORM_DIR)/Makefile
ifeq ($(wildcard $(PLATFORM_MAKEFILE)),)
ifneq ($(strip $(ZEDBSD_PLATFORM)),)
$(error Unsupported ZEDBSD_PLATFORM '$(ZEDBSD_PLATFORM)' in config.mk)
endif
endif
BUILD := build/$(ZEDBSD_PLATFORM_DIR)

# Maintained x86 target artifacts are built only by the project-owned LLVM
# installation. HOSTCC/HOSTCXX remain independent bootstrap compilers for
# host Noct and LLVM themselves.
ZEDBSD_TARGET_LLVM_BIN := $(abspath build/llvm/bin)
ifeq ($(ZEDBSD_ARCHITECTURE),amd64)
ZEDBSD_TARGET_TRIPLE := x86_64-unknown-zedbsd
ZEDBSD_TARGET_SYSROOT := $(abspath build/amd64/sysroot)
else ifeq ($(ZEDBSD_ARCHITECTURE),i386)
ZEDBSD_TARGET_TRIPLE := i386-unknown-zedbsd
ZEDBSD_TARGET_SYSROOT := $(abspath build/i386/sysroot)
endif
ifneq ($(strip $(ZEDBSD_TARGET_TRIPLE)),)
ZEDBSD_TARGET_CLANG := $(ZEDBSD_TARGET_LLVM_BIN)/clang
CC := $(ZEDBSD_TARGET_CLANG) --target=$(ZEDBSD_TARGET_TRIPLE) \
	--sysroot=$(ZEDBSD_TARGET_SYSROOT)
AS := $(CC)
LD := $(ZEDBSD_TARGET_LLVM_BIN)/ld.lld
AR := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-ar
RANLIB := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-ranlib
NM := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-nm
OBJCOPY := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-objcopy
OBJDUMP := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-objdump
READELF := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-readelf
STRIP := $(ZEDBSD_TARGET_LLVM_BIN)/llvm-strip
endif

# Link-time optimization of vmunix (ws053) on the platforms that build with
# clang and ld.lld: each platform puts ZEDBSD_KERNEL_LTO_CFLAGS on every C
# object of the kernel, its drivers and the HAL, which are optimized together
# (the user's decision of 2026-09-24); the assembly stays native.
# ZEDBSD_KERNEL_LTO chooses full (the default: the fastest and smallest
# kernel on amd64, a link of about 20 s), thin (a link of a few seconds) or
# none.
ZEDBSD_KERNEL_LTO ?= full
ifeq ($(ZEDBSD_KERNEL_LTO),full)
ZEDBSD_KERNEL_LTO_CFLAGS := -flto
else ifeq ($(ZEDBSD_KERNEL_LTO),thin)
ZEDBSD_KERNEL_LTO_CFLAGS := -flto=thin
else ifeq ($(ZEDBSD_KERNEL_LTO),none)
ZEDBSD_KERNEL_LTO_CFLAGS :=
else
$(error ZEDBSD_KERNEL_LTO must be full, thin or none, not '$(ZEDBSD_KERNEL_LTO)')
endif

# The kernel objects are compiled again when the LTO flags change: this
# content-stable stamp, a prerequisite of each of them, is rewritten only
# when they differ.
ZEDBSD_KERNEL_LTO_STAMP := $(BUILD)/.kernel-lto
.PHONY: FORCE_ZEDBSD_KERNEL_LTO
FORCE_ZEDBSD_KERNEL_LTO:

$(ZEDBSD_KERNEL_LTO_STAMP): FORCE_ZEDBSD_KERNEL_LTO
	@mkdir -p $(dir $@)
	@value='lto=$(ZEDBSD_KERNEL_LTO_CFLAGS)'; \
 if ! test -f $@ || ! grep -Fqx -- "$$value" $@; then \
 printf '%s\n' "$$value" > $@.tmp; \
 mv $@.tmp $@; \
 fi

# Architecture + Board owns the image-layout Variant set. These values are
# image metadata only: do not add them to ZEDBSD_CPPFLAGS, source lists, object
# lists, or firmware-loader selection.
ZEDBSD_VARIANTS_i386_pcat := default
# amd64 defaults to native (WS062): UEFI, the kernel on the ESP, a UFS root
# partition and a swap partition.  hybrid, uefi and bios stay selectable.
ZEDBSD_VARIANTS_amd64_pcat := native hybrid uefi bios
ZEDBSD_VARIANTS_i386_pc98 := default
ZEDBSD_VARIANTS_arm64_rpi4 := default
ZEDBSD_VARIANTS_sparcv9_sun4u := default
ZEDBSD_VARIANTS_m68k_x68k := default
ZEDBSD_PLATFORM_TARGET_i386 := i386_pcat
ZEDBSD_PLATFORM_TARGET_amd64 := amd64_pcat
ZEDBSD_PLATFORM_TARGET_pc98 := i386_pc98
ZEDBSD_PLATFORM_TARGET_rpi4 := arm64_rpi4
ZEDBSD_PLATFORM_TARGET_sun4u := sparcv9_sun4u
ZEDBSD_PLATFORM_TARGET_x68k := m68k_x68k
ZEDBSD_TARGET_VARIANT_KEY := $(ZEDBSD_ARCHITECTURE)_$(ZEDBSD_BOARD)
ZEDBSD_PLATFORM_TARGET := $(ZEDBSD_PLATFORM_TARGET_$(ZEDBSD_PLATFORM))
ZEDBSD_TARGET_VARIANTS := \
	$(ZEDBSD_VARIANTS_$(ZEDBSD_TARGET_VARIANT_KEY))
ifeq ($(origin ZEDBSD_VARIANT),undefined)
ZEDBSD_VARIANT := $(firstword $(ZEDBSD_TARGET_VARIANTS))
endif
ZEDBSD_TARGET_HIERARCHY_VALID := $(and \
	$(filter 1,$(words $(ZEDBSD_PLATFORM))),\
	$(filter 1,$(words $(ZEDBSD_ARCHITECTURE))),\
	$(filter 1,$(words $(ZEDBSD_BOARD))),\
	$(strip $(ZEDBSD_PLATFORM_TARGET)),\
	$(if $(filter-out $(ZEDBSD_PLATFORM_TARGET),\
 $(ZEDBSD_TARGET_VARIANT_KEY)),,yes))
ZEDBSD_VARIANT_VALID := $(and $(strip $(ZEDBSD_VARIANT)),\
	$(filter 1,$(words $(ZEDBSD_VARIANT))),\
	$(if $(filter-out $(ZEDBSD_TARGET_VARIANTS),$(ZEDBSD_VARIANT)),,yes))

# Reject a hand-edited image contract before any standard image target begins.
# menuconfig and source-only targets remain usable so an invalid file can be
# repaired without deleting it.
ZEDBSD_IMAGE_REQUESTED := $(if $(strip $(MAKECMDGOALS)),\
	$(filter disk-image run check-disk-image validate-image-config \
 %.img %.hd,$(MAKECMDGOALS)),default)
ifneq ($(strip $(ZEDBSD_IMAGE_REQUESTED)),)
ifeq ($(strip $(ZEDBSD_TARGET_HIERARCHY_VALID)),)
$(error Invalid target hierarchy ZEDBSD_PLATFORM='$(ZEDBSD_PLATFORM)' \
	ZEDBSD_ARCHITECTURE='$(ZEDBSD_ARCHITECTURE)' ZEDBSD_BOARD='$(ZEDBSD_BOARD)')
endif
ifeq ($(strip $(ZEDBSD_VARIANT_VALID)),)
$(error Invalid ZEDBSD_VARIANT '$(ZEDBSD_VARIANT)' for \
	Architecture '$(ZEDBSD_ARCHITECTURE)' Board '$(ZEDBSD_BOARD)'; expected one of: \
	$(ZEDBSD_TARGET_VARIANTS))
endif
endif

CONFIG_DRIVER_NE2000 ?= y
CONFIG_DRIVER_LGY98 ?= y
CONFIG_DRIVER_GRAPHICS ?= y
CONFIG_DRIVER_PCI_UHCI ?= y
CONFIG_DRIVER_PCI_EHCI ?= y
CONFIG_DRIVER_PCI_XHCI ?= y
CONFIG_DRIVER_PCI_NVME ?= y
CONFIG_DRIVER_PCI_VENUS ?= n
CONFIG_DRIVER_PCI_I915 ?= n
# HD Audio is on by default where its driver builds (amd64); a config written
# by the menu names it explicitly.
CONFIG_DRIVER_PCI_HDA ?= $(if $(filter amd64,$(ZEDBSD_PLATFORM)),y,n)
CONFIG_DRIVER_PCI_INTEL_AX211 ?= n
CONFIG_DRIVER_USB_STORAGE ?= y
CONFIG_DRIVER_USB_CDC_NCM ?= y
CONFIG_DRIVER_USB_CDC_ECM ?= y
CONFIG_DRIVER_USB_HID ?= y
CONFIG_DRIVER_USB_HUB ?= y
CONFIG_DRIVER_USB_RTL8822BU ?= n
CONFIG_KERNEL_TEST_CHECKPOINTS ?= n
CONFIG_PCAT_SERIAL_MIRROR ?= n
CONFIG_KERNEL_USB_HID_CHECKPOINT ?= n
CONFIG_BUF_CACHE_KIB ?= 0
CONFIG_GPU_JOB_RESERVATION_MS ?= 10000
CONFIG_GPU_JOB_EXECUTION_MS ?= 60000
CONFIG_GPU_JOB_STOP_MS ?= 10000
CONFIG_GPU_CONTROL_MS ?= 10000

# Where packages install (ws034-p037): everything a package brings goes under
# /usr -- commands in /usr/bin (ZEDBSD_PACKAGE_BINDIR), daemons in /usr/sbin or
# /usr/libexec, libraries in /usr/lib, headers in /usr/include, data and
# licenses in /usr/share.  Only configuration goes to /etc.  / itself (/bin,
# /sbin, /lib) is the base system's; the runtime loader searches /lib first
# and then /usr/lib.
ZEDBSD_PACKAGE_BINDIR := /usr/bin

# Userland packages register themselves from userland/**/Makefile. Kernel
# makefiles provide ABI-specific link rules, while package ownership, source
# paths and menu metadata live with each program.
USERLAND_PACKAGES :=
ZEDBSD_USERLAND_DOWNLOAD_TARGETS :=
ZEDBSD_USERLAND_PATCH_TARGETS :=
define ZEDBSD_USERLAND_PACKAGE
USERLAND_PACKAGES += $(1)
USERLAND_$(1)_LABEL := $(2)
USERLAND_$(1)_PLATFORMS := $(3)
USERLAND_$(1)_DEFAULT := $(4)
USERLAND_$(1)_CLASS := $(5)
USERLAND_$(1)_SOURCES := $(6)
USERLAND_$(1)_SELECTABLE := $(7)
USERLAND_$(1)_MENU := $(8)
USERLAND_$(1)_PACKAGE := $(9)
USERLAND_$(1)_REQUIRE := $(10)
USERLAND_$(1)_MODE := $(11)
USERLAND_$(1)_TYPE := $(if $(12),$(12),\
	$(if $(filter library,$(5)),library,program))
USERLAND_$(1)_DATA := $(13)
USERLAND_$(1)_HEADERS := $(14)
USERLAND_$(1)_INSTALL_DIR := $(if $(15),$(15),bin)
endef
USERLAND_PACKAGE_MAKEFILES := $(sort \
	$(wildcard userland/*/Makefile) \
	$(wildcard userland/*/*/Makefile) \
	$(wildcard userland/*/*/*/Makefile))
include $(USERLAND_PACKAGE_MAKEFILES)
ZEDBSD_ALL_USER_PROGRAMS := $(foreach program,$(USERLAND_PACKAGES),\
	$(if $(filter y,$(USERLAND_$(program)_SELECTABLE)),$(program)))
# A program's platform list says where it builds (* is everywhere); the
# default set is only what builds for this platform.
user_program_applies = $(or $(filter *,$(USERLAND_$(1)_PLATFORMS)),\
	$(filter $(ZEDBSD_PLATFORM),$(USERLAND_$(1)_PLATFORMS)))
ZEDBSD_DEFAULT_USER_PROGRAMS := $(foreach program,$(ZEDBSD_ALL_USER_PROGRAMS),\
	$(if $(filter y,$(USERLAND_$(program)_DEFAULT)),\
	$(if $(call user_program_applies,$(program)),$(program))))
USERLAND_BASIC_PROGRAMS := $(foreach program,$(USERLAND_PACKAGES),\
	$(if $(filter basic,$(USERLAND_$(program)_CLASS)),$(program)))
USERLAND_NETWORK_PROGRAMS := $(foreach program,$(USERLAND_PACKAGES),\
	$(if $(filter network,$(USERLAND_$(program)_CLASS)),$(program)))
# A valid legacy/minimal config may omit ZEDBSD_USER_PROGRAMS. Honor package
# defaults in that case; selecting every optional entry would turn a normal
# offline build into an implicit source download.
ZEDBSD_USER_PROGRAMS ?= $(ZEDBSD_DEFAULT_USER_PROGRAMS)

# Remove held package roots before dependency expansion. Otherwise a stale
# configuration that still names a held application could retain its
# dependencies even though the application itself is suppressed.  Nothing is
# held at present: a package named here is offered by the menu and then
# quietly dropped, so a package that cannot be built belongs out of the menu
# rather than in this list.
ZEDBSD_TARGET_PACKAGE_HOLD :=
override ZEDBSD_USER_PROGRAMS := $(filter-out \
	$(ZEDBSD_TARGET_PACKAGE_HOLD),$(ZEDBSD_USER_PROGRAMS))

# Package dependencies are named by their registered stable path (for example,
# editors/remacs -> base/noct). Resolve those paths back to program names even
# when config.mk was hand-edited.
user_program_dependency_names = $(strip $(foreach program,$(1),\
	$(foreach requirement,$(USERLAND_$(program)_REQUIRE),\
 $(foreach candidate,$(USERLAND_PACKAGES),\
 $(if $(filter $(requirement),$(USERLAND_$(candidate)_PACKAGE)),\
 $(candidate))))))
ZEDBSD_USER_PROGRAMS_DEPS_1 := $(sort $(ZEDBSD_USER_PROGRAMS) \
	$(call user_program_dependency_names,$(ZEDBSD_USER_PROGRAMS)))
ZEDBSD_USER_PROGRAMS_DEPS_2 := $(sort $(ZEDBSD_USER_PROGRAMS_DEPS_1) \
	$(call user_program_dependency_names,$(ZEDBSD_USER_PROGRAMS_DEPS_1)))
ZEDBSD_USER_PROGRAMS_DEPS_3 := $(sort $(ZEDBSD_USER_PROGRAMS_DEPS_2) \
	$(call user_program_dependency_names,$(ZEDBSD_USER_PROGRAMS_DEPS_2)))
override ZEDBSD_USER_PROGRAMS := $(ZEDBSD_USER_PROGRAMS_DEPS_3)
# The RTL8822B initialization tables are BSD-3-Clause data embedded in the
# kernel. Binary images containing that driver must carry the corresponding
# notice even when the separately licensed firmware package is not selected.
ifeq ($(strip $(CONFIG_DRIVER_USB_RTL8822BU)),y)
override ZEDBSD_USER_PROGRAMS := $(sort \
	$(ZEDBSD_USER_PROGRAMS) rtl8822b-tables-license)
endif
# The AX211 driver contains wire-format work derived from OpenBSD iwx(4) and
# Intel sources. Binary images containing the driver must reproduce both
# notices independently of the separately selected firmware package.
ifeq ($(strip $(CONFIG_DRIVER_PCI_INTEL_AX211)),y)
override ZEDBSD_USER_PROGRAMS := $(sort \
	$(ZEDBSD_USER_PROGRAMS) intel-ax211-driver-license)
endif
ifneq ($(strip $(ZEDBSD_TARGET_TRIPLE)),)
override ZEDBSD_USER_PROGRAMS := $(sort \
	$(ZEDBSD_USER_PROGRAMS) llvm-runtime-license)
endif
# A saved configuration may be reused after changing targets. Do not let
# packages selected for another ABI become impossible prerequisites of the
# current root filesystem (PC/AT i386 is named "pcat" by the build system).
ZEDBSD_USER_PLATFORM := $(ZEDBSD_PLATFORM)
override ZEDBSD_USER_PROGRAMS := $(foreach program,$(ZEDBSD_USER_PROGRAMS),\
	$(if $(filter * $(ZEDBSD_USER_PLATFORM),\
 $(USERLAND_$(program)_PLATFORMS)),$(program)))
# Essential administrative tools are present even when an older config.mk
# predates their package registration.
override ZEDBSD_USER_PROGRAMS := $(sort $(ZEDBSD_USER_PROGRAMS) at batch \
	blkid diskpart mkfs mkswap crontab getty gettext halt hostname init logger login lp lpr mailx msgfmt ngettext \
	cron net networkd ntpdate poweroff reboot service shutdown swapoff swapon syslogd talk wifi)
# Xzed cannot operate without the kernel graphics character device. Keep
# hand-edited and older saved configurations from producing an unusable
# userland/kernel combination.
ifneq ($(filter Xzed,$(ZEDBSD_USER_PROGRAMS)),)
override CONFIG_DRIVER_GRAPHICS := y
endif
# Only PC/AT and PC-98 currently provide a /dev/graphics implementation.
# Keep this derived capability internal: an unsupported target may still carry
# an old CONFIG_DRIVER_GRAPHICS=y setting without acquiring a generic node or
# an unresolved registration symbol.
ZEDBSD_GRAPHICS_BACKEND := $(strip \
	$(if $(filter pcat amd64,$(ZEDBSD_PLATFORM_DIR)),pcat,\
	$(if $(filter pc98,$(ZEDBSD_PLATFORM_DIR)),pc98)))
override CONFIG_DRIVER_GRAPHICS_DEVICE := $(if $(and \
	$(filter y,$(CONFIG_DRIVER_GRAPHICS)),$(ZEDBSD_GRAPHICS_BACKEND)),y,n)
# Kernel object lists and preprocessor guards both depend on this derived
# capability. Keep a content-stable stamp so changing either config.mk or a
# command-line CONFIG_DRIVER_GRAPHICS override invalidates an existing BUILD
# without forcing an otherwise unchanged kernel to rebuild every time.
ZEDBSD_GRAPHICS_CONFIG_STAMP := $(BUILD)/.graphics-device-config
.PHONY: FORCE_ZEDBSD_GRAPHICS_CONFIG
FORCE_ZEDBSD_GRAPHICS_CONFIG:

$(ZEDBSD_GRAPHICS_CONFIG_STAMP): FORCE_ZEDBSD_GRAPHICS_CONFIG
	@mkdir -p $(dir $@)
	@value='CONFIG_DRIVER_GRAPHICS_DEVICE=$(CONFIG_DRIVER_GRAPHICS_DEVICE)'; \
 if ! test -f $@ || ! grep -Fqx -- "$$value" $@; then \
 printf '%s\n' "$$value" > $@.tmp; \
 mv $@.tmp $@; \
 fi
ZEDBSD_MISSING_PACKAGE_REQUIREMENTS := $(sort \
	$(foreach program,$(ZEDBSD_USER_PROGRAMS),\
 $(foreach requirement,$(USERLAND_$(program)_REQUIRE),\
 $(if $(filter $(requirement),\
 $(foreach candidate,$(USERLAND_PACKAGES),\
 $(USERLAND_$(candidate)_PACKAGE))),,\
 $(requirement)))))
ifneq ($(strip $(ZEDBSD_MISSING_PACKAGE_REQUIREMENTS)),)
$(error Unknown userland package dependencies: \
	$(ZEDBSD_MISSING_PACKAGE_REQUIREMENTS))
endif
USERLAND_SELECTED_BASIC_PROGRAMS = $(filter $(ZEDBSD_USER_PROGRAMS),\
	$(USERLAND_BASIC_PROGRAMS))
USERLAND_SELECTED_NETWORK_PROGRAMS = $(filter $(ZEDBSD_USER_PROGRAMS),\
	$(USERLAND_NETWORK_PROGRAMS))
zedbsd_userland_destination = /$(USERLAND_$(1)_INSTALL_DIR)/$(1)
ZEDBSD_USERLAND_FILE_MODES = $(foreach program,$(ZEDBSD_USER_PROGRAMS),\
	$(if $(USERLAND_$(program)_MODE),\
 --mode $(call zedbsd_userland_destination,$(program))=$(USERLAND_$(program)_MODE)))
ZEDBSD_SELECTED_DATA_PACKAGES = $(foreach package,$(ZEDBSD_USER_PROGRAMS),\
	$(if $(strip $(USERLAND_$(package)_DATA)),$(package)))
ZEDBSD_USERLAND_DATA_INPUTS = $(foreach package,\
	$(ZEDBSD_SELECTED_DATA_PACKAGES),$(foreach entry,\
 $(USERLAND_$(package)_DATA),$(word 2,$(subst =, ,$(entry)))))
ZEDBSD_USERLAND_DATA_FILES = $(foreach package,\
	$(ZEDBSD_SELECTED_DATA_PACKAGES),$(foreach entry,\
 $(USERLAND_$(package)_DATA),--file $(entry)))
ZEDBSD_USERLAND_DATA_MODES = $(foreach package,\
	$(ZEDBSD_SELECTED_DATA_PACKAGES),$(foreach entry,\
 $(USERLAND_$(package)_DATA),\
 --mode $(word 1,$(subst =, ,$(entry)))=0644))

# $(1): object tree prefix, $(2): registered package name.
define ZEDBSD_USERLAND_OBJECTS
$(patsubst %.c,$(1)/%.o,$(filter %.c,$(USERLAND_$(2)_SOURCES))) \
$(patsubst %.S,$(1)/%.o,$(filter %.S,$(USERLAND_$(2)_SOURCES)))
endef

.PHONY: list-user-programs
list-user-programs:
	@$(foreach program,$(ZEDBSD_ALL_USER_PROGRAMS),printf '%s|%s|%s|%s|%s|%s|%s\n' \
 '$(program)' '$(USERLAND_$(program)_LABEL)' \
 '$(USERLAND_$(program)_PLATFORMS)' \
 '$(USERLAND_$(program)_DEFAULT)' \
 '$(USERLAND_$(program)_MENU)' \
 '$(USERLAND_$(program)_PACKAGE)' \
 '$(USERLAND_$(program)_REQUIRE)';)

.PHONY: menuconfig
menuconfig:
	@$(PYTHON) tools/menuconfig.py --output $(ZEDBSD_CONFIG)

.PHONY: menuconfig-host-test
menuconfig-host-test:
	@$(PYTHON) plan/tools/menuconfig-target-host-test.py

# The wired policy takes no device and runs no command, so what it decides
# can be put to it on the host, where a cable can be moved by writing one.
.PHONY: managed-lan-host-test
managed-lan-host-test:
	@mkdir -p $(BUILD)/host-tests
	@$(HOSTCC) -std=c11 -O2 -Wall -Wextra -Werror -Iplan/ws033/tests/include -Iinclude -I. \
	 userland/base/networkd/managed-lan.c \
	 plan/ws033/tests/managed-lan-host-test.c \
	 -o $(BUILD)/host-tests/managed-lan
	@$(BUILD)/host-tests/managed-lan

.PHONY: validate-image-config
validate-image-config:
	@:

.PHONY: help list-targets
help:
	@printf '%s\n' \
 'zedBSD build interface' \
 '' \
 ' make Build a disk image' \
 ' make menuconfig Configure the build in config.mk' \
 ' make disk-image Build a disk image' \
 ' make world Build vmunix and rootfs' \
 ' make rootfs Build rootfs' \
 ' make vmunix Build the kernel' \
 ' make run Build a disk image and start QEMU' \
 ' make download Acquire all declared external userland inputs' \
 ' make patch Extract and patch every declared external input' \
 ' make toolchain-cache Install the pinned rev-0 LLVM cache (x86_64 Linux)' \
 ' make toolchain Build the toolchain' \
 ' make help Show this summary'

list-targets:
	@printf 'Primary targets:\n'; \
 for target in $(ZEDBSD_PRIMARY_TARGETS); do printf ' %s\n' "$$target"; done
	@printf 'Support targets:\n'; \
 for target in $(ZEDBSD_SUPPORT_TARGETS); do printf ' %s\n' "$$target"; done
	@printf 'Focused checks:\n'; \
 for target in $(ZEDBSD_CHECK_TARGETS); do printf ' %s\n' "$$target"; done

# The LLVM source is verified, and the host generators the clang package's
# cross build runs are built from it, here: with the binary cache nothing else
# does either before packages start using (and patching) that source tree.
toolchain: $(NOCT_HOST_BUILD_STAMP) noct-toolchain-smoke llvm-toolchain \
	sysroots $(ZEDBSD_LLVM_SOURCE_VERIFIED) $(ZEDBSD_LLVM_NATIVE_STAMP)

.PHONY: download
download: $(sort $(ZEDBSD_USERLAND_DOWNLOAD_TARGETS)) llvm-download

# Extracted and patched trees for every declared external input. Acquisition
# and patch preparation stay separate so that a tree is prepared once and then
# built repeatedly without consulting the network again.
.PHONY: patch
patch: $(sort $(ZEDBSD_USERLAND_PATCH_TARGETS))


$(ZEDBSD_IMAGE_HOST): tools/build/zedimage-host.c
	@mkdir -p $(dir $@)
	$(HOSTCC) -std=c11 -O2 -Wall -Wextra -Werror $< -o $@

ZEDBSD_CONFIG_CPPFLAGS := \
	-DCONFIG_DRIVER_NE2000=$(if $(filter y,$(CONFIG_DRIVER_NE2000)),1,0) \
	-DCONFIG_DRIVER_LGY98=$(if $(filter y,$(CONFIG_DRIVER_LGY98)),1,0) \
	-DCONFIG_DRIVER_GRAPHICS=$(if $(filter y,$(CONFIG_DRIVER_GRAPHICS)),1,0) \
	-DCONFIG_DRIVER_GRAPHICS_DEVICE=$(if $(filter y,$(CONFIG_DRIVER_GRAPHICS_DEVICE)),1,0) \
	-DCONFIG_DRIVER_PCI_UHCI=$(if $(filter y,$(CONFIG_DRIVER_PCI_UHCI)),1,0) \
	-DCONFIG_DRIVER_PCI_EHCI=$(if $(filter y,$(CONFIG_DRIVER_PCI_EHCI)),1,0) \
	-DCONFIG_DRIVER_PCI_XHCI=$(if $(filter y,$(CONFIG_DRIVER_PCI_XHCI)),1,0) \
	-DCONFIG_DRIVER_PCI_NVME=$(if $(filter y,$(CONFIG_DRIVER_PCI_NVME)),1,0) \
	-DCONFIG_DRIVER_PCI_VENUS=$(if $(filter y,$(CONFIG_DRIVER_PCI_VENUS)),1,0) \
	-DCONFIG_DRIVER_PCI_I915=$(if $(filter y,$(CONFIG_DRIVER_PCI_I915)),1,0) \
	-DCONFIG_DRIVER_PCI_HDA=$(if $(filter y,$(CONFIG_DRIVER_PCI_HDA)),1,0) \
	-DCONFIG_DRIVER_PCI_INTEL_AX211=$(if $(filter y,$(CONFIG_DRIVER_PCI_INTEL_AX211)),1,0) \
	-DCONFIG_DRIVER_USB_STORAGE=$(if $(filter y,$(CONFIG_DRIVER_USB_STORAGE)),1,0) \
	-DCONFIG_DRIVER_USB_CDC_NCM=$(if $(filter y,$(CONFIG_DRIVER_USB_CDC_NCM)),1,0) \
	-DCONFIG_DRIVER_USB_CDC_ECM=$(if $(filter y,$(CONFIG_DRIVER_USB_CDC_ECM)),1,0) \
	-DCONFIG_DRIVER_USB_HID=$(if $(filter y,$(CONFIG_DRIVER_USB_HID)),1,0) \
	-DCONFIG_DRIVER_USB_HUB=$(if $(filter y,$(CONFIG_DRIVER_USB_HUB)),1,0) \
	-DCONFIG_DRIVER_USB_RTL8822BU=$(if $(filter y,$(CONFIG_DRIVER_USB_RTL8822BU)),1,0) \
	-DCONFIG_KERNEL_USB_HID_CHECKPOINT=$(if $(filter y,$(CONFIG_KERNEL_USB_HID_CHECKPOINT)),1,0) \
	-DCONFIG_BUF_CACHE_KIB=$(CONFIG_BUF_CACHE_KIB) \
	-DCONFIG_GPU_JOB_RESERVATION_MS=$(CONFIG_GPU_JOB_RESERVATION_MS) \
	-DCONFIG_GPU_JOB_EXECUTION_MS=$(CONFIG_GPU_JOB_EXECUTION_MS) \
	-DCONFIG_GPU_JOB_STOP_MS=$(CONFIG_GPU_JOB_STOP_MS) \
	-DCONFIG_GPU_CONTROL_MS=$(CONFIG_GPU_CONTROL_MS)
ifeq ($(CONFIG_KERNEL_TEST_CHECKPOINTS),y)
ZEDBSD_CONFIG_CPPFLAGS += -DKERN_TEST_CHECKPOINTS
endif
ifeq ($(CONFIG_PCAT_SERIAL_MIRROR),y)
ZEDBSD_CONFIG_CPPFLAGS += -DPCAT_SERIAL_MIRROR
endif
# Private test builds may add compile-time fault injection without replacing
# the configured feature macros above. Keep these flags last so a disposable
# BUILD directory records the complete effective configuration in its stamp.
ZEDBSD_TEST_CPPFLAGS ?=
ZEDBSD_CONFIG_CPPFLAGS += $(strip $(ZEDBSD_TEST_CPPFLAGS))
ZEDBSD_PLATFORM_CONFIG_STAMP := $(BUILD)/.platform-config
.PHONY: FORCE_ZEDBSD_PLATFORM_CONFIG
FORCE_ZEDBSD_PLATFORM_CONFIG:

$(ZEDBSD_PLATFORM_CONFIG_STAMP): FORCE_ZEDBSD_PLATFORM_CONFIG
	@mkdir -p $(dir $@)
	@value='$(strip $(ZEDBSD_CONFIG_CPPFLAGS))'; \
 if ! test -f $@ || ! grep -Fqx -- "$$value" $@; then \
 printf '%s\n' "$$value" > $@.tmp; \
 mv $@.tmp $@; \
 fi
BUILD_TOOLS_DIR := tools/build
ZEDBSD_PRIMARY_TARGETS := menuconfig vmunix bootloader rootfs-bin rootfs-usr \
	rootfs world disk-image run toolchain
ZEDBSD_SUPPORT_TARGETS := help list-targets check clean distclean
ZEDBSD_CHECK_TARGETS := check softfloat-host-test \
	check-disk-image \
	phase20-init-notify-host-test phase20-net-config-host-test \
	phase20-networkd-protocol-host-test phase20-dhcp-host-test \
	libc-opcode-check softfloat-opcode-check uapi-abi-layout-check \
	hal-signal-frame-layout-check \
	posix-header-check posix-api-matrix-check susv4-header-check \
	posix2024-header-check posix2024-api-matrix-check \
	posix2024-utility-matrix-check \
	susv4-libc-host-test crypt-host-test gettext-catalog-host-test \
	userland-command-host-test menuconfig-host-test \
	managed-lan-host-test \
	ufs-format-host-test ufs-format-python-test overlay-journal-format-host-test

# Scripts invoked from make receive the configured architecture and build tree.
export ZEDBSD_ARCH := $(ZEDBSD_ARCHITECTURE)
export ZEDBSD_BUILD_DIR := $(CURDIR)/$(BUILD)

ifeq ($(ZEDBSD_ARCHITECTURE),amd64)
ASFLAGS := -m64 -c
else
ASFLAGS := -m32 -c
endif
ifneq ($(strip $(ZEDBSD_TARGET_SYSROOT)),)
ZEDBSD_CPPFLAGS := -nostdinc \
	-isystem $(ZEDBSD_TARGET_SYSROOT)/usr/include \
	-Iinclude -Isrc -I. -I$(BUILD) $(ZEDBSD_CONFIG_CPPFLAGS)
else
ZEDBSD_CPPFLAGS := -nostdinc -Iinclude -Isrc -I. \
	-I$(BUILD) -Iinclude/libc $(ZEDBSD_CONFIG_CPPFLAGS)
endif
ifeq ($(ZEDBSD_ARCHITECTURE),i386)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_I386
else ifeq ($(ZEDBSD_ARCHITECTURE),amd64)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_AMD64
else ifeq ($(ZEDBSD_ARCHITECTURE),arm64)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_ARM64
else ifeq ($(ZEDBSD_ARCHITECTURE),sparcv9)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_SPARCV9
else ifeq ($(ZEDBSD_ARCHITECTURE),m68k)
ZEDBSD_CPPFLAGS += -DHAL_ARCH_M68K
endif
ZEDBSD_CFLAGS := -m32 -march=i386 -Os -ffreestanding -fno-pic -fno-pie \
	-fno-stack-protector -fno-asynchronous-unwind-tables \
	-fno-unwind-tables -ffunction-sections -fdata-sections \
	-Wall -Wextra -Werror

include src/libc/libc.mk
include src/libc/softfloat.mk
include toolchain/llvm/sysroot.mk
ifneq ($(strip $(ZEDBSD_TARGET_SYSROOT)),)
ZEDBSD_COMPILER_RT_OBJECTS := \
	$(ZEDBSD_TARGET_SYSROOT)/usr/lib/libzedbsd-compiler-rt.o \
	$(ZEDBSD_TARGET_SYSROOT)/usr/lib/libclang_rt.builtins.a
ZEDBSD_SOFTFLOAT_OBJECTS := $(ZEDBSD_COMPILER_RT_OBJECTS)
endif

KERN_NET_SOURCES := \
	src/kern/net/packet-buf.c \
	src/kern/net/net-device.c \
	src/kern/net/core.c \
	src/kern/net/socket.c \
	src/kern/net/socket-file.c \
	src/kern/net/unix-socket.c \
	src/kern/net/packet-socket.c \
	src/kern/net/route-socket.c \
	src/kern/net/checksum.c \
	src/kern/net/ethernet.c \
	src/kern/net/route.c \
	src/kern/net/inet-socket.c \
	src/kern/net/wifi/wlan-crypto.c \
	src/kern/net/wifi/wlan-frame.c \
	src/kern/net/wifi/wlan-wpa2-codec.c \
	src/kern/net/wifi/wlan-wpa2.c \
	src/kern/net/wifi/wlan-l2.c \
	src/kern/net/wifi/wlan.c \
	src/kern/net/arp.c \
	src/kern/net/ipv4.c \
	src/kern/net/icmp.c \
	src/kern/net/udp.c \
	src/kern/net/tcp.c
KERN_NET_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_NET_SOURCES))

KERN_BLOCK_IDENTITY_SOURCES := src/kern/block-identity.c
KERN_BLOCK_IDENTITY_OBJS := $(patsubst %.c,$(BUILD)/%.o,\
	$(KERN_BLOCK_IDENTITY_SOURCES))
KERN_FAT_SOURCES := src/drivers/fs/fat.c
KERN_FAT_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_FAT_SOURCES))
KERN_UFS_SOURCES := \
	src/drivers/fs/ufs.c \

KERN_UFS_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_UFS_SOURCES))
KERN_ACL_SOURCES := src/kern/acl.c
KERN_ACL_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_ACL_SOURCES))
KERN_QUOTA_SOURCES := src/kern/quota.c
KERN_QUOTA_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_QUOTA_SOURCES))
KERN_BOOT_SOURCES := src/kern/boot.c
KERN_BOOT_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_BOOT_SOURCES))

# GPU synchronization belongs to the framework selected by its hardware backends.
# Add future GPU backends to this dependency list; generic fd support stays in kern.
KERN_GPU_BACKENDS := $(CONFIG_DRIVER_PCI_VENUS) $(CONFIG_DRIVER_PCI_I915)
KERN_GPU_SOURCES :=
ifneq ($(filter y,$(KERN_GPU_BACKENDS)),)
KERN_GPU_SOURCES := src/drivers/gpu/gpu.c src/drivers/gpu/gpu-fence.c
endif
KERN_GPU_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_GPU_SOURCES))

# The audio framework is built only when an audio hardware backend selects it.
# Add audio backends to this list.
KERN_AUDIO_BACKENDS ?= $(CONFIG_DRIVER_PCI_HDA)
KERN_AUDIO_SOURCES :=
ifneq ($(filter y,$(KERN_AUDIO_BACKENDS)),)
KERN_AUDIO_SOURCES := src/drivers/audio/audio.c
endif
KERN_AUDIO_OBJS := $(patsubst %.c,$(BUILD)/%.o,$(KERN_AUDIO_SOURCES))

# ----------------------------------------------------------------------
# Generic compile rules. Per-object flag overrides use target-specific
# variables; header dependencies come from -MMD.

OBJ_CPPFLAGS = $(ZEDBSD_CPPFLAGS)
OBJ_CFLAGS = $(ZEDBSD_CFLAGS)
OBJ_CC = $(CC)

$(BUILD)/%.o: %.S
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@

# PC/AT and PC-98 keep their established driver object paths even though the
# production source owner is src/drivers. Platform-specific target flags are
# attached to these object names in their vmunix makefiles. The layout stamp
# invalidates pre-move objects which have the same output name but no dependency
# file; a source-only rename can otherwise leave those ABI-stale objects newer
# than their new src/drivers prerequisite.
DRIVER_SOURCE_LAYOUT_STAMP := $(BUILD)/.src-drivers-layout-v1

$(DRIVER_SOURCE_LAYOUT_STAMP):
	@mkdir -p $(dir $@)
	@touch $@

$(BUILD)/drivers/%.o: src/drivers/%.c $(DRIVER_SOURCE_LAYOUT_STAMP)
	@mkdir -p $(dir $@)
	$(OBJ_CC) $(OBJ_CPPFLAGS) $(OBJ_CFLAGS) -MMD -MP -c $< -o $@

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(OBJ_CC) $(OBJ_CPPFLAGS) $(OBJ_CFLAGS) -MMD -MP -c $< -o $@

$(ZEDBSD_LIBC_OBJECTS): OBJ_CC = $(ZEDBSD_LIBC_CC)
$(ZEDBSD_LIBC_OBJECTS): OBJ_CPPFLAGS = $(ZEDBSD_LIBC_CPPFLAGS)
$(ZEDBSD_LIBC_OBJECTS): OBJ_CFLAGS = $(ZEDBSD_LIBC_CFLAGS)

# ----------------------------------------------------------------------
# Architecture-specific rules (artifacts, disk images, QEMU tests,
# milestone verification chains).

# Root filesystem assembly is Make-controlled. Format-specific encoders and
# validators remain small standalone tools under tools/build; no normal build
# target depends on the legacy scripts directory.
ARCH_IMAGE_DIR := build/arch-images
# The root filesystem image is made from this build's root tree, so it lives
# with the build.  In the shared directory above, a build whose tree had not
# changed took whatever image another build (another configuration, or pcat
# and pc98, which share i386) had written last, and booted that root instead
# of its own.  Test images with fixed file lists stay in the shared directory.
ZEDBSD_ROOTFS_IMAGE_DIR := $(BUILD)/arch-images
DATA_IMAGE := build/data.img
SWAP_IMAGE := build/swapfile
DATA_IMAGE_TOOLS := $(BUILD_TOOLS_DIR)/make-data-image.noct \
	$(BUILD_TOOLS_DIR)/overlay_journal_format.noct \
	$(BUILD_TOOLS_DIR)/ufs_format.noct $(ZEDBSD_IMAGE_HOST)
ARCH_IMAGE_TOOLS := $(BUILD_TOOLS_DIR)/make-arch-overlay-image.py \
	$(BUILD_TOOLS_DIR)/check-arch-overlay-image.py
ARCH_UFS_IMAGE_TOOLS := $(BUILD_TOOLS_DIR)/make-arch-overlay-ufs.noct \
	$(BUILD_TOOLS_DIR)/ufs_format.noct $(ZEDBSD_IMAGE_HOST)
ZEDBSD_ACCOUNT_INPUTS := userland/base/etc/passwd userland/base/etc/group \
	userland/base/etc/shadow userland/base/etc/services
ZEDBSD_ACCOUNT_FILES := --file /etc/passwd=userland/base/etc/passwd \
	--file /etc/group=userland/base/etc/group \
	--file /etc/shadow=userland/base/etc/shadow \
	--file /etc/services=userland/base/etc/services \
	--mode /etc/passwd=0644 --mode /etc/group=0644 \
	--mode /etc/shadow=0400 --mode /etc/services=0644
ZEDBSD_BASE_DATA_INPUTS := $(ZEDBSD_USERLAND_DATA_INPUTS)
ZEDBSD_BASE_DATA_FILES := $(ZEDBSD_USERLAND_DATA_FILES) \
	$(ZEDBSD_USERLAND_DATA_MODES)
ZEDBSD_XZED_SESSION_INPUTS := userland/X11/session/startx \
	userland/X11/session/Xzedrc userland/X11/session/zwm.conf
ZEDBSD_XZED_SESSION_FILES := $(if $(filter zwm,$(ZEDBSD_USER_PROGRAMS)),\
	--file /bin/startx=userland/X11/session/startx \
	--file /etc/Xzed/Xzedrc=userland/X11/session/Xzedrc \
	--file /etc/Xzed/zwm.conf=userland/X11/session/zwm.conf \
	--mode /bin/startx=0755 --mode /etc/Xzed/Xzedrc=0755)
ZEDBSD_PACKAGE_INPUTS += $(ZEDBSD_XZED_SESSION_INPUTS)
ZEDBSD_PACKAGE_FILES += $(ZEDBSD_XZED_SESSION_FILES)

# Files a caller wants in this one image without declaring a package, named on
# the command line. It exists so that a test can put a program in an image and
# run it, and is empty in an ordinary build:
#
#   make ZEDBSD_EXTRA_INPUTS=/path/to/prog \
#        ZEDBSD_EXTRA_FILES='--file /usr/bin/prog=/path/to/prog' disk-image
ZEDBSD_PACKAGE_INPUTS += $(ZEDBSD_EXTRA_INPUTS)
ZEDBSD_PACKAGE_FILES += $(ZEDBSD_EXTRA_FILES)

# The rootfs output path is shared by successive menuconfig selections. A
# source file timestamp cannot represent removal of a program or the addition
# of an older cached data-only package, so retain the complete resolved
# selection as a content-stable prerequisite.
ZEDBSD_ROOTFS_CONFIG_STAMP := $(BUILD)/.rootfs-config
ZEDBSD_ARCH_IMAGE_CONFIG_STAMP := \
	$(ARCH_IMAGE_DIR)/.$(ZEDBSD_ARCHITECTURE)-rootfs-config
.PHONY: FORCE_ZEDBSD_ROOTFS_CONFIG
FORCE_ZEDBSD_ROOTFS_CONFIG:

$(ZEDBSD_ROOTFS_CONFIG_STAMP) \
$(ZEDBSD_ARCH_IMAGE_CONFIG_STAMP): FORCE_ZEDBSD_ROOTFS_CONFIG
	@mkdir -p $(dir $@)
	@platform='$(ZEDBSD_PLATFORM)'; \
 architecture='$(ZEDBSD_ARCHITECTURE)'; \
 board='$(ZEDBSD_BOARD)'; \
 programs='$(strip $(ZEDBSD_USER_PROGRAMS))'; \
 data='$(strip $(ZEDBSD_USERLAND_DATA_FILES))'; \
 files='$(strip $(ZEDBSD_PACKAGE_FILES))'; \
 modes='$(strip $(ZEDBSD_USERLAND_FILE_MODES))'; \
 links='$(strip $(ZEDBSD_PACKAGE_LINKS))'; \
 development='$(ZEDBSD_ROOTFS_DEVELOPMENT)'; \
 value="platform=$$platform;architecture=$$architecture;board=$$board;programs=$$programs;data=$$data;files=$$files;modes=$$modes;links=$$links;development=$$development"; \
 if ! test -f $@ || ! grep -Fqx -- "$$value" $@; then \
 printf '%s\n' "$$value" > $@.tmp; \
 mv $@.tmp $@; \
 fi

$(DATA_IMAGE): $(DATA_IMAGE_TOOLS)
	@mkdir -p $(dir $@)
	$(NOCT) --path=$(BUILD_TOOLS_DIR) \
 $(BUILD_TOOLS_DIR)/make-data-image.noct \
 --backend $(abspath $(ZEDBSD_IMAGE_HOST)) --output $@

$(SWAP_IMAGE): $(BUILD_TOOLS_DIR)/make-swapfile.noct
	@mkdir -p $(dir $@)
	$(NOCT) --path=$(BUILD_TOOLS_DIR) $(BUILD_TOOLS_DIR)/make-swapfile.noct --size-mib 64 --output $@

# $(1): output, $(2): profile, $(3): prerequisites, $(4): --file arguments.
define ZEDBSD_ARCH_IMAGE_RULE
$(1): $(ZEDBSD_ARCH_IMAGE_CONFIG_STAMP) $(3) $(ZEDBSD_PACKAGE_INPUTS) \
	$(ARCH_IMAGE_TOOLS)
	@mkdir -p $$(dir $$@)
	$$(PYTHON) $$(BUILD_TOOLS_DIR)/make-arch-overlay-image.py --force \
 --profile $(2) --output $$@ $(4) $(ZEDBSD_PACKAGE_FILES)

$(1)-check: $(1)
	$$(PYTHON) $$(BUILD_TOOLS_DIR)/check-arch-overlay-image.py \
 --profile $(2) --image $$< $(4) $(ZEDBSD_PACKAGE_FILES)
endef

# $(1): output, $(2): profile, $(3): prerequisites, $(4): --file arguments.
define ZEDBSD_ARCH_UFS_IMAGE_RULE
$(1): $(ZEDBSD_ARCH_IMAGE_CONFIG_STAMP) $(3) $(ZEDBSD_PACKAGE_INPUTS) \
	$(ARCH_UFS_IMAGE_TOOLS)
	@mkdir -p $$(dir $$@)
	$$(NOCT) --path=$$(BUILD_TOOLS_DIR) \
 $$(BUILD_TOOLS_DIR)/make-arch-overlay-ufs.noct \
 --backend $$(abspath $$(ZEDBSD_IMAGE_HOST)) --force \
 --profile $(2) --output $$@ $(4) $$(ZEDBSD_PACKAGE_FILES)

$(1)-check: $(1)
	PYTHONPATH=$$(BUILD_TOOLS_DIR) $$(PYTHON) \
 $$(BUILD_TOOLS_DIR)/check-arch-overlay-ufs.py \
 --profile $(2) --image $$< $(4) $(ZEDBSD_PACKAGE_FILES)
endef

# The directories every root carries, with the mode each must have.  A
# directory is made with its mode rather than whatever the builder's file
# creation mask leaves: a group-writable directory is refused by anything
# that moves its root into the tree, because whoever is in that group could
# have put something there.
ZEDBSD_ROOTFS_DIRECTORIES := bin sbin lib etc var root home dev boot run \
	usr/bin usr/sbin usr/libexec var/empty etc/ssh
ZEDBSD_ROOTFS_STICKY_DIRECTORIES := tmp shm

# $(1): profile, $(2): prerequisites, $(3): --file/--mode arguments.
#
# The staged tree is the root.  It is what the UFS image is made from, so
# there is one description of what a root holds instead of two that drift:
# a symbolic link, a directory mode, or anything a package adds to the tree
# reaches the image because the image is that tree.
define ZEDBSD_ROOTFS_TREE_RULE
$(BUILD)/rootfs/.stamp: $(ZEDBSD_ROOTFS_CONFIG_STAMP) $(2) \
	$(ZEDBSD_PACKAGE_INPUTS) $(ZEDBSD_ROOTFS_DEVELOPMENT_INPUTS)
	@rm -rf $(BUILD)/rootfs
	@mkdir -p $(BUILD)/rootfs $(addprefix $(BUILD)/rootfs/,\
 $(ZEDBSD_ROOTFS_DIRECTORIES) $(ZEDBSD_ROOTFS_STICKY_DIRECTORIES))
	@chmod 0755 $(BUILD)/rootfs $(addprefix $(BUILD)/rootfs/,\
 $(ZEDBSD_ROOTFS_DIRECTORIES))
	@chmod 1777 $(addprefix $(BUILD)/rootfs/,\
 $(ZEDBSD_ROOTFS_STICKY_DIRECTORIES))
	@ln -s ../run $(BUILD)/rootfs/var/run
	@printf '%s\n' '$(1)' > $(BUILD)/rootfs/lib/arch.id
	@printf 'zedBSD ufs root v1\n' > $(BUILD)/rootfs/etc/zedbsd-root
	@set -e; for pass in file mode; do \
 set -- $(3) $(ZEDBSD_PACKAGE_FILES); while test $$$$# -gt 0; do \
 option=$$$$1; specification=$$$$2; shift 2; \
 path=$$$${specification%%=*}; value=$$$${specification#*=}; \
 path=$$$${path#/}; destination=$(BUILD)/rootfs/$$$$path; \
 case $$$$option in \
 --file) test "$$$$pass" = file || continue; \
 mkdir -p "$$$${destination%/*}"; cp -f "$$$$value" "$$$$destination" ;; \
 --mode) test "$$$$pass" = mode || continue; \
 test -e "$$$$destination" || { \
 echo "rootfs: --mode names a file nothing installed: /$$$$path" >&2; \
 exit 2; }; \
 chmod "$$$$value" "$$$$destination" ;; \
 *) echo "unknown rootfs option: $$$$option" >&2; exit 2 ;; \
 esac; \
 done; \
	done
	@set -e; for specification in $(ZEDBSD_PACKAGE_LINKS); do \
 path=$$$${specification%%=*}; target=$$$${specification#*=}; \
 path=$$$${path#/}; destination=$(BUILD)/rootfs/$$$$path; \
 mkdir -p "$$$${destination%/*}"; ln -sfn "$$$$target" "$$$$destination"; \
 done
	@$$(call ZEDBSD_ROOTFS_INSTALL_DEVELOPMENT,$(BUILD)/rootfs)
	@touch $$@
endef

# Symbolic links a package puts in the root, as DEST=TARGET with TARGET taken
# as written (usually relative, such as a library's SONAME).  Only the root
# tree reads them; a library's file itself is installed under its SONAME with
# --file, so the loader finds it without following a link.
ZEDBSD_PACKAGE_LINKS ?=

# The files a program is built from on the target itself: the C library
# headers and the link-time objects, and what packages add for the same
# purpose (headers in /usr/include, pkg-config files, the unversioned .so
# link a linker looks for, static archives).  They are what makes the running
# system able to compile, so they are installed by default; an embedded root
# that will never host a compiler sets ZEDBSD_ROOTFS_DEVELOPMENT to n (the
# build menu's "Install development files"), which removes them from the
# tree after the packages are in.  A library itself is installed under its
# SONAME as a regular file, so removing the .so links leaves the loader's
# names intact.
ZEDBSD_ROOTFS_DEVELOPMENT ?= y
# A target without a sysroot (arm64 for now) has no development files.
ifeq ($(strip $(ZEDBSD_TARGET_SYSROOT)),)
override ZEDBSD_ROOTFS_DEVELOPMENT := n
endif
ifeq ($(ZEDBSD_ROOTFS_DEVELOPMENT),y)
ZEDBSD_ROOTFS_DEVELOPMENT_INPUTS := \
	$(ZEDBSD_TARGET_SYSROOT)/.zedbsd-sysroot-complete
define ZEDBSD_ROOTFS_INSTALL_DEVELOPMENT
	mkdir -p $(1)/usr/include $(1)/usr/lib
	cp -R $(ZEDBSD_TARGET_SYSROOT)/usr/include/. $(1)/usr/include/
	cp -R $(ZEDBSD_TARGET_SYSROOT)/usr/lib/. $(1)/usr/lib/
	chmod -R u+w $(1)/usr/include $(1)/usr/lib
endef
else
ZEDBSD_ROOTFS_DEVELOPMENT_INPUTS :=
define ZEDBSD_ROOTFS_INSTALL_DEVELOPMENT
	rm -rf $(1)/usr/include $(1)/usr/lib/pkgconfig $(1)/usr/share/pkgconfig
	find $(1)/lib -maxdepth 1 \
		\( \( -type l -name '*.so' \) -o \( -type f -name '*.a' \) \) \
		-exec rm -f {} +
	test ! -d $(1)/usr/lib || find $(1)/usr/lib -maxdepth 1 \
		\( \( -type l -name '*.so' \) -o \( -type f -name '*.a' \) \) \
		-exec rm -f {} +
endef
endif

# $(1): output, $(2): profile.  The root is the staged tree.
define ZEDBSD_ROOTFS_UFS_IMAGE_RULE
$(1): $(BUILD)/rootfs/.stamp $(ARCH_UFS_IMAGE_TOOLS)
	@mkdir -p $$(dir $$@)
	$$(NOCT) --path=$$(BUILD_TOOLS_DIR) \
 $$(BUILD_TOOLS_DIR)/make-arch-overlay-ufs.noct \
 --backend $$(abspath $$(ZEDBSD_IMAGE_HOST)) --force \
 --profile $(2) --output $$@ --tree $(BUILD)/rootfs
endef

ifneq ($(strip $(ZEDBSD_PLATFORM)),)
include $(PLATFORM_MAKEFILE)
endif

ifneq ($(strip $(ZEDBSD_TARGET_TRIPLE)),)
# The kernel needs the target tools only: it reads no C library header, so
# vmunix does not wait for the sysroot.  Everything built for user space does.
.PHONY: zedbsd-target-tools-ready zedbsd-target-toolchain-ready
zedbsd-target-tools-ready:
	@for tool in clang ld.lld lld-link llvm-ar llvm-ranlib llvm-nm llvm-objcopy \
 llvm-objdump llvm-readelf llvm-strip; do \
 test -x "$(ZEDBSD_TARGET_LLVM_BIN)/$$tool" || { \
 echo "Missing project target tool: $(ZEDBSD_TARGET_LLVM_BIN)/$$tool" >&2; \
 echo "Run 'make toolchain-cache' first on x86_64 Linux, then run 'make toolchain'." >&2; \
 echo "Alternatively run 'make toolchain' alone to build LLVM from source." >&2; \
 exit 1; \
 }; \
	done

zedbsd-target-toolchain-ready: zedbsd-target-tools-ready
	@test -f "$(ZEDBSD_TARGET_SYSROOT)/.zedbsd-sysroot-complete" || { \
 echo "Missing target sysroot: $(ZEDBSD_TARGET_SYSROOT)" >&2; \
 echo "Run 'make toolchain' before building a target image." >&2; \
 exit 1; \
	}

vmunix: | zedbsd-target-tools-ready
rootfs world disk-image run: | zedbsd-target-toolchain-ready
endif

.PHONY: vmunix rootfs world
world: vmunix rootfs

clean:
	rm -rf $(BUILD)

# The Noct trees are extracted, one of them outside build/, so they are removed by name.
distclean: noct-clean
	rm -rf build

ifneq ($(strip $(ZEDBSD_PLATFORM)),)
-include $(filter-out $(BUILD)/rootfs/%,$(wildcard $(BUILD)/*.d \
	$(BUILD)/*/*.d $(BUILD)/*/*/*.d $(BUILD)/*/*/*/*.d \
	$(BUILD)/*/*/*/*/*.d $(BUILD)/*/*/*/*/*/*.d \
	$(BUILD)/*/*/*/*/*/*/*.d \
	$(BUILD)/*/*/*/*/*/*/*/*.d))
endif

.PHONY: clean distclean
