# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,mkfs,mkfs,*,y,basic,userland/base/mkfs/main.c userland/base/mkfs/ufs-format.c userland/base/common/format-file.c src/drivers/fs/ufs/ufs-super.c src/drivers/fs/ufs/ufs-endian.c,y,base,,,0755,program,,,sbin))
