# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,mkfs,mkfs,*,y,basic,userland/base/mkfs/main.c userland/base/mkfs/ufs-format.c userland/base/mkfs/fat32-format.c userland/base/mkfs/block-command.c userland/base/common/format-file.c userland/base/mkfs/ufs-super.c userland/base/mkfs/ufs-endian.c,y,base,,,0755,program,,,sbin))
