#!/usr/bin/env python3
"""Compiles zdesktop-terminal's shaders and writes userland/base/zdesktop-terminal/shaders.h.

The build uses the checked-in header, so no shader compiler is needed to
build
zdesktop-terminal; run this (with glslc and spirv-val on PATH) after changing a
shader.
Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
"""
import pathlib
import struct
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
SHADERS = [("cell.vert", "terminal_cell_vert"), ("cell.frag", "terminal_cell_frag")]


def compile_shader(source):
    """Returns the validated SPIR-V words of one shader."""
    with tempfile.TemporaryDirectory() as directory:
        output = pathlib.Path(directory) / "shader.spv"
        subprocess.run(["glslc", "--target-env=vulkan1.0", "-O", str(source),
                        "-o", str(output)], check=True, timeout=30)
        subprocess.run(["spirv-val", "--target-env", "vulkan1.0",
                        str(output)], check=True, timeout=30)
        data = output.read_bytes()
    return struct.unpack("<%dI" % (len(data) // 4), data)


def main():
    lines = ["/*", " * zedBSD", " * Copyright (C) 2026 Awe Morris", " *",
             " * SPDX-License-Identifier: Zlib", " */", "",
             "/* Generated by shaders/regenerate.py from the shaders in shaders/; do not edit. */",
             "", "#ifndef ZDESKTOP_TERMINAL_SHADERS_H", "#define ZDESKTOP_TERMINAL_SHADERS_H", "",
             "#include <stdint.h>", ""]
    for source, name in SHADERS:
        words = compile_shader(HERE / source)
        lines.append("static const uint32_t %s[] = {" % name)
        for index in range(0, len(words), 6):
            chunk = ", ".join("0x%08xU" % word for word in words[index:index + 6])
            lines.append("\t%s," % chunk)
        lines.append("};")
        lines.append("")
    lines.append("#endif")
    (HERE.parent / "shaders.h").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
