/* -*- coding: utf-8; tab-width: 8; indent-tabs-mode: t; -*- */

/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * One maintained mapping for getconf names and their defining interfaces.
 */

GETCONF_SYSCONF("ARG_MAX", _SC_ARG_MAX)
GETCONF_SYSCONF("CHILD_MAX", _SC_CHILD_MAX)
GETCONF_SYSCONF("CLK_TCK", _SC_CLK_TCK)
GETCONF_SYSCONF("OPEN_MAX", _SC_OPEN_MAX)
GETCONF_SYSCONF("PAGE_SIZE", _SC_PAGE_SIZE)
GETCONF_SYSCONF("PAGESIZE", _SC_PAGESIZE)
GETCONF_SYSCONF("STREAM_MAX", _SC_STREAM_MAX)
GETCONF_SYSCONF("NPROCESSORS_CONF", _SC_NPROCESSORS_CONF)
GETCONF_SYSCONF("NPROCESSORS_ONLN", _SC_NPROCESSORS_ONLN)
GETCONF_SYSCONF("_POSIX_JOB_CONTROL", _SC_JOB_CONTROL)
GETCONF_SYSCONF("_POSIX_MESSAGE_PASSING", _SC_MESSAGE_PASSING)
GETCONF_SYSCONF("_POSIX_REALTIME_SIGNALS", _SC_REALTIME_SIGNALS)
GETCONF_SYSCONF("_POSIX_SEMAPHORES", _SC_SEMAPHORES)
GETCONF_SYSCONF("_POSIX_SHARED_MEMORY_OBJECTS", _SC_SHARED_MEMORY_OBJECTS)
GETCONF_SYSCONF("_POSIX_THREADS", _SC_THREADS)
GETCONF_SYSCONF("_POSIX_THREAD_PROCESS_SHARED", _SC_THREAD_PROCESS_SHARED)
GETCONF_SYSCONF("_POSIX_TIMERS", _SC_TIMERS)
GETCONF_SYSCONF("_POSIX_VERSION", _SC_VERSION)
GETCONF_SYSCONF("POSIX2_VERSION", _SC_2_VERSION)
GETCONF_SYSCONF("_POSIX2_VERSION", _SC_2_VERSION)
GETCONF_SYSCONF("_XOPEN_UNIX", _SC_XOPEN_UNIX)
GETCONF_SYSCONF("_XOPEN_VERSION", _SC_XOPEN_VERSION)
GETCONF_SYSCONF("MQ_OPEN_MAX", _SC_MQ_OPEN_MAX)
GETCONF_SYSCONF("MQ_PRIO_MAX", _SC_MQ_PRIO_MAX)
GETCONF_SYSCONF("RTSIG_MAX", _SC_RTSIG_MAX)
GETCONF_SYSCONF("SEM_NSEMS_MAX", _SC_SEM_NSEMS_MAX)
GETCONF_SYSCONF("SEM_VALUE_MAX", _SC_SEM_VALUE_MAX)
GETCONF_SYSCONF("SIGQUEUE_MAX", _SC_SIGQUEUE_MAX)
GETCONF_SYSCONF("PTHREAD_DESTRUCTOR_ITERATIONS",
		_SC_THREAD_DESTRUCTOR_ITERATIONS)
GETCONF_SYSCONF("PTHREAD_KEYS_MAX", _SC_THREAD_KEYS_MAX)
GETCONF_SYSCONF("PTHREAD_STACK_MIN", _SC_THREAD_STACK_MIN)
GETCONF_SYSCONF("PTHREAD_THREADS_MAX", _SC_THREAD_THREADS_MAX)

GETCONF_PATHCONF("LINK_MAX", _PC_LINK_MAX)
GETCONF_PATHCONF("MAX_CANON", _PC_MAX_CANON)
GETCONF_PATHCONF("MAX_INPUT", _PC_MAX_INPUT)
GETCONF_PATHCONF("NAME_MAX", _PC_NAME_MAX)
GETCONF_PATHCONF("PATH_MAX", _PC_PATH_MAX)
GETCONF_PATHCONF("PIPE_BUF", _PC_PIPE_BUF)
GETCONF_PATHCONF("_POSIX_CHOWN_RESTRICTED", _PC_CHOWN_RESTRICTED)
GETCONF_PATHCONF("_POSIX_NO_TRUNC", _PC_NO_TRUNC)
GETCONF_PATHCONF("_POSIX_VDISABLE", _PC_VDISABLE)
#ifndef GETCONF_NO_TEXTDOMAIN
GETCONF_PATHCONF("TEXTDOMAIN_MAX", _PC_TEXTDOMAIN_MAX)
#endif

GETCONF_CONFSTR("PATH", _CS_PATH)
GETCONF_CONFSTR("CS_PATH", _CS_PATH)

GETCONF_CONSTANT("BC_BASE_MAX", BC_BASE_MAX)
GETCONF_CONSTANT("BC_DIM_MAX", BC_DIM_MAX)
GETCONF_CONSTANT("BC_SCALE_MAX", BC_SCALE_MAX)
GETCONF_CONSTANT("BC_STRING_MAX", BC_STRING_MAX)
GETCONF_CONSTANT("CHARCLASS_NAME_MAX", CHARCLASS_NAME_MAX)
GETCONF_CONSTANT("COLL_WEIGHTS_MAX", COLL_WEIGHTS_MAX)
GETCONF_CONSTANT("EXPR_NEST_MAX", EXPR_NEST_MAX)
GETCONF_CONSTANT("LINE_MAX", LINE_MAX)
GETCONF_CONSTANT("POSIX2_BC_BASE_MAX", BC_BASE_MAX)
GETCONF_CONSTANT("POSIX2_BC_DIM_MAX", BC_DIM_MAX)
GETCONF_CONSTANT("POSIX2_BC_SCALE_MAX", BC_SCALE_MAX)
GETCONF_CONSTANT("POSIX2_BC_STRING_MAX", BC_STRING_MAX)
GETCONF_CONSTANT("POSIX2_COLL_WEIGHTS_MAX", COLL_WEIGHTS_MAX)
GETCONF_CONSTANT("POSIX2_EXPR_NEST_MAX", EXPR_NEST_MAX)
GETCONF_CONSTANT("POSIX2_LINE_MAX", LINE_MAX)
GETCONF_CONSTANT("POSIX2_RE_DUP_MAX", RE_DUP_MAX)
GETCONF_CONSTANT("RE_DUP_MAX", RE_DUP_MAX)

GETCONF_TEXT("POSIX_V7_WIDTH_RESTRICTED_ENVS", GETCONF_MODEL_V7)
GETCONF_TEXT("POSIX_V8_WIDTH_RESTRICTED_ENVS", GETCONF_MODEL_V8)
GETCONF_TEXT("POSIX_V7_ILP32_OFF32_CFLAGS", GETCONF_ILP32_CFLAGS)
GETCONF_TEXT("POSIX_V7_ILP32_OFF32_LDFLAGS", GETCONF_ILP32_LDFLAGS)
GETCONF_TEXT("POSIX_V7_ILP32_OFF32_LIBS", "")
GETCONF_TEXT("POSIX_V7_LP64_OFF64_CFLAGS", GETCONF_LP64_CFLAGS)
GETCONF_TEXT("POSIX_V7_LP64_OFF64_LDFLAGS", GETCONF_LP64_LDFLAGS)
GETCONF_TEXT("POSIX_V7_LP64_OFF64_LIBS", "")
GETCONF_TEXT("POSIX_V8_ILP32_OFF32_CFLAGS", GETCONF_ILP32_CFLAGS)
GETCONF_TEXT("POSIX_V8_ILP32_OFF32_LDFLAGS", GETCONF_ILP32_LDFLAGS)
GETCONF_TEXT("POSIX_V8_ILP32_OFF32_LIBS", "")
GETCONF_TEXT("POSIX_V8_LP64_OFF64_CFLAGS", GETCONF_LP64_CFLAGS)
GETCONF_TEXT("POSIX_V8_LP64_OFF64_LDFLAGS", GETCONF_LP64_LDFLAGS)
GETCONF_TEXT("POSIX_V8_LP64_OFF64_LIBS", "")
GETCONF_TEXT("POSIX_V7_THREADS_CFLAGS", "-pthread")
GETCONF_TEXT("POSIX_V7_THREADS_LDFLAGS", "-pthread")
GETCONF_TEXT("POSIX_V7_THREADS_LIBS", "")
GETCONF_TEXT("POSIX_V8_THREADS_CFLAGS", "-pthread")
GETCONF_TEXT("POSIX_V8_THREADS_LDFLAGS", "-pthread")
GETCONF_TEXT("POSIX_V8_THREADS_LIBS", "")
