include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,getconf,getconf,*,y,basic,userland/base/getconf/main.c,y,base,,))
