include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,pax,pax,*,y,basic,userland/base/pax/main.c,y,base,,))
