# Focused ws004-p021 amd64/UEFI xHCI build selection.
ZEDBSD_MENU_VERSION := 3
ZEDBSD_PLATFORM := amd64
ZEDBSD_ARCHITECTURE := amd64
ZEDBSD_BOARD := pcat
ZEDBSD_VARIANT := uefi

CONFIG_KERNEL_TEST_CHECKPOINTS := n
CONFIG_BUF_CACHE_KIB := 0
CONFIG_DRIVER_NE2000 := y
CONFIG_DRIVER_PCI_UHCI := y
CONFIG_DRIVER_PCI_EHCI := y
CONFIG_DRIVER_PCI_XHCI := y
CONFIG_DRIVER_PCI_NVME := y
CONFIG_DRIVER_USB_STORAGE := y
CONFIG_DRIVER_USB_CDC_NCM := y
CONFIG_DRIVER_GRAPHICS := y
CONFIG_DRIVER_LGY98 := n

ZEDBSD_USER_PROGRAMS :=
