# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,mkswap,mkswap,*,y,basic,userland/base/mkswap/main.c userland/base/mkswap/swap-format.c userland/base/common/format-file.c src/kern/swap-format.c,y,base,,,0755,program,,,sbin))
