include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,ar,ar,*,y,basic,userland/base/ar/main.c userland/base/common/archive.c userland/base/common/elf_symbols.c,y,base,,))
