/* -*- mode: c; c-file-style: "linux"; tab-width: 8; -*- */

/* Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib */
#ifndef ZEDBSD_UAPI_IO_STATS_H
#define ZEDBSD_UAPI_IO_STATS_H

#include <stdint.h>

#define IO_STATS_VERSION 8U

/* Append events; never renumber an existing entry. All sizes are bytes. */
enum io_stat_event {
	IO_FILE_READ,
	IO_FILE_WRITE,
	IO_BUF_READ,
	IO_BUF_WRITE,
	IO_DRIVER_READ,
	IO_DRIVER_WRITE,
	IO_DRIVER_FLUSH,
	IO_COMPLETE_READ,
	IO_COMPLETE_WRITE,
	IO_COMPLETE_FLUSH,
	IO_COMPLETE_ERROR,
	IO_LOOP_READ,
	IO_LOOP_WRITE,
	IO_LOOP_FLUSH,
	IO_USB_READ10,
	IO_USB_WRITE10,
	IO_USB_SYNC_CACHE,
	IO_USB_OTHER,
	IO_DMA_ALLOC,
	IO_DMA_FREE,
	IO_UFS1_READ,
	IO_UFS1_WRITE,
	IO_UFS1_CONTENT_READ,
	IO_UFS1_CONTENT_WRITE,
	IO_UFS2_READ,
	IO_UFS2_WRITE,
	IO_UFS2_CONTENT_READ,
	IO_UFS2_CONTENT_WRITE,
	IO_XHCI_QUARANTINE,
	IO_DMA_REQUEST,
	IO_USB_BUFFER_ALLOC,
	IO_USB_BUFFER_FREE,
	IO_USB_BUFFER_RETAINED,
	IO_SYSCALL_READ,
	IO_SYSCALL_WRITE,
	IO_POOL_BACKING_ALLOC,
	IO_POOL_LARGE_BORROW,
	IO_POOL_SMALL_BORROW,
	IO_POOL_FALLBACK,
	IO_POOL_RETURN,
	IO_BUF_RUN_READ,
	IO_BUF_RUN_WRITE,
	IO_BUF_SINGLE_GEOMETRY,
	IO_BUF_SINGLE_MEMORY,
	IO_BUF_SINGLE_BUSY,
	IO_BUF_SINGLE_HIT,
	IO_USB_TRANSFER_RESERVE_ALLOC,
	IO_USB_TRANSFER_RESERVE_FREE,
	IO_XHCI_REQUEST_ALLOC,
	IO_UFS_CG_HIT,
	IO_UFS_CG_MISS,
	IO_UFS_INDIRECT_WINDOW,
	IO_UFS_ALLOC_BEGIN,
	IO_UFS_ALLOCATE,
	IO_UFS_ALLOC_COMMIT,
	IO_UFS_ALLOC_ABORT,
	IO_FAT_SECTOR_HIT,
	IO_FAT_SECTOR_MISS,
	IO_FAT_CHAIN_STEP,
	IO_FAT_CHAIN_INVALIDATE,
	IO_FAT_CURSOR_HIT,
	IO_UFS_READ,
	IO_UFS_WRITE,
	IO_UFS_CONTENT_READ,
	IO_UFS_CONTENT_WRITE,
	IO_USB_STAGING_COPY,
	IO_XHCI_BOUNCE_COPY,
	IO_XHCI_SHARED_STAGING,
	IO_XHCI_SG_TD,
	IO_XHCI_DATA_TRB,
	IO_DISK_VECTOR_BATCH,
	IO_DISK_VECTOR_SPLIT,
	IO_STAT_COUNT
};

struct io_stat_value {
	uint64_t calls;
	uint64_t bytes;
};

/* Each field is atomic; a live snapshot is not a transaction across fields. */
struct io_stats {
	uint32_t version;
	uint32_t count;
	struct io_stat_value events[IO_STAT_COUNT];
};

#endif
