/*
 * syscall
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

#ifndef ZEDBSD_UAPI_SYSCALL_H
#define ZEDBSD_UAPI_SYSCALL_H

enum zedbsd_syscall_number {
	ZEDBSD_SYS_exit = 1,
	ZEDBSD_SYS_open = 2,
	ZEDBSD_SYS_close = 3,
	ZEDBSD_SYS_read = 4,
	ZEDBSD_SYS_write = 5,
	ZEDBSD_SYS_lseek = 6,
	ZEDBSD_SYS_fstat = 7,
	ZEDBSD_SYS_getdents = 8,
	ZEDBSD_SYS_chdir = 9,
	ZEDBSD_SYS_getcwd = 10,
	ZEDBSD_SYS_mmap = 11,
	ZEDBSD_SYS_munmap = 12,
	ZEDBSD_SYS_mprotect = 13,
	ZEDBSD_SYS_ioctl = 14,
	ZEDBSD_SYS_clock_gettime = 15,
	ZEDBSD_SYS_nanosleep = 16,
	ZEDBSD_SYS_spawn = 17,
	ZEDBSD_SYS_wait = 18,
	ZEDBSD_SYS_brk = 19,
	ZEDBSD_SYS_socket = 20,
	ZEDBSD_SYS_bind = 21,
	ZEDBSD_SYS_connect = 22,
	ZEDBSD_SYS_listen = 23,
	ZEDBSD_SYS_accept = 24,
	ZEDBSD_SYS_sendto = 25,
	ZEDBSD_SYS_recvfrom = 26,
	ZEDBSD_SYS_shutdown = 27,
	ZEDBSD_SYS_getsockname = 28,
	ZEDBSD_SYS_getpeername = 29,
	ZEDBSD_SYS_setsockopt = 30,
	ZEDBSD_SYS_getsockopt = 31,
	ZEDBSD_SYS_fork = 32,
	ZEDBSD_SYS_execve = 33,
	ZEDBSD_SYS_waitpid = 34,
	ZEDBSD_SYS_getpid = 35,
	ZEDBSD_SYS_getppid = 36,
	ZEDBSD_SYS_getpgrp = 37,
	ZEDBSD_SYS_getpgid = 38,
	ZEDBSD_SYS_setpgid = 39,
	ZEDBSD_SYS_setsid = 40,
	ZEDBSD_SYS_getsid = 41,
	ZEDBSD_SYS_dup = 42,
	ZEDBSD_SYS_dup2 = 43,
	ZEDBSD_SYS_dup3 = 44,
	ZEDBSD_SYS_fcntl = 45,
	ZEDBSD_SYS_pipe = 46,
	ZEDBSD_SYS_pipe2 = 47,
	ZEDBSD_SYS_pread = 48,
	ZEDBSD_SYS_pwrite = 49,
	ZEDBSD_SYS_readv = 50,
	ZEDBSD_SYS_writev = 51,
	ZEDBSD_SYS_fsync = 52,
	ZEDBSD_SYS_fdatasync = 53,
	ZEDBSD_SYS_stat = 54,
	ZEDBSD_SYS_lstat = 55,
	ZEDBSD_SYS_truncate = 56,
	ZEDBSD_SYS_ftruncate = 57,
	ZEDBSD_SYS_mkdir = 58,
	ZEDBSD_SYS_unlink = 59,
	ZEDBSD_SYS_rmdir = 60,
	ZEDBSD_SYS_rename = 61,
	ZEDBSD_SYS_umask = 62,
	ZEDBSD_SYS_getuid = 63,
	ZEDBSD_SYS_geteuid = 64,
	ZEDBSD_SYS_getgid = 65,
	ZEDBSD_SYS_getegid = 66,
	ZEDBSD_SYS_getgroups = 67,
	ZEDBSD_SYS_setuid = 68,
	ZEDBSD_SYS_seteuid = 69,
	ZEDBSD_SYS_setgid = 70,
	ZEDBSD_SYS_setegid = 71,
	ZEDBSD_SYS_setgroups = 72,
	ZEDBSD_SYS_setreuid = 73,
	ZEDBSD_SYS_setregid = 74,
	ZEDBSD_SYS_access = 75,
	ZEDBSD_SYS_sigaction = 76,
	ZEDBSD_SYS_sigprocmask = 77,
	ZEDBSD_SYS_sigpending = 78,
	ZEDBSD_SYS_kill = 79,
	ZEDBSD_SYS_sigreturn = 80,
	ZEDBSD_SYS_msync = 81,
	ZEDBSD_SYS_openat = 82,
	ZEDBSD_SYS_fstatat = 83,
	ZEDBSD_SYS_mkdirat = 84,
	ZEDBSD_SYS_unlinkat = 85,
	ZEDBSD_SYS_renameat = 86,
	ZEDBSD_SYS_chmod = 87,
	ZEDBSD_SYS_fchmod = 88,
	ZEDBSD_SYS_fchmodat = 89,
	ZEDBSD_SYS_chown = 90,
	ZEDBSD_SYS_fchown = 91,
	ZEDBSD_SYS_lchown = 92,
	ZEDBSD_SYS_fchownat = 93,
	ZEDBSD_SYS_utimensat = 94,
	ZEDBSD_SYS_futimens = 95,
	ZEDBSD_SYS_faccessat = 96,
	ZEDBSD_SYS_linkat = 97,
	ZEDBSD_SYS_symlinkat = 98,
	ZEDBSD_SYS_readlinkat = 99,
	ZEDBSD_SYS_sigsuspend = 100,
	ZEDBSD_SYS_clock_getres = 101,
	ZEDBSD_SYS_clock_settime = 102,
	ZEDBSD_SYS_sysctl = 103,
};

#endif
