/* zedBSD build configuration for the vendored bc engine.
 * SPDX-License-Identifier: Zlib */
#ifndef ZEDBSD_BC_CONFIG_H
#define ZEDBSD_BC_CONFIG_H

#define VERSION 7.1.0
#define BC_ENABLED 1
#define DC_ENABLED 0
#define BUILD_TYPE HN
#define EXECPREFIX
#define MAINEXEC bc
#define BC_NUM_KARATSUBA_LEN 32
#define BC_ENABLE_NLS 0
#define BC_ENABLE_EXTRA_MATH 1
#define BC_ENABLE_HISTORY 0
#define BC_ENABLE_LIBRARY 0
#define BC_ENABLE_MEMCHECK 0
#define BC_ENABLE_AFL 0
#define BC_ENABLE_OSSFUZZ 0
#define BC_ENABLE_EDITLINE 0
#define BC_ENABLE_READLINE 0
#define BC_DEFAULT_BANNER 0
#define BC_DEFAULT_SIGINT_RESET 1
#define BC_DEFAULT_TTY_MODE 1
#define BC_DEFAULT_PROMPT 1
#define BC_DEFAULT_EXPR_EXIT 1
#define BC_DEFAULT_DIGIT_CLAMP 0
#define DC_DEFAULT_SIGINT_RESET 1
#define DC_DEFAULT_TTY_MODE 0
#define DC_DEFAULT_PROMPT 0
#define DC_DEFAULT_EXPR_EXIT 1
#define DC_DEFAULT_DIGIT_CLAMP 0

#endif
