# zedBSD
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,wakebench,wake-to-run latency benchmark,*,y,basic,userland/base/tests/wakebench/main.c,y,base,base/tests/wakebench,,0755,program,,,bin))
