#include <hal/hal.h>
#include "defs.h"
#include "task.h"

static struct sparcv9_task*tasks,*running;static uint32 task_count;static size_t stack_bytes;
uintptr_t sparcv9_current_trap_sp;
struct sparcv9_window_context *sparcv9_current_user_windows;
static void add(struct sparcv9_task*t){struct sparcv9_task**p=&tasks;while(*p)p=&(*p)->next;*p=t;t->next=NULL;task_count++;}
static void remove_task(struct sparcv9_task*t){struct sparcv9_task**p=&tasks;while(*p&&*p!=t)p=&(*p)->next;if(*p){*p=t->next;if(task_count)task_count--;}}
void hal_task_init(void){struct sparcv9_task*t;if(running)HAL_FATAL("hal_task_init twice");t=hal_malloc(sizeof(*t));if(!t)HAL_FATAL("initial SPARC V9 task allocation failed");hal_memset(t,0,sizeof(*t));t->space=HAL_SPACE_SYS;t->run_cpu=0;add(t);running=t;}
static void build(struct sparcv9_task*t,void(*start)(void*),void*arg,void*user_sp){uintptr_t top=((uintptr_t)t->stack+SPARCV9_SYS_STACK_SIZE)&~15UL;uintptr_t sp=top-SPARCV9_STACK_BIAS-SPARCV9_STACK_FRAME_SIZE;struct sparcv9_window_context*c=&t->windows;hal_memset(c,0,sizeof(*c));c->cwp=0;c->cansave=6;c->cleanwin=7;c->window[0][0]=(uintptr_t)start;c->window[0][1]=t->space==HAL_SPACE_SYS?(uintptr_t)arg:(uintptr_t)user_sp;/* CWP+1 inputs overlap the initial window's outputs. */c->window[1][14]=sp;c->window[1][15]=(uintptr_t)(t->space==HAL_SPACE_SYS?sparcv9_kernel_task_entry:sparcv9_user_task_entry)-8U;t->trap_sp=top-SPARCV9_STACK_BIAS;}
hal_task_t hal_task_create(hal_space_t s,void(*start)(void*),void*arg,void*usp){struct sparcv9_task*t;if(!start||((s==HAL_SPACE_SYS)!=(usp==NULL)))return NULL;t=hal_malloc(sizeof(*t));if(!t)return NULL;hal_memset(t,0,sizeof(*t));t->stack_allocation=hal_malloc(SPARCV9_SYS_STACK_SIZE+15U);if(!t->stack_allocation){hal_free(t);return NULL;}t->stack=(void*)(((uintptr_t)t->stack_allocation+15U)&~15UL);t->space=s;t->run_cpu=-1;build(t,start,arg,usp);stack_bytes+=SPARCV9_SYS_STACK_SIZE;add(t);return t;}
void hal_task_destroy(hal_task_t h){struct sparcv9_task*t=h;if(!t)return;if(t==running)HAL_FATAL("destroy current SPARC V9 task");remove_task(t);if(t->stack){stack_bytes-=SPARCV9_SYS_STACK_SIZE;hal_free(t->stack_allocation);}hal_free(t);}
static void save_trap_state(struct sparcv9_task*t){__asm__ volatile("rdpr %%tl,%0":"=r"(t->trap_level));if(t->trap_level>1)HAL_FATAL("SPARC V9 task switch above TL1");if(t->trap_level){__asm__ volatile("rdpr %%tpc,%0":"=r"(t->trap_pc));__asm__ volatile("rdpr %%tnpc,%0":"=r"(t->trap_next_pc));__asm__ volatile("rdpr %%tstate,%0":"=r"(t->trap_state));__asm__ volatile("rdpr %%tt,%0":"=r"(t->trap_type));}}
static void restore_trap_state(const struct sparcv9_task*t){__asm__ volatile("wrpr %0,0,%%tl"::"r"(t->trap_level):"memory");if(t->trap_level){__asm__ volatile("wrpr %0,0,%%tpc"::"r"(t->trap_pc));__asm__ volatile("wrpr %0,0,%%tnpc"::"r"(t->trap_next_pc));__asm__ volatile("wrpr %0,0,%%tstate"::"r"(t->trap_state));__asm__ volatile("wrpr %0,0,%%tt"::"r"(t->trap_type));}}
void hal_task_context_switch(hal_task_t h){struct sparcv9_task*to=h,*from=running;if(!to||!from)HAL_FATAL("invalid SPARC V9 task switch");if(to==from)return;if(to->run_cpu>=0)HAL_FATAL("SPARC V9 HAL task already running");from->run_cpu=-1;to->run_cpu=0;save_trap_state(from);running=to;sparcv9_current_trap_sp=to->trap_sp;sparcv9_current_user_windows=&to->trap_windows;hal_page_switch_space(to->space);restore_trap_state(to);sparcv9_task_dispatch(&from->windows,&to->windows);}
void sparcv9_task_returned(void){HAL_FATAL("SPARC V9 task returned");for(;;)__asm__ volatile("nop");}
hal_task_t hal_task_get_current(void){return running;}
void hal_task_set_tls(hal_task_t h,uintptr_t v){struct sparcv9_task*t=h;if(t){t->tls=v;t->windows.global[7]=v;if(t==running)sparcv9_tls_write(v);}}
uintptr_t hal_task_get_tls(hal_task_t h){if(h==running)return sparcv9_tls_read();return h?((struct sparcv9_task*)h)->tls:0;}
void hal_task_set_private(hal_task_t h,void*p){if(h)((struct sparcv9_task*)h)->private_data=p;}
void *hal_task_get_private(hal_task_t h){return h?((struct sparcv9_task*)h)->private_data:NULL;}
hal_space_t hal_task_get_space(hal_task_t h){return h?((struct sparcv9_task*)h)->space:HAL_SPACE_SYS;}
int hal_task_transfer(hal_task_t h,hal_cpu_id_t cpu){struct sparcv9_task*t=h;if(!t||cpu!=0)return HAL_ERR_INVALID;if(t->run_cpu>=0)return HAL_ERR_BUSY;return HAL_OK;}

void sparcv9_task_enter_user_frame(struct sparcv9_user_trap_frame*f,
	uintptr_t pc,uintptr_t npc,uint64 tstate,uint64 type){if(running){running->active_user_frame=f;running->active_pc=pc;running->active_next_pc=npc;running->active_tstate=tstate;running->active_trap_type=type;}}
void sparcv9_task_leave_user_frame(void){if(running)running->active_user_frame=NULL;}
static void set_user_trap(uintptr_t pc,uintptr_t npc,uint64 state){__asm__ volatile("wrpr %0,0,%%tpc\n\twrpr %1,0,%%tnpc\n\twrpr %2,0,%%tstate"::"r"(pc),"r"(npc),"r"(state):"memory");}
static unsigned user_output_window(const struct sparcv9_window_context*c){return(unsigned)((c->cwp+1U)&(SPARCV9_NWINDOWS-1U));}
hal_task_t hal_task_fork_current(hal_space_t s,intptr_t r){struct sparcv9_task*t;unsigned w;if(!running||s==HAL_SPACE_SYS||!running->active_user_frame)return NULL;t=hal_task_create(s,(void(*)(void*))(uintptr_t)running->active_next_pc,NULL,(void*)(running->active_user_frame->old_sp+SPARCV9_STACK_BIAS));if(!t)return NULL;t->trap_windows=running->trap_windows;w=user_output_window(&t->trap_windows);t->trap_windows.window[w][8]=(uint64)r;t->tls=sparcv9_tls_read();t->trap_windows.global[7]=t->tls;t->trap_level=1;t->trap_pc=running->active_pc;t->trap_next_pc=running->active_next_pc;t->trap_state=running->active_tstate;t->trap_type=running->active_trap_type;t->windows.window[1][15]=(uintptr_t)sparcv9_user_fork_entry-8U;return t;}
int hal_task_exec_current(hal_space_t s,uintptr_t e,uintptr_t sp){struct sparcv9_user_trap_frame*f;uint64 state;if(!running||s==HAL_SPACE_SYS||(f=running->active_user_frame)==NULL||!e||!sp||sp<SPARCV9_STACK_BIAS)return-1;state=running->active_tstate&~0x1fULL;hal_memset(&running->trap_windows,0,sizeof(running->trap_windows));running->trap_windows.cansave=6;running->trap_windows.cleanwin=7;running->trap_windows.window[1][14]=sp-SPARCV9_STACK_BIAS;hal_memset(f,0,sizeof(*f));f->old_sp=sp-SPARCV9_STACK_BIAS;running->space=s;running->tls=0;running->signal_depth=0;running->active_pc=e-4U;running->active_next_pc=e;running->active_tstate=state;hal_page_switch_space(s);set_user_trap(e-4U,e,state);return 0;}
uintptr_t hal_task_user_stack(void){return running&&running->active_user_frame?running->active_user_frame->old_sp+SPARCV9_STACK_BIAS:0;}
int hal_task_signal_enter(uintptr_t h,uintptr_t sp,int n,uintptr_t r,uint32_t t){struct sparcv9_user_trap_frame*f;unsigned w,d;if(!running||(f=running->active_user_frame)==NULL||running->signal_depth>=HAL_SIGNAL_NEST_MAX||!h||!sp||sp<SPARCV9_STACK_BIAS||!r||!t)return-1;d=running->signal_depth;running->signal_windows[d]=running->trap_windows;running->signal_frame[d]=*f;running->signal_pc[d]=running->active_pc;running->signal_next_pc[d]=running->active_next_pc;running->signal_tstate[d]=running->active_tstate;running->signal_token[d]=t;running->signal_depth=d+1U;w=user_output_window(&running->trap_windows);running->trap_windows.window[w][8]=(uint64)n;running->trap_windows.window[w][14]=sp-SPARCV9_STACK_BIAS;running->trap_windows.window[w][15]=r-8U;f->old_sp=sp-SPARCV9_STACK_BIAS;f->out[0]=(uint64)n;running->active_pc=h-4U;running->active_next_pc=h;set_user_trap(h-4U,h,running->active_tstate);return 0;}
int hal_task_signal_return(uint32_t t,intptr_t*v){struct sparcv9_user_trap_frame*f;unsigned d;if(!running||(f=running->active_user_frame)==NULL||!v||running->signal_depth==0||!t)return-1;d=running->signal_depth-1U;if(t!=running->signal_token[d])return-1;running->trap_windows=running->signal_windows[d];*f=running->signal_frame[d];*v=(intptr_t)f->out[0];running->active_pc=running->signal_pc[d];running->active_next_pc=running->signal_next_pc[d];running->active_tstate=running->signal_tstate[d];set_user_trap(running->active_pc,running->active_next_pc,running->active_tstate);running->signal_token[d]=0;running->signal_depth=d;return 0;}
int hal_task_signal_restart(uint32_t t,uint32_t n,const uintptr_t a[HAL_SYSCALL_ARGS],intptr_t*v){struct sparcv9_user_trap_frame*f;unsigned i,d;if(!running||(f=running->active_user_frame)==NULL||!a||!v||running->signal_depth==0||!t)return-1;d=running->signal_depth-1U;if(t!=running->signal_token[d]||running->signal_pc[d]<4U)return-1;running->trap_windows=running->signal_windows[d];*f=running->signal_frame[d];f->syscall_number=n;for(i=0;i<HAL_SYSCALL_ARGS;i++)f->out[i]=a[i];running->active_pc=running->signal_pc[d]-4U;running->active_next_pc=running->signal_pc[d];running->active_tstate=running->signal_tstate[d];set_user_trap(running->active_pc,running->active_next_pc,running->active_tstate);*v=(intptr_t)a[0];running->signal_token[d]=0;running->signal_depth=d;return 0;}
void hal_sparcv9_task_memory_stats(uint32*c,size_t*b){if(c)*c=task_count;if(b)*b=stack_bytes;}

static uint8 self_stack[4096]__attribute__((aligned(16)));static struct sparcv9_window_context main_context,test_context;static unsigned count;
static void self_task(void){count=1;sparcv9_task_dispatch(&test_context,&main_context);count=2;sparcv9_task_dispatch(&test_context,&main_context);for(;;)__asm__ volatile("nop");}
void sparcv9_context_selftest(void){uintptr_t top=(uintptr_t)(self_stack+sizeof(self_stack))&~15UL;hal_memset(&test_context,0,sizeof(test_context));test_context.cansave=6;test_context.cleanwin=7;test_context.window[1][14]=top-SPARCV9_STACK_BIAS-SPARCV9_STACK_FRAME_SIZE;test_context.window[1][15]=(uintptr_t)self_task-8U;sparcv9_task_dispatch(&main_context,&test_context);if(count!=1)HAL_FATAL("SPARC V9 context selftest first switch");sparcv9_task_dispatch(&main_context,&test_context);if(count!=2)HAL_FATAL("SPARC V9 context selftest second switch");hal_puts("SPARCV9 CONTEXT PASS\n");}
