build/ws035-p001/x68k-user/bin/sh
build/ws035-p001/x68k-user/bin/admin
build/ws035-p001/x68k-user/bin/ar
build/ws035-p001/x68k-user/bin/at
build/ws035-p001/x68k-user/bin/awk
build/ws035-p001/x68k-user/bin/basename
build/ws035-p001/x68k-user/bin/batch
build/ws035-p001/x68k-user/bin/bc
build/ws035-p001/x68k-user/bin/blkid
build/ws035-p001/x68k-user/bin/cal
build/ws035-p001/x68k-user/bin/cat
build/ws035-p001/x68k-user/bin/cflow
build/ws035-p001/x68k-user/bin/chgrp
build/ws035-p001/x68k-user/bin/chmod
build/ws035-p001/x68k-user/bin/chown
build/ws035-p001/x68k-user/bin/cksum
build/ws035-p001/x68k-user/bin/cmp
build/ws035-p001/x68k-user/bin/comm
build/ws035-p001/x68k-user/bin/compress
build/ws035-p001/x68k-user/bin/cp
build/ws035-p001/x68k-user/bin/cron
build/ws035-p001/x68k-user/bin/crontab
build/ws035-p001/x68k-user/bin/csplit
build/ws035-p001/x68k-user/bin/cut
build/ws035-p001/x68k-user/bin/cxref
build/ws035-p001/x68k-user/bin/date
build/ws035-p001/x68k-user/bin/dd
build/ws035-p001/x68k-user/bin/delta
build/ws035-p001/x68k-user/bin/df
build/ws035-p001/x68k-user/bin/diff
build/ws035-p001/x68k-user/bin/dirname
build/ws035-p001/x68k-user/bin/diskpart
build/ws035-p001/x68k-user/bin/dmesg
build/ws035-p001/x68k-user/bin/du
build/ws035-p001/x68k-user/bin/ed
build/ws035-p001/x68k-user/bin/expand
build/ws035-p001/x68k-user/bin/expr
build/ws035-p001/x68k-user/bin/file
build/ws035-p001/x68k-user/bin/find
build/ws035-p001/x68k-user/bin/fmt
build/ws035-p001/x68k-user/bin/fold
build/ws035-p001/x68k-user/bin/fuser
build/ws035-p001/x68k-user/bin/gencat
build/ws035-p001/x68k-user/bin/get
build/ws035-p001/x68k-user/bin/getconf
build/ws035-p001/x68k-user/bin/gettext
build/ws035-p001/x68k-user/bin/getty
build/ws035-p001/x68k-user/bin/grep
build/ws035-p001/x68k-user/bin/halt
build/ws035-p001/x68k-user/bin/head
build/ws035-p001/x68k-user/bin/hostname
build/ws035-p001/x68k-user/bin/iconv
build/ws035-p001/x68k-user/bin/id
build/ws035-p001/x68k-user/bin/infocmp
build/ws035-p001/x68k-user/bin/init
build/ws035-p001/x68k-user/bin/ipcrm
build/ws035-p001/x68k-user/bin/ipcs
build/ws035-p001/x68k-user/bin/join
build/ws035-p001/x68k-user/bin/kill
build/ws035-p001/x68k-user/bin/less
build/ws035-p001/x68k-user/bin/link
build/ws035-p001/x68k-user/bin/ln
build/ws035-p001/x68k-user/bin/locale
build/ws035-p001/x68k-user/bin/localedef
build/ws035-p001/x68k-user/bin/logger
build/ws035-p001/x68k-user/bin/login
build/ws035-p001/x68k-user/bin/logname
build/ws035-p001/x68k-user/bin/lp
build/ws035-p001/x68k-user/bin/lpr
build/ws035-p001/x68k-user/bin/ls
build/ws035-p001/x68k-user/bin/m4
build/ws035-p001/x68k-user/bin/mailx
build/ws035-p001/x68k-user/bin/mesg
build/ws035-p001/x68k-user/bin/mkdir
build/ws035-p001/x68k-user/bin/mkfifo
build/ws035-p001/x68k-user/bin/mkfs
build/ws035-p001/x68k-user/bin/mkswap
build/ws035-p001/x68k-user/bin/more
build/ws035-p001/x68k-user/bin/msgfmt
build/ws035-p001/x68k-user/bin/mv
build/ws035-p001/x68k-user/bin/newgrp
build/ws035-p001/x68k-user/bin/ngettext
build/ws035-p001/x68k-user/bin/nice
build/ws035-p001/x68k-user/bin/nl
build/ws035-p001/x68k-user/bin/nm
build/ws035-p001/x68k-user/bin/nohup
build/ws035-p001/x68k-user/bin/ntpdate
build/ws035-p001/x68k-user/bin/od
build/ws035-p001/x68k-user/bin/paste
build/ws035-p001/x68k-user/bin/patch
build/ws035-p001/x68k-user/bin/pathchk
build/ws035-p001/x68k-user/bin/pax
build/ws035-p001/x68k-user/bin/poweroff
build/ws035-p001/x68k-user/bin/pr
build/ws035-p001/x68k-user/bin/prs
build/ws035-p001/x68k-user/bin/ps
build/ws035-p001/x68k-user/bin/readlink
build/ws035-p001/x68k-user/bin/realpath
build/ws035-p001/x68k-user/bin/reboot
build/ws035-p001/x68k-user/bin/renice
build/ws035-p001/x68k-user/bin/rm
build/ws035-p001/x68k-user/bin/rmdel
build/ws035-p001/x68k-user/bin/rmdir
build/ws035-p001/x68k-user/bin/sact
build/ws035-p001/x68k-user/bin/sccs
build/ws035-p001/x68k-user/bin/sed
build/ws035-p001/x68k-user/bin/service
build/ws035-p001/x68k-user/bin/shutdown
build/ws035-p001/x68k-user/bin/sleep
build/ws035-p001/x68k-user/bin/sort
build/ws035-p001/x68k-user/bin/split
build/ws035-p001/x68k-user/bin/stat
build/ws035-p001/x68k-user/bin/strings
build/ws035-p001/x68k-user/bin/stty
build/ws035-p001/x68k-user/bin/swapoff
build/ws035-p001/x68k-user/bin/swapon
build/ws035-p001/x68k-user/bin/sync
build/ws035-p001/x68k-user/bin/syslogd
build/ws035-p001/x68k-user/bin/tabs
build/ws035-p001/x68k-user/bin/tail
build/ws035-p001/x68k-user/bin/talk
build/ws035-p001/x68k-user/bin/tee
build/ws035-p001/x68k-user/bin/tic
build/ws035-p001/x68k-user/bin/time
build/ws035-p001/x68k-user/bin/timeout
build/ws035-p001/x68k-user/bin/top
build/ws035-p001/x68k-user/bin/touch
build/ws035-p001/x68k-user/bin/tput
build/ws035-p001/x68k-user/bin/tr
build/ws035-p001/x68k-user/bin/truncate
build/ws035-p001/x68k-user/bin/tsort
build/ws035-p001/x68k-user/bin/tty
build/ws035-p001/x68k-user/bin/uname
build/ws035-p001/x68k-user/bin/uncompress
build/ws035-p001/x68k-user/bin/unexpand
build/ws035-p001/x68k-user/bin/unget
build/ws035-p001/x68k-user/bin/uniq
build/ws035-p001/x68k-user/bin/unlink
build/ws035-p001/x68k-user/bin/uudecode
build/ws035-p001/x68k-user/bin/uuencode
build/ws035-p001/x68k-user/bin/val
build/ws035-p001/x68k-user/bin/wc
build/ws035-p001/x68k-user/bin/what
build/ws035-p001/x68k-user/bin/who
build/ws035-p001/x68k-user/bin/write
build/ws035-p001/x68k-user/bin/xargs
build/ws035-p001/x68k-user/bin/zcat
