include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# zedBSD userland package
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,swapoff,swapoff,*,y,basic,userland/base/swapoff/main.c,y,base,,,0755,program,,,sbin))
