/* Minimal Xlib-compatible client library for Xzed. SPDX-License-Identifier: Zlib */
#include <X11/Xlib.h>
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
struct _XGC { uint32_t xid,foreground; };
struct _XDisplay { int fd; uint32_t base,next,root; unsigned long black,white; uint16_t sequence; uint8_t pending[32]; int has_pending; };
static void w16(uint8_t*p,uint16_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);} static void w32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);p[2]=(uint8_t)(v>>16);p[3]=(uint8_t)(v>>24);} static uint16_t r16(const uint8_t*p){return(uint16_t)(p[0]|p[1]<<8);} static uint32_t r32(const uint8_t*p){return(uint32_t)p[0]|(uint32_t)p[1]<<8|(uint32_t)p[2]<<16|(uint32_t)p[3]<<24;}
static int wr(int f,const void*v,size_t n){const uint8_t*p=v;while(n){ssize_t z=send(f,p,n,0);if(z<0){if(errno==EINTR)continue;return-1;}p+=z;n-=(size_t)z;}return 0;} static int rd(int f,void*v,size_t n){uint8_t*p=v;while(n){ssize_t z=recv(f,p,n,0);if(z<0){if(errno==EINTR)continue;return-1;}if(!z)return-1;p+=z;n-=(size_t)z;}return 0;}
static int req(Display*d,uint8_t*q,size_t n){w16(q+2,(uint16_t)(n/4));d->sequence++;return wr(d->fd,q,n);}
Display *XOpenDisplay(const char*n){struct sockaddr_un a;uint8_t q[12]={0},h[8],b[4096];uint16_t z;Display*d;(void)n;d=calloc(1,sizeof(*d));if(!d)return 0;d->fd=socket(AF_UNIX,SOCK_STREAM,0);if(d->fd<0)goto bad;memset(&a,0,sizeof(a));a.sun_family=AF_UNIX;strcpy(a.sun_path,"/tmp/.X11-unix/X0");if(connect(d->fd,(struct sockaddr*)&a,sizeof(a)))goto bad;q[0]='l';w16(q+2,11);if(wr(d->fd,q,12)||rd(d->fd,h,8)||h[0]!=1)goto bad;z=r16(h+6);if(z*4U>sizeof(b)||rd(d->fd,b,z*4U))goto bad;d->base=r32(b+4);d->next=1;d->root=r32(b+52);d->white=0xffffff;return d;bad:if(d->fd>=0)close(d->fd);free(d);return 0;}
int XCloseDisplay(Display*d){if(!d)return 0;close(d->fd);free(d);return 0;} int XDefaultScreen(Display*d){(void)d;return 0;} Window XRootWindow(Display*d,int s){(void)s;return d->root;} unsigned long XBlackPixel(Display*d,int s){(void)d;(void)s;return 0;} unsigned long XWhitePixel(Display*d,int s){(void)d;(void)s;return 0xffffff;}
Window XCreateSimpleWindow(Display*d,Window p,int x,int y,unsigned int wi,unsigned int he,unsigned int bw,unsigned long bc,unsigned long bg){uint8_t q[40]={0};uint32_t id=d->base|d->next++;q[0]=1;q[1]=24;w32(q+4,id);w32(q+8,p);w16(q+12,(uint16_t)x);w16(q+14,(uint16_t)y);w16(q+16,(uint16_t)wi);w16(q+18,(uint16_t)he);w16(q+20,(uint16_t)bw);w16(q+22,1);w32(q+24,3);w32(q+28,3);w32(q+32,(uint32_t)bc);w32(q+36,(uint32_t)bg);return req(d,q,sizeof(q))?0:id;}
int XSelectInput(Display*d,Window w,long m){uint8_t q[16]={0};q[0]=2;w32(q+4,w);w32(q+8,1U<<11);w32(q+12,(uint32_t)m);return req(d,q,16);}
static int winreq(Display*d,uint8_t op,Window w){uint8_t q[8]={0};q[0]=op;w32(q+4,w);return req(d,q,8);} int XMapWindow(Display*d,Window w){return winreq(d,8,w);}int XUnmapWindow(Display*d,Window w){return winreq(d,10,w);}int XDestroyWindow(Display*d,Window w){return winreq(d,4,w);}
GC XCreateGC(Display*d,Drawable w,unsigned long m,void*v){uint8_t q[16]={0};GC g=calloc(1,sizeof(*g));(void)m;(void)v;if(!g)return 0;g->xid=d->base|d->next++;g->foreground=0xffffff;q[0]=55;w32(q+4,g->xid);w32(q+8,w);if(req(d,q,16)){free(g);return 0;}return g;} int XFreeGC(Display*d,GC g){uint8_t q[8]={0};if(!g)return 0;q[0]=60;w32(q+4,g->xid);req(d,q,8);free(g);return 0;}int XSetForeground(Display*d,GC g,unsigned long c){uint8_t q[16]={0};g->foreground=(uint32_t)c;q[0]=56;w32(q+4,g->xid);w32(q+8,4);w32(q+12,(uint32_t)c);return req(d,q,16);}
int XFillRectangle(Display*d,Drawable w,GC g,int x,int y,unsigned int wi,unsigned int he){uint8_t q[20]={0};q[0]=70;w32(q+4,w);w32(q+8,g->xid);w16(q+12,(uint16_t)x);w16(q+14,(uint16_t)y);w16(q+16,(uint16_t)wi);w16(q+18,(uint16_t)he);return req(d,q,20);}int XDrawLine(Display*d,Drawable w,GC g,int x,int y,int x2,int y2){uint8_t q[20]={0};q[0]=65;w32(q+4,w);w32(q+8,g->xid);w16(q+12,(uint16_t)x);w16(q+14,(uint16_t)y);w16(q+16,(uint16_t)x2);w16(q+18,(uint16_t)y2);return req(d,q,20);}
static void event(Display*d,const uint8_t*b,XEvent*e){memset(e,0,sizeof(*e));e->type=b[0]&0x7f;e->xany.display=d;e->xany.window=r32(b+12);e->xany.serial=r16(b+2);if(e->type==Expose){e->xexpose.window=r32(b+4);e->xexpose.x=r16(b+8);e->xexpose.y=r16(b+10);e->xexpose.width=r16(b+12);e->xexpose.height=r16(b+14);e->xexpose.count=r16(b+16);}else{e->xkey.keycode=b[1];e->xkey.time=r32(b+4);e->xkey.root=r32(b+8);e->xkey.window=r32(b+12);e->xkey.subwindow=r32(b+16);e->xkey.x_root=(int16_t)r16(b+20);e->xkey.y_root=(int16_t)r16(b+22);e->xkey.x=(int16_t)r16(b+24);e->xkey.y=(int16_t)r16(b+26);e->xkey.state=r16(b+28);e->xkey.same_screen=b[30];}}
int XNextEvent(Display*d,XEvent*e){uint8_t b[32];if(d->has_pending){memcpy(b,d->pending,32);d->has_pending=0;}else if(rd(d->fd,b,32))return-1;event(d,b,e);return 0;}int XPending(Display*d){int f,z;if(d->has_pending)return 1;f=fcntl(d->fd,F_GETFL);fcntl(d->fd,F_SETFL,f|O_NONBLOCK);z=(int)recv(d->fd,d->pending,32,MSG_DONTWAIT);fcntl(d->fd,F_SETFL,f);if(z==32)d->has_pending=1;return d->has_pending;}int XFlush(Display*d){(void)d;return 0;}int XSync(Display*d,Bool discard){(void)d;(void)discard;return 0;}
