/* Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib */
#ifndef ZEDBSD_LANGINFO_H
#define ZEDBSD_LANGINFO_H
#include <zedbsd/locale-format.h>

typedef int nl_item;

#define CODESET ZEDBSD_LOCALE_KEY_CODESET
#define RADIXCHAR ZEDBSD_LOCALE_KEY_DECIMAL_POINT
#define THOUSEP ZEDBSD_LOCALE_KEY_THOUSANDS_SEP
#define CRNCYSTR ZEDBSD_LOCALE_KEY_CURRENCY_SYMBOL
#define D_T_FMT ZEDBSD_LOCALE_KEY_D_T_FMT
#define D_FMT ZEDBSD_LOCALE_KEY_D_FMT
#define T_FMT ZEDBSD_LOCALE_KEY_T_FMT
#define T_FMT_AMPM ZEDBSD_LOCALE_KEY_T_FMT_AMPM
#define AM_STR ZEDBSD_LOCALE_KEY_AM_STR
#define PM_STR ZEDBSD_LOCALE_KEY_PM_STR
#define ABDAY_1 ZEDBSD_LOCALE_KEY_ABDAY_1
#define ABDAY_2 ZEDBSD_LOCALE_KEY_ABDAY_2
#define ABDAY_3 ZEDBSD_LOCALE_KEY_ABDAY_3
#define ABDAY_4 ZEDBSD_LOCALE_KEY_ABDAY_4
#define ABDAY_5 ZEDBSD_LOCALE_KEY_ABDAY_5
#define ABDAY_6 ZEDBSD_LOCALE_KEY_ABDAY_6
#define ABDAY_7 ZEDBSD_LOCALE_KEY_ABDAY_7
#define DAY_1 ZEDBSD_LOCALE_KEY_DAY_1
#define DAY_2 ZEDBSD_LOCALE_KEY_DAY_2
#define DAY_3 ZEDBSD_LOCALE_KEY_DAY_3
#define DAY_4 ZEDBSD_LOCALE_KEY_DAY_4
#define DAY_5 ZEDBSD_LOCALE_KEY_DAY_5
#define DAY_6 ZEDBSD_LOCALE_KEY_DAY_6
#define DAY_7 ZEDBSD_LOCALE_KEY_DAY_7
#define ABMON_1 ZEDBSD_LOCALE_KEY_ABMON_1
#define ABMON_2 ZEDBSD_LOCALE_KEY_ABMON_2
#define ABMON_3 ZEDBSD_LOCALE_KEY_ABMON_3
#define ABMON_4 ZEDBSD_LOCALE_KEY_ABMON_4
#define ABMON_5 ZEDBSD_LOCALE_KEY_ABMON_5
#define ABMON_6 ZEDBSD_LOCALE_KEY_ABMON_6
#define ABMON_7 ZEDBSD_LOCALE_KEY_ABMON_7
#define ABMON_8 ZEDBSD_LOCALE_KEY_ABMON_8
#define ABMON_9 ZEDBSD_LOCALE_KEY_ABMON_9
#define ABMON_10 ZEDBSD_LOCALE_KEY_ABMON_10
#define ABMON_11 ZEDBSD_LOCALE_KEY_ABMON_11
#define ABMON_12 ZEDBSD_LOCALE_KEY_ABMON_12
#define MON_1 ZEDBSD_LOCALE_KEY_MON_1
#define MON_2 ZEDBSD_LOCALE_KEY_MON_2
#define MON_3 ZEDBSD_LOCALE_KEY_MON_3
#define MON_4 ZEDBSD_LOCALE_KEY_MON_4
#define MON_5 ZEDBSD_LOCALE_KEY_MON_5
#define MON_6 ZEDBSD_LOCALE_KEY_MON_6
#define MON_7 ZEDBSD_LOCALE_KEY_MON_7
#define MON_8 ZEDBSD_LOCALE_KEY_MON_8
#define MON_9 ZEDBSD_LOCALE_KEY_MON_9
#define MON_10 ZEDBSD_LOCALE_KEY_MON_10
#define MON_11 ZEDBSD_LOCALE_KEY_MON_11
#define MON_12 ZEDBSD_LOCALE_KEY_MON_12
#define ERA ZEDBSD_LOCALE_KEY_ERA
#define ERA_D_FMT ZEDBSD_LOCALE_KEY_ERA_D_FMT
#define ERA_D_T_FMT ZEDBSD_LOCALE_KEY_ERA_D_T_FMT
#define ERA_T_FMT ZEDBSD_LOCALE_KEY_ERA_T_FMT
#define ALT_DIGITS ZEDBSD_LOCALE_KEY_ALT_DIGITS
#define YESEXPR ZEDBSD_LOCALE_KEY_YESEXPR
#define NOEXPR ZEDBSD_LOCALE_KEY_NOEXPR
#define YESSTR ZEDBSD_LOCALE_KEY_YESSTR
#define NOSTR ZEDBSD_LOCALE_KEY_NOSTR
char *nl_langinfo(nl_item);
#endif
