include $(dir $(lastword $(MAKEFILE_LIST)))../../base/package.mk

# zedBSD Venus diagnostic client
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,venus-frame,Venus Vulkan test frame,amd64,n,basic,userland/gpu/venus/venus-frame.c userland/gpu/venus/client.c,y,base,,,0755,program,,,bin))
