#!/usr/bin/env python3
"""ws031-p024 increment 3: writes the spill shaders of the host compile test (plan/ws031/tests/i915-vk-compile-test.c,
test_p024_spill_mix) and compiles them with glslc.  Each keeps N values of the pixel live over a loop whose trip
count differs from channel to channel; the loop samples a texture (its reply lands while the values are spilled),
a discard follows while they are still live, and the end sums the products t[k] * t[(7k + 5) % N].  The C test
computes the same in the same order."""
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
#
# usage: python3 plan/ws031/tests/p024/gen-spill.py
import pathlib
import subprocess

HERE = pathlib.Path(__file__).resolve().parent

# Name and number of live values: 96 spills about as spill.frag does, 224 more than 4 KiB a thread.
SHADERS = (('spilltex', 96), ('spillbig', 224))


def source(count):
    lines = [
        '/* Generated by gen-spill.py (ws031-p024); do not edit. */',
        '#version 450',
        '',
        'layout(location = 0) in vec2 place;',
        'layout(set = 0, binding = 0) uniform sampler2D image;',
        'layout(location = 0) out vec4 color;',
        '',
        'void main()',
        '{',
        '    float x = place.x;',
        '    float y = place.y;',
    ]
    for k in range(count):
        lines.append(f'    float t{k} = x * {float(k + 1)} + y;')
    lines += [
        '    float a = t7;',
        '    float b = t50;',
        '    uint n = uint(x * 8.0) % 5u;',
        '    for (uint i = 0u; i < n; i++) {',
        '        vec4 s = texture(image, vec2(a * 0.125, b * 0.0625));',
        '        a = a * 0.5 + s.x;',
        '        b = b + s.w - s.z * 0.25;',
        '    }',
        '    if (n == 2u)',
        '        discard;',
        '    float sum = 0.0;',
    ]
    for k in range(count):
        lines.append(f'    sum += t{k} * t{(7 * k + 5) % count};')
    lines += [
        '    color = vec4(sum + a, a, b, float(n));',
        '}',
        '',
    ]
    return '\n'.join(lines)


for name, count in SHADERS:
    glsl = HERE / f'{name}.frag'
    glsl.write_text(source(count))
    subprocess.run(['glslc', '--target-env=vulkan1.0', '-O0', '-fshader-stage=fragment', '-o', str(HERE / f'{name}.frag.spv'),
                    str(glsl)], check=True)
