# zedBSD
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,gpu-admission-test,GPU concurrent admission test,amd64,y,basic,userland/base/tests/gpu-admission/main.c,y,base,base/tests/gpu-admission,,0755,program,,,bin))
