# zedBSD X11 demo package
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,xzed-demo,xzed-demo,*,n,basic,userland/X11/tests/demo.c userland/X11/libX11/xlib.c,y,X11,,))
