# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,diskpart,diskpart,*,y,basic,userland/base/diskpart/main.c userland/base/diskpart/table.c,y,base,,,0755,program,,,sbin))
