include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,lpr,lpr,*,y,basic,userland/base/lp/main.c userland/base/lp/lpd-client.c,y,base,,))
