# Focused textured 3D demo configuration; ordinary config.mk is untouched.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
ZEDBSD_MENU_VERSION := 3
ZEDBSD_PLATFORM := amd64
ZEDBSD_ARCHITECTURE := amd64
ZEDBSD_BOARD := pcat
ZEDBSD_VARIANT := hybrid
CONFIG_KERNEL_TEST_CHECKPOINTS := n
CONFIG_BUF_CACHE_KIB := 0
CONFIG_DRIVER_NE2000 := n
CONFIG_DRIVER_PCI_UHCI := n
CONFIG_DRIVER_PCI_EHCI := n
CONFIG_DRIVER_PCI_XHCI := y
CONFIG_DRIVER_PCI_NVME := n
CONFIG_DRIVER_PCI_INTEL_AX211 := n
CONFIG_DRIVER_PCI_VENUS := y
CONFIG_DRIVER_USB_STORAGE := y
CONFIG_DRIVER_USB_CDC_NCM := n
CONFIG_DRIVER_USB_CDC_ECM := n
CONFIG_DRIVER_USB_HID := n
CONFIG_DRIVER_USB_RTL8822BU := n
CONFIG_DRIVER_GRAPHICS := n
CONFIG_DRIVER_LGY98 := n
ZEDBSD_USER_PROGRAMS := vkdemo venus-frame cat ls dmesg sleep sync
