# Automatically generated by the zedBSD build menu.  Do not edit.
ZEDBSD_MENU_VERSION := 3
ZEDBSD_PLATFORM := amd64
ZEDBSD_ARCHITECTURE := amd64
ZEDBSD_BOARD := pcat
ZEDBSD_VARIANT := uefi

CONFIG_KERNEL_TEST_CHECKPOINTS := n
CONFIG_BUF_CACHE_KIB := 0
CONFIG_DRIVER_NE2000 := n
CONFIG_DRIVER_PCI_UHCI := y
CONFIG_DRIVER_PCI_EHCI := y
CONFIG_DRIVER_PCI_XHCI := y
CONFIG_DRIVER_PCI_NVME := y
CONFIG_DRIVER_PCI_INTEL_AX211 := y
CONFIG_DRIVER_USB_STORAGE := y
CONFIG_DRIVER_USB_CDC_NCM := y
CONFIG_DRIVER_USB_CDC_ECM := y
CONFIG_DRIVER_USB_HID := y
CONFIG_DRIVER_USB_RTL8822BU := y
CONFIG_DRIVER_GRAPHICS := y
CONFIG_DRIVER_LGY98 := n

ZEDBSD_USER_PROGRAMS := Xzed zshell zterm zwm admin ar at awk basename batch bc blkid cal cat cflow chgrp chmod chown cksum cmp comm compress cp crontab csplit curses cut cxref date dd delta df dhcpc diff dirname dmesg du ed expand expr fetch file find fmt fold fuser gencat get getconf gettext grep halt head host hostname iconv id ifconfig infocmp ipcrm ipcs join kill less link ln locale localedef logger login logname lp lpr ls m4 mailx mesg mkdir mkfifo more msgfmt mv newgrp ngettext nice nl nm nohup nslookup ntpdate od paste patch pathchk pax ping poweroff pr prs ps readlink realpath reboot renice rm rmdel rmdir route sact sccs sed service shutdown sleep sort split stat strings stty swapoff swapon tabs tail talk tee terminfo-extra terminfo tic time timeout top touch tput tr truncate tsort tty uname uncompress unexpand unget uniq unlink uudecode uuencode val wc what who wifi write xargs zcat intelax211-firmware rtl8822b-firmware
