# AMD64 build composition.
include platform/amd64/vmunix.mk
include platform/amd64/bootloader.mk
include platform/amd64/rootfs.mk
include platform/amd64/disk-image.mk
include platform/amd64/run.mk
include platform/amd64/toolchain.mk
