include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,val,val,*,y,basic,userland/base/sccs/main.c userland/base/common/sccs.c,y,base,,))
