# PC-98 build composition.
include platform/pc98/vmunix.mk
include platform/pc98/bootloader.mk
include platform/pc98/rootfs.mk
include platform/pc98/disk-image.mk
include platform/pc98/run.mk
include platform/pc98/toolchain.mk
