/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * The executor scenario "vkx": command buffers recorded through the wire
 * and run on the GPU, checked against images and bytes the CPU computes.
 *
 * The executor runs its GPU work on the request worker, which serves only
 * once the node is published, so the scenario starts a thread and returns;
 * the thread waits for the node, opens a session of its own as a client
 * would, and drives the executor with the wire commands libvulkan sends.
 * The objects a command buffer names (the storage, buffers, target, render
 * pass, framebuffer and pipelines) are made directly and published in the
 * executor's object table, so each step exercises the recording and its
 * execution: indexed draws with 16- and 32-bit indices, a vertex offset and
 * a first index; dynamic viewports and scissors; buffer copies; a command
 * buffer of well over 64 operations whose fragment shader reads the pushed
 * colour at byte 112; a mipmapped texture whose levels are filled with
 * distinct colours by per-level copies and sampled minified with nearest
 * and linear mip filtering, a LOD range, a LOD bias and a view of later
 * levels; a mip chain generated by linear blits from level to level.  Each
 * step logs "VKX-<name> PASS" or "FAIL", then the thread logs the verdict
 * and closes the session.
 */

#include "scenarios.h"
#include <kern/kcrt.h>

#include "../../compiler/compiler.h"
#include "../../i915.h"
#include "../../memory.h"
#include "../../session.h"
#include "../../sync.h"
#include "../../render/gfx.h"
#include "../../render/internal.h"
#include "../../render/object.h"
#include "../../render/render.h"

#include <drivers/gpu/gpu.h>
#include <kern/clock.h>
#include <kern/klog.h>
#include <kern/lock.h>
#include <kern/sched.h>
#include <kern/thread.h>

#include <libc/vulkan/vulkan_core.h>

#include <uapi/errno.h>
#include <stddef.h>
#include <stdint.h>

#include "../fixtures/executor-shaders-gen.inc"

/* The side of the square target, in pixels. */
#define I915_VKX_SIZE			64U

/* The storage every buffer and the target are bound in, and where each is. */
#define I915_VKX_STORAGE_BYTES		(1024U * 1024U)
#define I915_VKX_TARGET_OFFSET		0x00000U
#define I915_VKX_VERTEX_OFFSET		0x10000U
#define I915_VKX_VERTEX_BYTES		0x01000U
#define I915_VKX_INDEX_OFFSET		0x20000U
#define I915_VKX_INDEX_BYTES		0x01000U
#define I915_VKX_SOURCE_OFFSET		0x30000U
#define I915_VKX_DESTINATION_OFFSET	0x60000U
#define I915_VKX_COPY_BYTES		0x28000U
#define I915_VKX_TEXTURE_OFFSET		0x90000U
#define I915_VKX_CHAIN_OFFSET		0xa0000U

/* Where the 32-bit indices sit in the index buffer, after the 16-bit ones. */
#define I915_VKX_INDEX32_OFFSET		256U

/*
 * The mipmapped images of the mip steps: 64x64 RGBA8 with all 7 levels,
 * the largest level first; the first of the textured quads in the vertex
 * buffer; how far a sampled or filtered byte may be from its reference.
 */
#define I915_VKX_MIP_SIZE		64U
#define I915_VKX_MIP_LEVELS		7U
#define I915_VKX_TEXQUAD_FIRST		32U
#define I915_VKX_MIP_TOLERANCE		2U

/* The bytes of one vertex: a vec4 position, then a vec4 colour. */
#define I915_VKX_VERTEX_STRIDE		32U

/* The wire identities the scenario publishes its objects under, apart from any client's. */
#define I915_VKX_IDENTITY		0x7e57000000000000ULL
#define I915_VKX_ID_VERTICES		(I915_VKX_IDENTITY + 1U)
#define I915_VKX_ID_INDICES		(I915_VKX_IDENTITY + 2U)
#define I915_VKX_ID_SOURCE		(I915_VKX_IDENTITY + 3U)
#define I915_VKX_ID_DESTINATION		(I915_VKX_IDENTITY + 4U)
#define I915_VKX_ID_PASS		(I915_VKX_IDENTITY + 5U)
#define I915_VKX_ID_FRAMEBUFFER		(I915_VKX_IDENTITY + 6U)
#define I915_VKX_ID_COLOR_PIPELINE	(I915_VKX_IDENTITY + 7U)
#define I915_VKX_ID_DYNAMIC_PIPELINE	(I915_VKX_IDENTITY + 8U)
#define I915_VKX_ID_PUSH_PIPELINE	(I915_VKX_IDENTITY + 9U)
#define I915_VKX_ID_POOL		(I915_VKX_IDENTITY + 10U)
#define I915_VKX_ID_COMMAND_BUFFER	(I915_VKX_IDENTITY + 11U)
#define I915_VKX_ID_TEXTURE		(I915_VKX_IDENTITY + 12U)
#define I915_VKX_ID_CHAIN		(I915_VKX_IDENTITY + 13U)
#define I915_VKX_ID_TEX_PIPELINE	(I915_VKX_IDENTITY + 14U)
#define I915_VKX_ID_SET_NEAREST		(I915_VKX_IDENTITY + 15U)
#define I915_VKX_ID_SET_FORCED		(I915_VKX_IDENTITY + 16U)
#define I915_VKX_ID_SET_BIAS		(I915_VKX_IDENTITY + 17U)
#define I915_VKX_ID_SET_LATER		(I915_VKX_IDENTITY + 18U)
#define I915_VKX_ID_SET_LINEAR		(I915_VKX_IDENTITY + 19U)
#define I915_VKX_ID_SET_LOD5		(I915_VKX_IDENTITY + 20U)
#define I915_VKX_ID_SET_LOD5_HALF	(I915_VKX_IDENTITY + 21U)
#define I915_VKX_ID_SET_LOD6		(I915_VKX_IDENTITY + 22U)

/* The wire opcodes the scenario sends, as libvulkan numbers them. */
#define I915_VKX_OP_QUEUE_SUBMIT		18U
#define I915_VKX_OP_CREATE_COMMAND_POOL		85U
#define I915_VKX_OP_DESTROY_COMMAND_POOL	86U
#define I915_VKX_OP_ALLOCATE_COMMAND_BUFFERS	88U
#define I915_VKX_OP_BEGIN_COMMAND_BUFFER	90U
#define I915_VKX_OP_END_COMMAND_BUFFER		91U
#define I915_VKX_OP_BIND_PIPELINE		93U
#define I915_VKX_OP_SET_VIEWPORT		94U
#define I915_VKX_OP_SET_SCISSOR			95U
#define I915_VKX_OP_BIND_DESCRIPTOR_SETS	103U
#define I915_VKX_OP_BIND_INDEX_BUFFER		104U
#define I915_VKX_OP_BIND_VERTEX_BUFFERS		105U
#define I915_VKX_OP_DRAW_INDEXED		107U
#define I915_VKX_OP_COPY_BUFFER			112U
#define I915_VKX_OP_BLIT_IMAGE			114U
#define I915_VKX_OP_COPY_BUFFER_TO_IMAGE	115U
#define I915_VKX_OP_COPY_IMAGE_TO_BUFFER	116U
#define I915_VKX_OP_PUSH_CONSTANTS		132U
#define I915_VKX_OP_BEGIN_RENDER_PASS		133U
#define I915_VKX_OP_END_RENDER_PASS		135U

/* The largest stream the scenario builds, and the room for its replies. */
#define I915_VKX_WIRE_BYTES		32768U
#define I915_VKX_REPLY_BYTES		4096U

/* The bytes of the push constant block, and where the fragment colour sits in it. */
#define I915_VKX_PUSH_BYTES		128U
#define I915_VKX_PUSH_COLOR		112U

/* How long the thread waits for the node to be published, in seconds. */
#define I915_VKX_WAIT_S			120U

/* IEEE-754 bits of the floats the scenario uses; the kernel computes no float. */
#define I915_VKX_F_0			0x00000000U
#define I915_VKX_F_QUARTER		0x3e800000U
#define I915_VKX_F_HALF			0x3f000000U
#define I915_VKX_F_THREE_QUARTERS	0x3f400000U
#define I915_VKX_F_1			0x3f800000U
#define I915_VKX_F_8			0x41000000U
#define I915_VKX_F_16			0x41800000U
#define I915_VKX_F_24			0x41c00000U
#define I915_VKX_F_32			0x42000000U
#define I915_VKX_F_40			0x42200000U
#define I915_VKX_F_64			0x42800000U
#define I915_VKX_F_ONE_AND_HALF		0x3fc00000U
#define I915_VKX_F_2			0x40000000U
#define I915_VKX_F_5			0x40a00000U
#define I915_VKX_F_FIVE_AND_HALF	0x40b00000U
#define I915_VKX_F_6			0x40c00000U

/* The pixels the scenario writes: RGBA8 in memory, red in the low byte. */
#define I915_VKX_BLACK			0xff000000U
#define I915_VKX_RED			0xff0000ffU
#define I915_VKX_GREEN			0xff00ff00U
#define I915_VKX_BLUE			0xffff0000U
#define I915_VKX_WHITE			0xffffffffU

/*
 * Everything the scenario owns while its thread runs.
 *
 * It is filled by the setup, used by the steps and emptied by the teardown,
 * all on the scenario's thread; the scenario runs once per boot.
 */
struct i915_vkx {
	/* The device, and the node and executor sessions the scenario opened. */
	struct i915_device *device;
	struct i915_session *session;
	struct i915_render_session *render;

	/* The storage object and its CPU view; the memory that names it. */
	struct i915_gem_object *storage;
	uint8_t *cpu;
	struct i915_gfx_memory memory;

	/* The target, its view, the render pass and the framebuffer. */
	struct i915_gfx_image target;
	struct i915_gfx_view view;
	struct i915_gfx_pass pass;
	struct i915_gfx_framebuffer framebuffer;

	/* The vertex, index and transfer buffers. */
	struct i915_gfx_buffer vertices;
	struct i915_gfx_buffer indices;
	struct i915_gfx_buffer source;
	struct i915_gfx_buffer destination;

	/* The shader modules and the three pipelines made from them. */
	struct i915_gfx_shader place;
	struct i915_gfx_shader color;
	struct i915_gfx_shader push;
	struct i915_gfx_pipeline color_pipeline;
	struct i915_gfx_pipeline dynamic_pipeline;
	struct i915_gfx_pipeline push_pipeline;

	/*
	 * The mip steps' objects: the sampled texture and the blitted chain;
	 * the texturing shader and pipeline; a view of every level of the
	 * texture and one of level 2 on; the samplers (nearest level, LOD fixed
	 * at 1.5 with linear blending, bias 2, linear blending over the whole
	 * range, and the least LOD held at 5, 5.5 with linear blending and 6)
	 * and the sets that pair them.
	 */
	struct i915_gfx_image texture;
	struct i915_gfx_image chain;
	struct i915_gfx_shader tex;
	struct i915_gfx_pipeline tex_pipeline;
	struct i915_gfx_view texture_view;
	struct i915_gfx_view later_view;
	struct i915_gfx_sampler nearest_sampler;
	struct i915_gfx_sampler forced_sampler;
	struct i915_gfx_sampler bias_sampler;
	struct i915_gfx_sampler linear_sampler;
	struct i915_gfx_sampler lod5_sampler;
	struct i915_gfx_sampler lod5_half_sampler;
	struct i915_gfx_sampler lod6_sampler;
	struct i915_gfx_dset nearest_set;
	struct i915_gfx_dset forced_set;
	struct i915_gfx_dset bias_set;
	struct i915_gfx_dset later_set;
	struct i915_gfx_dset linear_set;
	struct i915_gfx_dset lod5_set;
	struct i915_gfx_dset lod5_half_set;
	struct i915_gfx_dset lod6_set;

	/* Nonzero once the objects are published, and once the command pool exists. */
	int published;
	int pooled;

	/* The stream under construction, and nonzero once it overflowed. */
	uint8_t wire[I915_VKX_WIRE_BYTES];
	size_t used;
	int overflow;

	/* The replies of the last stream, and how many bytes they took. */
	uint8_t reply[I915_VKX_REPLY_BYTES];
	size_t reply_bytes;

	/* The image a step expects the target to hold. */
	uint32_t expected[I915_VKX_SIZE * I915_VKX_SIZE];

	/* The model of the destination buffer a copy expects. */
	uint8_t model[I915_VKX_COPY_BYTES];

	/* How many steps passed and failed. */
	unsigned passed;
	unsigned failed;
};

/*
 * The scenario's state.
 *
 * Only the scenario's thread touches it, from its start to its end; the
 * scenario runs once per boot.
 */
static struct i915_vkx i915_vkx_state;

/* The bits of -1, -0.75 .. 1 in steps of 0.25: NDC coordinate k maps to pixel 8 * k. */
static const uint32_t i915_vkx_ndc[9] = {
	0xbf800000U,
	0xbf400000U,
	0xbf000000U,
	0xbe800000U,
	0x00000000U,
	0x3e800000U,
	0x3f000000U,
	0x3f400000U,
	0x3f800000U,
};

/* The bits of 0 .. 1.75 in steps of 0.25: the offset of grid column or row c. */
static const uint32_t i915_vkx_steps[8] = {
	0x00000000U,
	0x3e800000U,
	0x3f000000U,
	0x3f400000U,
	0x3f800000U,
	0x3fa00000U,
	0x3fc00000U,
	0x3fe00000U,
};

/* The four colour levels of the grid as float bits: 0, 0.25, 0.75 and 1. */
static const uint32_t i915_vkx_level_bits[4] = {
	I915_VKX_F_0,
	I915_VKX_F_QUARTER,
	I915_VKX_F_THREE_QUARTERS,
	I915_VKX_F_1,
};

/* The bytes an RGBA8 target stores for each level: the level times 255, rounded to nearest. */
static const uint32_t i915_vkx_level_bytes[4] = {
	0U,
	64U,
	191U,
	255U,
};

/*
 * The colour each level of the sampled texture is filled with: red, green,
 * blue, yellow, cyan, magenta, white, all opaque (RGBA8 in memory, red in
 * the low byte).
 */
static const uint32_t i915_vkx_level_colors[I915_VKX_MIP_LEVELS] = {
	0xff0000ffU,
	0xff00ff00U,
	0xffff0000U,
	0xff00ffffU,
	0xffffff00U,
	0xffff00ffU,
	0xffffffffU,
};

static void i915_vkx_thread(void *argument);
static int i915_vkx_wait_node(struct i915_device *device);
static int i915_vkx_setup(struct i915_vkx *x);
static void i915_vkx_teardown(struct i915_vkx *x);
static int i915_vkx_storage_create(struct i915_vkx *x);
static void i915_vkx_objects_init(struct i915_vkx *x);
static int i915_vkx_objects_publish(struct i915_vkx *x);
static void i915_vkx_objects_withdraw(struct i915_vkx *x);
static void i915_vkx_pipeline_init(struct i915_vkx *x, struct i915_gfx_pipeline *pipeline, struct i915_gfx_shader *fragment, int dynamic);
static int i915_vkx_pipelines_prepare(struct i915_vkx *x);
static void i915_vkx_vertices_write(struct i915_vkx *x);
static void i915_vkx_quad_write(uint32_t *words, unsigned left, unsigned top, unsigned right, unsigned bottom, const uint32_t color[4]);
static void i915_vkx_indices_write(struct i915_vkx *x);
static void i915_vkx_put32(struct i915_vkx *x, uint32_t value);
static void i915_vkx_put64(struct i915_vkx *x, uint64_t value);
static void i915_vkx_record(struct i915_vkx *x, uint32_t opcode);
static int i915_vkx_execute(struct i915_vkx *x, const char *what);
static uint32_t i915_vkx_reply32(const struct i915_vkx *x, size_t offset);
static int i915_vkx_pool_create(struct i915_vkx *x);
static void i915_vkx_begin(struct i915_vkx *x);
static void i915_vkx_begin_pass(struct i915_vkx *x);
static void i915_vkx_bind_pipeline(struct i915_vkx *x, uint64_t pipeline);
static void i915_vkx_bind_vertices(struct i915_vkx *x);
static void i915_vkx_bind_indices(struct i915_vkx *x, uint64_t offset, uint32_t type);
static void i915_vkx_draw_indexed(struct i915_vkx *x, uint32_t count, uint32_t instances, uint32_t first, int32_t vertex_offset, uint32_t first_instance);
static void i915_vkx_set_viewport(struct i915_vkx *x, uint32_t left, uint32_t top, uint32_t width, uint32_t height);
static void i915_vkx_set_scissor(struct i915_vkx *x, uint32_t left, uint32_t top, uint32_t width, uint32_t height);
static void i915_vkx_push(struct i915_vkx *x, const uint32_t *block);
static int i915_vkx_finish(struct i915_vkx *x, const char *what);
static void i915_vkx_expect_clear(struct i915_vkx *x);
static void i915_vkx_expect_rect(struct i915_vkx *x, unsigned left, unsigned top, unsigned right, unsigned bottom, uint32_t pixel);
static int i915_vkx_compare_target(struct i915_vkx *x, const char *what);
static void i915_vkx_verdict(struct i915_vkx *x, const char *what, int error);
static void i915_vkx_step_index16(struct i915_vkx *x);
static void i915_vkx_step_index32(struct i915_vkx *x);
static void i915_vkx_step_viewport(struct i915_vkx *x);
static void i915_vkx_step_copy(struct i915_vkx *x);
static void i915_vkx_step_grid(struct i915_vkx *x);
static void i915_vkx_mip_objects_init(struct i915_vkx *x);
static void i915_vkx_mip_sampler_init(struct i915_gfx_sampler *sampler, uint32_t mipmap_mode, uint32_t lod_bias, uint32_t min_lod, uint32_t max_lod);
static void i915_vkx_texquad_write(uint32_t *words, unsigned left, unsigned top, unsigned right, unsigned bottom);
static uint32_t i915_vkx_level_extent(uint32_t level);
static void i915_vkx_subresource(struct i915_vkx *x, uint32_t level);
static void i915_vkx_level_copy(struct i915_vkx *x, uint32_t opcode, uint64_t image, uint32_t level, uint64_t buffer_offset);
static void i915_vkx_level_blit(struct i915_vkx *x, uint64_t image, uint32_t level);
static void i915_vkx_bind_set(struct i915_vkx *x, uint64_t set);
static void i915_vkx_texture_fill(struct i915_vkx *x);
static uint32_t i915_vkx_blend(uint32_t first, uint32_t second);
static int i915_vkx_near(uint32_t pixel, uint32_t expected);
static int i915_vkx_compare_near(struct i915_vkx *x, const char *what);
static void i915_vkx_step_mip_nearest(struct i915_vkx *x);
static void i915_vkx_step_mip_linear(struct i915_vkx *x);
static void i915_vkx_step_mip_blit(struct i915_vkx *x);

/*
 * Starts the executor scenario.
 *
 * Returns at once: the scenario's thread runs the steps after the node is
 * published and logs their verdicts itself.
 */
void
drv_i915_test_render_executor(
	struct i915_device *device)
{
	struct thread *thread;
	int error;

	/* Starts the thread that waits for the node and runs the steps. */
	error = kthread_create(i915_vkx_thread, device, SCHED_PRIORITY_DEFAULT, &thread);
	if (error != 0) {
		kern_logf("i915: vkx: verdict FAIL (the scenario thread cannot be created: %d)\n", error);
		return;
	}

	/* The thread reclaims itself when the steps are done. */
	thread->detached = 1U;
	thread_start(thread);
	kern_logf("i915: vkx: the steps run once the node is published\n");
}

/* Runs the scenario: waits for the node, sets up, runs every step, tears down and logs the verdict. */
static void
i915_vkx_thread(
	void *argument)
{
	struct i915_device *device;
	struct i915_vkx *x;
	int error;

	/* Waits until the node is published and its worker serves. */
	device = argument;
	error = i915_vkx_wait_node(device);
	if (error != 0) {
		kern_logf("i915: vkx: verdict FAIL (the node was not published within %u s)\n", I915_VKX_WAIT_S);
		return;
	}

	/* Opens the session and makes every object the steps use. */
	x = &i915_vkx_state;
	kern_memset(x, 0, sizeof(*x));
	x->device = device;
	error = i915_vkx_setup(x);
	if (error != 0) {
		kern_logf("i915: vkx: verdict FAIL (setup: %d)\n", error);
		i915_vkx_teardown(x);
		return;
	}

	/* Runs every step; each logs its own verdict. */
	i915_vkx_step_index16(x);
	i915_vkx_step_index32(x);
	i915_vkx_step_viewport(x);
	i915_vkx_step_copy(x);
	i915_vkx_step_grid(x);
	i915_vkx_step_mip_nearest(x);
	i915_vkx_step_mip_linear(x);
	i915_vkx_step_mip_blit(x);

	/* Gives everything back and says how the steps went. */
	i915_vkx_teardown(x);
	if (x->failed != 0U) {
		kern_logf("i915: vkx: verdict FAIL (%u of %u steps passed)\n", x->passed, x->passed + x->failed);
		return;
	}

	kern_logf("i915: vkx: verdict PASS (%u of %u steps passed)\n", x->passed, x->passed + x->failed);
}

/* Waits until the node is published, sleeping a twentieth of a second at a time; ETIMEDOUT when it never is. */
static int
i915_vkx_wait_node(
	struct i915_device *device)
{
	struct i915_completion nap;
	unsigned waited;

	/* A completion nobody signals: each wait on it simply lasts until its deadline. */
	drv_i915_completion_init(&nap, "i915 vkx");

	/* Looks for the published node until the budget is spent. */
	for (waited = 0U; waited < I915_VKX_WAIT_S * 20U; waited++) {
		/* The node is published once the GPU core holds it. */
		if (device->gpu != NULL && device->vk != NULL)
			return 0;

		(void)drv_i915_wait_for_completion(&nap, sched_ticks() + KERN_CLOCK_HZ / 20U);
	}

	/* The node never came. */
	return ETIMEDOUT;
}

/* Opens the session, makes the storage, the objects and the pipelines, and a command pool. */
static int
i915_vkx_setup(
	struct i915_vkx *x)
{
	void *private_session;
	int error;

	/* Opens a session of the node as a client's open would. */
	error = x->device->gpu_ops.open(x->device, &private_session);
	if (error != 0)
		return error;

	x->session = private_session;
	x->render = x->session->vk;
	if (x->render == NULL)
		return ENODEV;

	/* Makes the storage, bound into the session's address space. */
	error = i915_vkx_storage_create(x);
	if (error != 0)
		return error;

	/* Describes the objects over the storage and publishes them. */
	i915_vkx_objects_init(x);
	error = i915_vkx_objects_publish(x);
	if (error != 0)
		return error;

	/* Compiles the four pipelines. */
	error = i915_vkx_pipelines_prepare(x);
	if (error != 0)
		return error;

	/* Writes the vertices and the indices every draw step reads. */
	i915_vkx_vertices_write(x);
	i915_vkx_indices_write(x);

	/* Creates the command pool and its one command buffer through the wire. */
	error = i915_vkx_pool_create(x);
	if (error != 0)
		return error;

	/* Succeeded: every step can record and submit. */
	return 0;
}

/* Gives back everything the setup made, whatever it got to. */
static void
i915_vkx_teardown(
	struct i915_vkx *x)
{
	struct i915_device *device;
	int error;

	/* Destroys the command pool and its buffer through the wire. */
	if (x->pooled != 0) {
		x->used = 0U;
		x->overflow = 0;
		i915_vkx_put32(x, I915_VKX_OP_DESTROY_COMMAND_POOL);
		i915_vkx_put32(x, 1U);
		i915_vkx_put64(x, 0U);
		i915_vkx_put64(x, I915_VKX_ID_POOL);
		i915_vkx_put64(x, 0U);
		error = i915_vkx_execute(x, "destroy the command pool");
		if (error != 0)
			kern_logf("i915: vkx: the command pool was not destroyed: %d\n", error);
		x->pooled = 0;
	}

	/* Withdraws the published objects and releases the kernels. */
	if (x->published != 0)
		i915_vkx_objects_withdraw(x);
	drv_i915_gfx_pipeline_release(&x->color_pipeline);
	drv_i915_gfx_pipeline_release(&x->dynamic_pipeline);
	drv_i915_gfx_pipeline_release(&x->push_pipeline);
	drv_i915_gfx_pipeline_release(&x->tex_pipeline);

	/* Unbinds and destroys the storage. */
	device = x->device;
	if (x->storage != NULL) {
		mutex_lock(&device->mutex);

		drv_i915_gem_unbind_vm(x->storage);
		drv_i915_gem_destroy(&device->gem, x->storage);

		mutex_unlock(&device->mutex);

		x->storage = NULL;
	}

	/* Closes the session, which releases the executor's draw state with it. */
	if (x->session != NULL) {
		device->gpu_ops.close(device, x->session);
		x->session = NULL;
		x->render = NULL;
	}
}

/* Makes the storage object, bound into the session's address space. */
static int
i915_vkx_storage_create(
	struct i915_vkx *x)
{
	struct i915_device *device;
	int error;

	/* Creates the object and binds it, destroying it again when the binding fails. */
	device = x->device;
	mutex_lock(&device->mutex);

	error = drv_i915_gem_create(&device->gem, I915_VKX_STORAGE_BYTES, &x->storage);
	if (error == 0) {
		error = drv_i915_gem_bind_vm(x->session->vm, x->storage);
		if (error != 0) {
			drv_i915_gem_destroy(&device->gem, x->storage);
			x->storage = NULL;
		}
	} else {
		x->storage = NULL;
	}

	mutex_unlock(&device->mutex);

	/* Reports why the storage could not be made. */
	if (error != 0)
		return error;

	/* The steps write and read the storage through its CPU view. */
	x->cpu = x->storage->address;

	/* Succeeded: the storage is bound. */
	return 0;
}

/* Describes the memory, the target, the pass, the framebuffer and the buffers over the storage. */
static void
i915_vkx_objects_init(
	struct i915_vkx *x)
{
	/* The memory is the whole storage. */
	x->memory.vk = x->device->vk;
	x->memory.identity = I915_VKX_IDENTITY;
	x->memory.size = I915_VKX_STORAGE_BYTES;
	x->memory.object = x->storage;

	/* The target: a linear 64x64 RGBA8 image. */
	x->target.format = VK_FORMAT_R8G8B8A8_UNORM;
	x->target.width = I915_VKX_SIZE;
	x->target.height = I915_VKX_SIZE;
	x->target.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
	x->target.pitch = I915_VKX_SIZE * 4U;
	x->target.bytes = I915_VKX_SIZE * I915_VKX_SIZE * 4U;
	x->target.levels = 1U;
	x->target.memory = &x->memory;
	x->target.offset = I915_VKX_TARGET_OFFSET;
	x->view.image = &x->target;
	x->view.format = VK_FORMAT_R8G8B8A8_UNORM;
	x->view.level_count = 1U;

	/* One subpass writing the one colour attachment, cleared at the begin. */
	x->pass.attachment_count = 1U;
	x->pass.attachments[0].format = VK_FORMAT_R8G8B8A8_UNORM;
	x->pass.attachments[0].load_op = VK_ATTACHMENT_LOAD_OP_CLEAR;
	x->pass.color_attachment = 0U;
	x->pass.depth_attachment = VK_ATTACHMENT_UNUSED;
	x->framebuffer.width = I915_VKX_SIZE;
	x->framebuffer.height = I915_VKX_SIZE;
	x->framebuffer.view_count = 1U;
	x->framebuffer.views[0] = &x->view;

	/* The vertex buffer. */
	x->vertices.size = I915_VKX_VERTEX_BYTES;
	x->vertices.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
	x->vertices.memory = &x->memory;
	x->vertices.offset = I915_VKX_VERTEX_OFFSET;

	/* The index buffer. */
	x->indices.size = I915_VKX_INDEX_BYTES;
	x->indices.usage = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
	x->indices.memory = &x->memory;
	x->indices.offset = I915_VKX_INDEX_OFFSET;

	/* The source and the destination of the copies. */
	x->source.size = I915_VKX_COPY_BYTES;
	x->source.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
	x->source.memory = &x->memory;
	x->source.offset = I915_VKX_SOURCE_OFFSET;
	x->destination.size = I915_VKX_COPY_BYTES;
	x->destination.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
	x->destination.memory = &x->memory;
	x->destination.offset = I915_VKX_DESTINATION_OFFSET;

	/* The shader modules borrow the generated words, which the compiler only reads. */
	x->place.words = (uint32_t *)(uintptr_t)i915_vkx_place_vert;
	x->place.word_count = sizeof(i915_vkx_place_vert) / 4U;
	x->color.words = (uint32_t *)(uintptr_t)i915_vkx_color_frag;
	x->color.word_count = sizeof(i915_vkx_color_frag) / 4U;
	x->push.words = (uint32_t *)(uintptr_t)i915_vkx_push_frag;
	x->push.word_count = sizeof(i915_vkx_push_frag) / 4U;

	/* The colour pipeline, the one with dynamic viewport and scissor, and the pushed-colour one. */
	i915_vkx_pipeline_init(x, &x->color_pipeline, &x->color, 0);
	i915_vkx_pipeline_init(x, &x->dynamic_pipeline, &x->color, 1);
	i915_vkx_pipeline_init(x, &x->push_pipeline, &x->push, 0);

	/* The mip steps' images, views, samplers, sets and pipeline. */
	i915_vkx_mip_objects_init(x);
}

/* Publishes the objects the wire names under the scenario's identities. */
static int
i915_vkx_objects_publish(
	struct i915_vkx *x)
{
	struct i915_render_session *session;
	int error;

	/* Publishes the buffers, the pass, the framebuffer and the pipelines, stopping at the first refusal. */
	session = x->render;
	error = drv_i915_object_insert(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_VERTICES, &x->vertices);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_INDICES, &x->indices);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_SOURCE, &x->source);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_DESTINATION, &x->destination);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_RENDER_PASS, I915_VKX_ID_PASS, &x->pass);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_FRAMEBUFFER, I915_VKX_ID_FRAMEBUFFER, &x->framebuffer);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_COLOR_PIPELINE, &x->color_pipeline);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_DYNAMIC_PIPELINE, &x->dynamic_pipeline);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_PUSH_PIPELINE, &x->push_pipeline);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_IMAGE, I915_VKX_ID_TEXTURE, &x->texture);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_IMAGE, I915_VKX_ID_CHAIN, &x->chain);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_TEX_PIPELINE, &x->tex_pipeline);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_NEAREST, &x->nearest_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_FORCED, &x->forced_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_BIAS, &x->bias_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LATER, &x->later_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LINEAR, &x->linear_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LOD5, &x->lod5_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LOD5_HALF, &x->lod5_half_set);
	if (error == 0)
		error = drv_i915_object_insert(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LOD6, &x->lod6_set);

	/* The teardown withdraws whatever was published, all of it or part of it. */
	x->published = 1;

	/* Reports why an object could not be published. */
	if (error != 0)
		return error;

	/* Succeeded: the wire can name every object. */
	return 0;
}

/* Withdraws every object the scenario published; an identity never published is ignored. */
static void
i915_vkx_objects_withdraw(
	struct i915_vkx *x)
{
	struct i915_render_session *session;

	/* Removes each identity from the table. */
	session = x->render;
	drv_i915_object_remove(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_VERTICES);
	drv_i915_object_remove(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_INDICES);
	drv_i915_object_remove(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_SOURCE);
	drv_i915_object_remove(session, I915_VK_OBJ_BUFFER, I915_VKX_ID_DESTINATION);
	drv_i915_object_remove(session, I915_VK_OBJ_RENDER_PASS, I915_VKX_ID_PASS);
	drv_i915_object_remove(session, I915_VK_OBJ_FRAMEBUFFER, I915_VKX_ID_FRAMEBUFFER);
	drv_i915_object_remove(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_COLOR_PIPELINE);
	drv_i915_object_remove(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_DYNAMIC_PIPELINE);
	drv_i915_object_remove(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_PUSH_PIPELINE);
	drv_i915_object_remove(session, I915_VK_OBJ_IMAGE, I915_VKX_ID_TEXTURE);
	drv_i915_object_remove(session, I915_VK_OBJ_IMAGE, I915_VKX_ID_CHAIN);
	drv_i915_object_remove(session, I915_VK_OBJ_PIPELINE, I915_VKX_ID_TEX_PIPELINE);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_NEAREST);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_FORCED);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_BIAS);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LATER);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LINEAR);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LOD5);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LOD5_HALF);
	drv_i915_object_remove(session, I915_VK_OBJ_DESCRIPTOR_SET, I915_VKX_ID_SET_LOD6);
	x->published = 0;
}

/*
 * Describes one pipeline: the placing vertex shader with a fragment shader,
 * two vec4 attributes of one binding, a triangle list, no culling and no
 * depth; the whole target as viewport and scissor, or both dynamic.
 */
static void
i915_vkx_pipeline_init(
	struct i915_vkx *x,
	struct i915_gfx_pipeline *pipeline,
	struct i915_gfx_shader *fragment,
	int dynamic)
{
	/* The two stages. */
	kern_memset(pipeline, 0, sizeof(*pipeline));
	pipeline->vertex = &x->place;
	pipeline->fragment = fragment;

	/* Binding 0 of 32-byte vertices: the position at 0, the colour at 16. */
	pipeline->binding_count = 1U;
	pipeline->bindings[0].binding = 0U;
	pipeline->bindings[0].stride = I915_VKX_VERTEX_STRIDE;
	pipeline->attribute_count = 2U;
	pipeline->attributes[0].location = 0U;
	pipeline->attributes[0].binding = 0U;
	pipeline->attributes[0].format = VK_FORMAT_R32G32B32A32_SFLOAT;
	pipeline->attributes[0].offset = 0U;
	pipeline->attributes[1].location = 1U;
	pipeline->attributes[1].binding = 0U;
	pipeline->attributes[1].format = VK_FORMAT_R32G32B32A32_SFLOAT;
	pipeline->attributes[1].offset = 16U;

	/* A triangle list, drawn from both sides with no depth test. */
	pipeline->topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
	pipeline->cull_mode = VK_CULL_MODE_NONE;

	/* A dynamic pipeline leaves its viewport and scissor to the command buffer. */
	if (dynamic != 0) {
		pipeline->dynamic_viewport = 1;
		pipeline->dynamic_scissor = 1;
		return;
	}

	/* The whole target, depth range [0, 1]. */
	pipeline->viewport[0] = I915_VKX_F_0;
	pipeline->viewport[1] = I915_VKX_F_0;
	pipeline->viewport[2] = I915_VKX_F_64;
	pipeline->viewport[3] = I915_VKX_F_64;
	pipeline->viewport[4] = I915_VKX_F_0;
	pipeline->viewport[5] = I915_VKX_F_1;
	pipeline->scissor.extent.width = I915_VKX_SIZE;
	pipeline->scissor.extent.height = I915_VKX_SIZE;
}

/* Compiles the four pipelines' kernels with the executor's compiler. */
static int
i915_vkx_pipelines_prepare(
	struct i915_vkx *x)
{
	int error;

	/* The colour pipeline. */
	error = drv_i915_gfx_pipeline_prepare(x->render, &x->color_pipeline);
	if (error != 0)
		return error;

	/* The pipeline with dynamic viewport and scissor. */
	error = drv_i915_gfx_pipeline_prepare(x->render, &x->dynamic_pipeline);
	if (error != 0)
		return error;

	/* The pipeline whose fragment shader reads the pushed colour. */
	error = drv_i915_gfx_pipeline_prepare(x->render, &x->push_pipeline);
	if (error != 0)
		return error;

	/* The pipeline whose fragment shader samples the mipmapped texture. */
	error = drv_i915_gfx_pipeline_prepare(x->render, &x->tex_pipeline);
	if (error != 0)
		return error;

	/* Says what the pushed-colour pipeline reads, which the grid step relies on. */
	kern_logf("i915: vkx: push registers: vertex %u, fragment %u\n",
		  x->push_pipeline.vs_binary->push_regs,
		  x->push_pipeline.fs_binary->push_regs);

	/* Succeeded: every pipeline can draw. */
	return 0;
}

/*
 * Writes the vertex buffer: five quads of four vertices each.
 *
 *   0..3    the whole target, blue
 *   4..7    pixels 8..24 square, red
 *   8..11   pixels 40..56 square, green
 *   12..15  the whole target, white
 *   16..19  pixels 0..8 square (grid cell 0), white
 *
 * then, from vertex 32 on, seven textured quads whose colour carries the
 * texture coordinate, (0, 0) at the top left to (1, 1) at the bottom right:
 *
 *   32..35  pixels 0..32 square (the texture minified twice)
 *   36..39  columns 32..48, rows 0..16 (four times)
 *   40..43  columns 48..56, rows 0..8 (eight times)
 *   44..47  pixels 32..64 square (twice)
 *   48..51  columns 0..16, rows 32..48 (four times)
 *   52..55  columns 56..64, rows 0..8 (eight times)
 *   56..59  columns 56..64, rows 8..16 (eight times)
 */
static void
i915_vkx_vertices_write(
	struct i915_vkx *x)
{
	static const uint32_t blue[4] = { I915_VKX_F_0, I915_VKX_F_0, I915_VKX_F_1, I915_VKX_F_1 };
	static const uint32_t red[4] = { I915_VKX_F_1, I915_VKX_F_0, I915_VKX_F_0, I915_VKX_F_1 };
	static const uint32_t green[4] = { I915_VKX_F_0, I915_VKX_F_1, I915_VKX_F_0, I915_VKX_F_1 };
	static const uint32_t white[4] = { I915_VKX_F_1, I915_VKX_F_1, I915_VKX_F_1, I915_VKX_F_1 };
	uint32_t *words;

	/* Writes the five quads, eight words to a vertex. */
	words = (uint32_t *)(void *)(x->cpu + I915_VKX_VERTEX_OFFSET);
	i915_vkx_quad_write(words, 0U, 0U, 8U, 8U, blue);
	i915_vkx_quad_write(words + 32U, 1U, 1U, 3U, 3U, red);
	i915_vkx_quad_write(words + 64U, 5U, 5U, 7U, 7U, green);
	i915_vkx_quad_write(words + 96U, 0U, 0U, 8U, 8U, white);
	i915_vkx_quad_write(words + 128U, 0U, 0U, 1U, 1U, white);

	/* Writes the seven textured quads. */
	i915_vkx_texquad_write(words + I915_VKX_TEXQUAD_FIRST * 8U, 0U, 0U, 4U, 4U);
	i915_vkx_texquad_write(words + (I915_VKX_TEXQUAD_FIRST + 4U) * 8U, 4U, 0U, 6U, 2U);
	i915_vkx_texquad_write(words + (I915_VKX_TEXQUAD_FIRST + 8U) * 8U, 6U, 0U, 7U, 1U);
	i915_vkx_texquad_write(words + (I915_VKX_TEXQUAD_FIRST + 12U) * 8U, 4U, 4U, 8U, 8U);
	i915_vkx_texquad_write(words + (I915_VKX_TEXQUAD_FIRST + 16U) * 8U, 0U, 4U, 2U, 6U);
	i915_vkx_texquad_write(words + (I915_VKX_TEXQUAD_FIRST + 20U) * 8U, 7U, 0U, 8U, 1U);
	i915_vkx_texquad_write(words + (I915_VKX_TEXQUAD_FIRST + 24U) * 8U, 7U, 1U, 8U, 2U);

	/* Writes the vertices back to memory before the GPU reads them. */
	drv_i915_gt_clflush(words, I915_VKX_VERTEX_BYTES);
}

/* Writes the four vertices of an axis-aligned quad between NDC steps (left, top) and (right, bottom). */
static void
i915_vkx_quad_write(
	uint32_t *words,
	unsigned left,
	unsigned top,
	unsigned right,
	unsigned bottom,
	const uint32_t color[4])
{
	unsigned corner;
	unsigned x;
	unsigned y;

	/* Writes the corners in turn: top left, top right, bottom right, bottom left. */
	for (corner = 0U; corner < 4U; corner++) {
		/* The right corners are the second and third, the bottom ones the third and fourth. */
		x = left;
		if (corner == 1U || corner == 2U)
			x = right;
		y = top;
		if (corner >= 2U)
			y = bottom;

		/* The position (x, y, 0, 1), then the colour. */
		words[corner * 8U + 0U] = i915_vkx_ndc[x];
		words[corner * 8U + 1U] = i915_vkx_ndc[y];
		words[corner * 8U + 2U] = I915_VKX_F_0;
		words[corner * 8U + 3U] = I915_VKX_F_1;
		kern_memcpy(&words[corner * 8U + 4U], color, 4U * sizeof(color[0]));
	}
}

/*
 * Writes the index buffer.
 *
 * At byte 0, sixteen-bit indices: two indices nothing should read (the
 * bind starts at byte 4), two more the first index skips, then the two
 * quads 0 and 1 of a draw with vertex offset 4.  At byte 256, thirty-two-bit
 * indices: one quad, for draws that pick the quad with their vertex offset.
 */
static void
i915_vkx_indices_write(
	struct i915_vkx *x)
{
	static const uint16_t short_indices[16] = {
		0xffffU, 0xffffU,
		0xfff0U, 0xfff0U,
		0U, 1U, 2U, 0U, 2U, 3U,
		4U, 5U, 6U, 4U, 6U, 7U,
	};
	static const uint32_t long_indices[6] = {
		0U, 1U, 2U, 0U, 2U, 3U,
	};
	uint8_t *indices;

	/* Writes both kinds and flushes them before the GPU reads them. */
	indices = x->cpu + I915_VKX_INDEX_OFFSET;
	kern_memcpy(indices, short_indices, sizeof(short_indices));
	kern_memcpy(indices + I915_VKX_INDEX32_OFFSET, long_indices, sizeof(long_indices));
	drv_i915_gt_clflush(indices, I915_VKX_INDEX_BYTES);
}

/* Appends one little-endian word to the stream; a stream that would overflow is marked. */
static void
i915_vkx_put32(
	struct i915_vkx *x,
	uint32_t value)
{
	/* Refuses a word past the end of the stream. */
	if (x->used + 4U > sizeof(x->wire)) {
		x->overflow = 1;
		return;
	}

	kern_memcpy(x->wire + x->used, &value, 4U);
	x->used += 4U;
}

/* Appends one little-endian double word to the stream. */
static void
i915_vkx_put64(
	struct i915_vkx *x,
	uint64_t value)
{
	/* The low word first. */
	i915_vkx_put32(x, (uint32_t)value);
	i915_vkx_put32(x, (uint32_t)(value >> 32));
}

/* Appends the head of a recording: [opcode][no reply][command buffer]. */
static void
i915_vkx_record(
	struct i915_vkx *x,
	uint32_t opcode)
{
	/* A recording asks for no reply. */
	i915_vkx_put32(x, opcode);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, I915_VKX_ID_COMMAND_BUFFER);
}

/* Executes the stream built so far and empties it; the replies stay in the reply area. */
static int
i915_vkx_execute(
	struct i915_vkx *x,
	const char *what)
{
	int error;

	/* Refuses a stream that did not fit. */
	if (x->overflow != 0) {
		kern_logf("i915: vkx: %s: the stream does not fit %u bytes\n", what, I915_VKX_WIRE_BYTES);
		return ENOSPC;
	}

	/* Executes it into the reply area. */
	x->reply_bytes = sizeof(x->reply);
	error = drv_i915_render_execute(x->render, x->wire, x->used, x->reply, &x->reply_bytes);
	x->used = 0U;
	if (error != 0) {
		kern_logf("i915: vkx: %s: the executor refused the stream: %d\n", what, error);
		return error;
	}

	/* Succeeded: the replies are in the reply area. */
	return 0;
}

/* Reads one reply word; zero past the replies. */
static uint32_t
i915_vkx_reply32(
	const struct i915_vkx *x,
	size_t offset)
{
	uint32_t value;

	/* A word past the replies reads as zero. */
	if (offset + 4U > x->reply_bytes)
		return 0U;

	kern_memcpy(&value, x->reply + offset, 4U);

	/* Succeeded: the word at the offset. */
	return value;
}

/* Creates the command pool and allocates its one primary command buffer. */
static int
i915_vkx_pool_create(
	struct i915_vkx *x)
{
	uint32_t result;
	int error;

	/* vkCreateCommandPool: [85][reply][device][present][sType 39][no chain][flags][family][no allocator][present][identity]. */
	x->used = 0U;
	i915_vkx_put32(x, I915_VKX_OP_CREATE_COMMAND_POOL);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, 39U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, I915_VKX_ID_POOL);

	/* vkAllocateCommandBuffers: [88][reply][device][present][sType 40][no chain][pool][primary][1][1][identity]. */
	i915_vkx_put32(x, I915_VKX_OP_ALLOCATE_COMMAND_BUFFERS);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, 40U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, I915_VKX_ID_POOL);
	i915_vkx_put32(x, VK_COMMAND_BUFFER_LEVEL_PRIMARY);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, I915_VKX_ID_COMMAND_BUFFER);
	error = i915_vkx_execute(x, "create the command pool");
	if (error != 0)
		return error;

	/* The pool exists from here on, whatever the allocation answered. */
	x->pooled = 1;

	/* Refuses a pool the executor did not make: [85][result][present][identity]. */
	result = i915_vkx_reply32(x, 4U);
	if (result != VK_SUCCESS)
		return EIO;

	/* Refuses a buffer it did not allocate: [88][result][count][identity] behind the pool's reply. */
	result = i915_vkx_reply32(x, 24U + 4U);
	if (result != VK_SUCCESS)
		return EIO;

	/* Succeeded: the command buffer can record. */
	return 0;
}

/* Appends vkBeginCommandBuffer, which empties the recording: [90][reply][buffer][present][sType 42][no chain][flags][no inheritance]. */
static void
i915_vkx_begin(
	struct i915_vkx *x)
{
	/* The begin asks for its reply. */
	x->used = 0U;
	x->overflow = 0;
	i915_vkx_put32(x, I915_VKX_OP_BEGIN_COMMAND_BUFFER);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, I915_VKX_ID_COMMAND_BUFFER);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, 42U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, 0U);
}

/*
 * Appends vkCmdBeginRenderPass of the whole target, cleared to opaque black:
 * [present][sType 43][no chain][pass][framebuffer][area][present][1]
 * {[colour][tag][4][r g b a]}[inline].
 */
static void
i915_vkx_begin_pass(
	struct i915_vkx *x)
{
	/* The begin info. */
	i915_vkx_record(x, I915_VKX_OP_BEGIN_RENDER_PASS);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, 43U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, I915_VKX_ID_PASS);
	i915_vkx_put64(x, I915_VKX_ID_FRAMEBUFFER);

	/* The render area: the whole target. */
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, I915_VKX_SIZE);
	i915_vkx_put32(x, I915_VKX_SIZE);

	/* One colour clear value: opaque black. */
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, 4U);
	i915_vkx_put32(x, I915_VKX_F_0);
	i915_vkx_put32(x, I915_VKX_F_0);
	i915_vkx_put32(x, I915_VKX_F_0);
	i915_vkx_put32(x, I915_VKX_F_1);

	/* The subpass contents are inline. */
	i915_vkx_put32(x, VK_SUBPASS_CONTENTS_INLINE);
}

/* Appends vkCmdBindPipeline of a graphics pipeline. */
static void
i915_vkx_bind_pipeline(
	struct i915_vkx *x,
	uint64_t pipeline)
{
	/* [bind point][pipeline]. */
	i915_vkx_record(x, I915_VKX_OP_BIND_PIPELINE);
	i915_vkx_put32(x, VK_PIPELINE_BIND_POINT_GRAPHICS);
	i915_vkx_put64(x, pipeline);
}

/* Appends vkCmdBindVertexBuffers of the vertex buffer at binding 0, offset 0. */
static void
i915_vkx_bind_vertices(
	struct i915_vkx *x)
{
	/* [first][present][1]{buffer}[1]{offset}. */
	i915_vkx_record(x, I915_VKX_OP_BIND_VERTEX_BUFFERS);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, I915_VKX_ID_VERTICES);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, 0U);
}

/* Appends vkCmdBindIndexBuffer of the index buffer at an offset. */
static void
i915_vkx_bind_indices(
	struct i915_vkx *x,
	uint64_t offset,
	uint32_t type)
{
	/* [buffer][offset][index type]. */
	i915_vkx_record(x, I915_VKX_OP_BIND_INDEX_BUFFER);
	i915_vkx_put64(x, I915_VKX_ID_INDICES);
	i915_vkx_put64(x, offset);
	i915_vkx_put32(x, type);
}

/* Appends vkCmdDrawIndexed. */
static void
i915_vkx_draw_indexed(
	struct i915_vkx *x,
	uint32_t count,
	uint32_t instances,
	uint32_t first,
	int32_t vertex_offset,
	uint32_t first_instance)
{
	/* [indices][instances][first index][vertex offset][first instance]. */
	i915_vkx_record(x, I915_VKX_OP_DRAW_INDEXED);
	i915_vkx_put32(x, count);
	i915_vkx_put32(x, instances);
	i915_vkx_put32(x, first);
	i915_vkx_put32(x, (uint32_t)vertex_offset);
	i915_vkx_put32(x, first_instance);
}

/* Appends vkCmdSetViewport of viewport 0, in depth [0, 1]; the rectangle is given as float bits. */
static void
i915_vkx_set_viewport(
	struct i915_vkx *x,
	uint32_t left,
	uint32_t top,
	uint32_t width,
	uint32_t height)
{
	/* [first 0][1][1]{x y width height min max}. */
	i915_vkx_record(x, I915_VKX_OP_SET_VIEWPORT);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, left);
	i915_vkx_put32(x, top);
	i915_vkx_put32(x, width);
	i915_vkx_put32(x, height);
	i915_vkx_put32(x, I915_VKX_F_0);
	i915_vkx_put32(x, I915_VKX_F_1);
}

/* Appends vkCmdSetScissor of scissor 0. */
static void
i915_vkx_set_scissor(
	struct i915_vkx *x,
	uint32_t left,
	uint32_t top,
	uint32_t width,
	uint32_t height)
{
	/* [first 0][1][1]{x y width height}. */
	i915_vkx_record(x, I915_VKX_OP_SET_SCISSOR);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, left);
	i915_vkx_put32(x, top);
	i915_vkx_put32(x, width);
	i915_vkx_put32(x, height);
}

/* Appends vkCmdPushConstants of the whole 128-byte block to both stages. */
static void
i915_vkx_push(
	struct i915_vkx *x,
	const uint32_t *block)
{
	unsigned index;

	/* [layout][stages][offset][size][size]{bytes}. */
	i915_vkx_record(x, I915_VKX_OP_PUSH_CONSTANTS);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, I915_VKX_PUSH_BYTES);
	i915_vkx_put64(x, I915_VKX_PUSH_BYTES);
	for (index = 0U; index < I915_VKX_PUSH_BYTES / 4U; index++)
		i915_vkx_put32(x, block[index]);
}

/*
 * Appends the end and a submission of the command buffer, executes the
 * stream and checks the three replies: [90][result][91][result][18][result].
 */
static int
i915_vkx_finish(
	struct i915_vkx *x,
	const char *what)
{
	uint32_t begun;
	uint32_t ended;
	uint32_t submitted;
	int error;

	/* vkEndCommandBuffer: [91][reply][buffer]. */
	i915_vkx_put32(x, I915_VKX_OP_END_COMMAND_BUFFER);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, I915_VKX_ID_COMMAND_BUFFER);

	/* vkQueueSubmit of the one buffer, with no semaphores and no fence. */
	i915_vkx_put32(x, I915_VKX_OP_QUEUE_SUBMIT);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put32(x, 4U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, I915_VKX_ID_COMMAND_BUFFER);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, 0U);
	i915_vkx_put64(x, 0U);

	/* Runs the stream: the recording, then the submission to its end. */
	error = i915_vkx_execute(x, what);
	if (error != 0)
		return error;

	/* Takes the results of the begin, the end and the submission. */
	begun = i915_vkx_reply32(x, 4U);
	ended = i915_vkx_reply32(x, 12U);
	submitted = i915_vkx_reply32(x, 20U);

	/* Refuses a begin, an end or a submission that did not succeed. */
	if (begun != VK_SUCCESS ||
	    ended != VK_SUCCESS ||
	    submitted != VK_SUCCESS) {
		kern_logf("i915: vkx: %s: begin %d, end %d, submit %d\n",
			  what,
			  (int)begun,
			  (int)ended,
			  (int)submitted);
		return EIO;
	}

	/* Succeeded: the command buffer ran to its end. */
	return 0;
}

/* Expects the whole target in the clear colour, opaque black. */
static void
i915_vkx_expect_clear(
	struct i915_vkx *x)
{
	unsigned index;

	/* Every pixel is the clear colour. */
	for (index = 0U; index < I915_VKX_SIZE * I915_VKX_SIZE; index++)
		x->expected[index] = I915_VKX_BLACK;
}

/* Expects the pixels of columns left .. right - 1 and rows top .. bottom - 1 to hold a pixel value. */
static void
i915_vkx_expect_rect(
	struct i915_vkx *x,
	unsigned left,
	unsigned top,
	unsigned right,
	unsigned bottom,
	uint32_t pixel)
{
	unsigned column;
	unsigned row;

	/* Paints the rectangle into the expected image. */
	for (row = top; row < bottom; row++) {
		for (column = left; column < right; column++)
			x->expected[row * I915_VKX_SIZE + column] = pixel;
	}
}

/* Compares the target with the expected image; EIO when any pixel differs, with the first logged. */
static int
i915_vkx_compare_target(
	struct i915_vkx *x,
	const char *what)
{
	const uint32_t *pixels;
	unsigned differ;
	unsigned first;
	unsigned index;

	/* Reads the target through the CPU view, past any line the CPU still caches. */
	pixels = (const uint32_t *)(const void *)(x->cpu + I915_VKX_TARGET_OFFSET);
	drv_i915_gt_clflush(pixels, I915_VKX_SIZE * I915_VKX_SIZE * 4U);

	/* Counts the pixels that differ and notes the first. */
	differ = 0U;
	first = 0U;
	for (index = 0U; index < I915_VKX_SIZE * I915_VKX_SIZE; index++) {
		if (pixels[index] != x->expected[index]) {
			if (differ == 0U)
				first = index;
			differ++;
		}
	}

	/* Says where the image differs. */
	if (differ != 0U) {
		kern_logf("i915: vkx: %s: %u of %u pixels differ; first at (%u,%u): 0x%08x, expected 0x%08x\n",
			  what,
			  differ,
			  I915_VKX_SIZE * I915_VKX_SIZE,
			  first % I915_VKX_SIZE,
			  first / I915_VKX_SIZE,
			  pixels[first],
			  x->expected[first]);
		return EIO;
	}

	/* Succeeded: the target is exactly the expected image. */
	return 0;
}

/* Logs a step's verdict and counts it. */
static void
i915_vkx_verdict(
	struct i915_vkx *x,
	const char *what,
	int error)
{
	/* A step fails with the error that stopped it. */
	if (error != 0) {
		x->failed++;
		kern_logf("i915: vkx: VKX-%s FAIL (%d)\n", what, error);
		return;
	}

	x->passed++;
	kern_logf("i915: vkx: VKX-%s PASS\n", what);
}

/*
 * INDEX16: one indexed draw of twelve 16-bit indices, bound at byte 4, from
 * index 2, with vertex offset 4, draws the red and the green squares.  A
 * bind offset, first index or vertex offset that were ignored would draw
 * the junk indices or the blue quad that covers the target.
 */
static void
i915_vkx_step_index16(
	struct i915_vkx *x)
{
	int error;

	/* Records the pass, the colour pipeline, the buffers and the draw. */
	i915_vkx_begin(x);
	i915_vkx_begin_pass(x);
	i915_vkx_bind_pipeline(x, I915_VKX_ID_COLOR_PIPELINE);
	i915_vkx_bind_vertices(x);
	i915_vkx_bind_indices(x, 4U, VK_INDEX_TYPE_UINT16);
	i915_vkx_draw_indexed(x, 12U, 1U, 2U, 4, 0U);
	i915_vkx_record(x, I915_VKX_OP_END_RENDER_PASS);

	/* Runs it and compares the target with the two squares on black. */
	error = i915_vkx_finish(x, "INDEX16");
	if (error == 0) {
		i915_vkx_expect_clear(x);
		i915_vkx_expect_rect(x, 8U, 8U, 24U, 24U, I915_VKX_RED);
		i915_vkx_expect_rect(x, 40U, 40U, 56U, 56U, I915_VKX_GREEN);
		error = i915_vkx_compare_target(x, "INDEX16");
	}

	i915_vkx_verdict(x, "INDEX16", error);
}

/*
 * INDEX32: two indexed draws of the same six 32-bit indices pick their quad
 * with the vertex offset: 8 for the green square, then 4, two instances,
 * for the red one.
 */
static void
i915_vkx_step_index32(
	struct i915_vkx *x)
{
	int error;

	/* Records the pass, the colour pipeline, the buffers and the two draws. */
	i915_vkx_begin(x);
	i915_vkx_begin_pass(x);
	i915_vkx_bind_pipeline(x, I915_VKX_ID_COLOR_PIPELINE);
	i915_vkx_bind_vertices(x);
	i915_vkx_bind_indices(x, I915_VKX_INDEX32_OFFSET, VK_INDEX_TYPE_UINT32);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, 8, 0U);
	i915_vkx_draw_indexed(x, 6U, 2U, 0U, 4, 0U);
	i915_vkx_record(x, I915_VKX_OP_END_RENDER_PASS);

	/* Runs it and compares the target with the two squares on black. */
	error = i915_vkx_finish(x, "INDEX32");
	if (error == 0) {
		i915_vkx_expect_clear(x);
		i915_vkx_expect_rect(x, 8U, 8U, 24U, 24U, I915_VKX_RED);
		i915_vkx_expect_rect(x, 40U, 40U, 56U, 56U, I915_VKX_GREEN);
		error = i915_vkx_compare_target(x, "INDEX32");
	}

	i915_vkx_verdict(x, "INDEX32", error);
}

/*
 * VIEWPORT: a pipeline with dynamic viewport and scissor draws a quad that
 * covers its whole viewport twice.  The blue one in viewport (16, 8) 32x16
 * cut by scissor (0, 0) 40x64 covers columns 16..40, rows 8..24; the white
 * one in viewport (0, 40) 64x24 cut by scissor (8, 48) 16x8 covers columns
 * 8..24, rows 48..56.
 */
static void
i915_vkx_step_viewport(
	struct i915_vkx *x)
{
	int error;

	/* Records the pass, the dynamic pipeline and the buffers. */
	i915_vkx_begin(x);
	i915_vkx_begin_pass(x);
	i915_vkx_bind_pipeline(x, I915_VKX_ID_DYNAMIC_PIPELINE);
	i915_vkx_bind_vertices(x);
	i915_vkx_bind_indices(x, I915_VKX_INDEX32_OFFSET, VK_INDEX_TYPE_UINT32);

	/* The blue quad in the first viewport and scissor. */
	i915_vkx_set_viewport(x, I915_VKX_F_16, I915_VKX_F_8, I915_VKX_F_32, I915_VKX_F_16);
	i915_vkx_set_scissor(x, 0U, 0U, 40U, I915_VKX_SIZE);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, 0, 0U);

	/* The white quad in the second. */
	i915_vkx_set_viewport(x, I915_VKX_F_0, I915_VKX_F_40, I915_VKX_F_64, I915_VKX_F_24);
	i915_vkx_set_scissor(x, 8U, 48U, 16U, 8U);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, 12, 0U);
	i915_vkx_record(x, I915_VKX_OP_END_RENDER_PASS);

	/* Runs it and compares the target with the two clipped rectangles on black. */
	error = i915_vkx_finish(x, "VIEWPORT");
	if (error == 0) {
		i915_vkx_expect_clear(x);
		i915_vkx_expect_rect(x, 16U, 8U, 40U, 24U, I915_VKX_BLUE);
		i915_vkx_expect_rect(x, 8U, 48U, 24U, 56U, I915_VKX_WHITE);
		error = i915_vkx_compare_target(x, "VIEWPORT");
	}

	i915_vkx_verdict(x, "VIEWPORT", error);
}

/*
 * COPY: one vkCmdCopyBuffer of four regions, from 16 bytes to more than
 * four full rows of the copy, at offsets that are multiples of four but not
 * of the row; the destination must equal, byte for byte, the model the CPU
 * makes of it.
 */
static void
i915_vkx_step_copy(
	struct i915_vkx *x)
{
	static const uint64_t regions[4][3] = {
		{ 0U, 0U, 16U },
		{ 64U, 4100U, 3U * 16384U + 20U },
		{ 70000U, 60000U, 4U },
		{ 96000U, 90000U, 4U * 16384U + 4U },
	};
	uint32_t *source;
	uint8_t *destination;
	unsigned differ;
	unsigned first;
	unsigned index;
	int error;

	/* Fills the source with a pattern and the destination and its model with 0xcd. */
	source = (uint32_t *)(void *)(x->cpu + I915_VKX_SOURCE_OFFSET);
	destination = x->cpu + I915_VKX_DESTINATION_OFFSET;
	for (index = 0U; index < I915_VKX_COPY_BYTES / 4U; index++)
		source[index] = index * 0x9e3779b1U + 0x12345U;
	kern_memset(destination, 0xcd, I915_VKX_COPY_BYTES);
	kern_memset(x->model, 0xcd, I915_VKX_COPY_BYTES);
	drv_i915_gt_clflush(source, I915_VKX_COPY_BYTES);
	drv_i915_gt_clflush(destination, I915_VKX_COPY_BYTES);

	/* Records the copy: [src][dst][4][4]{src offset, dst offset, size}. */
	i915_vkx_begin(x);
	i915_vkx_record(x, I915_VKX_OP_COPY_BUFFER);
	i915_vkx_put64(x, I915_VKX_ID_SOURCE);
	i915_vkx_put64(x, I915_VKX_ID_DESTINATION);
	i915_vkx_put32(x, 4U);
	i915_vkx_put64(x, 4U);
	for (index = 0U; index < 4U; index++) {
		i915_vkx_put64(x, regions[index][0]);
		i915_vkx_put64(x, regions[index][1]);
		i915_vkx_put64(x, regions[index][2]);
	}

	/* Runs it. */
	error = i915_vkx_finish(x, "COPY");
	if (error != 0) {
		i915_vkx_verdict(x, "COPY", error);
		return;
	}

	/* Makes the model: every region copied on the CPU. */
	for (index = 0U; index < 4U; index++) {
		kern_memcpy(x->model + regions[index][1],
		       (const uint8_t *)source + regions[index][0],
		       (size_t)regions[index][2]);
	}

	/* Compares the destination with the model byte for byte. */
	drv_i915_gt_clflush(destination, I915_VKX_COPY_BYTES);
	differ = 0U;
	first = 0U;
	for (index = 0U; index < I915_VKX_COPY_BYTES; index++) {
		if (destination[index] != x->model[index]) {
			if (differ == 0U)
				first = index;
			differ++;
		}
	}

	/* Says where the bytes differ. */
	if (differ != 0U) {
		kern_logf("i915: vkx: COPY: %u of %u bytes differ; first at %u: 0x%02x, expected 0x%02x\n",
			  differ,
			  I915_VKX_COPY_BYTES,
			  first,
			  destination[first],
			  x->model[first]);
		error = EIO;
	}

	i915_vkx_verdict(x, "COPY", error);
}

/*
 * GRID: 64 cells of 8x8 pixels, each one push of the whole block (the
 * cell's offset for the vertex stage at byte 0, its colour for the
 * fragment stage at byte 112) and one indexed draw of the white cell quad:
 * 134 operations in one command buffer.  Cell c takes red, green and blue
 * levels c % 4, c / 4 % 4 and c / 16 of 0, 0.25, 0.75 and 1.
 */
static void
i915_vkx_step_grid(
	struct i915_vkx *x)
{
	uint32_t block[I915_VKX_PUSH_BYTES / 4U];
	uint32_t pixel;
	unsigned cell;
	unsigned column;
	unsigned row;
	int error;

	/* Records the pass, the pushed-colour pipeline and the buffers. */
	i915_vkx_begin(x);
	i915_vkx_begin_pass(x);
	i915_vkx_bind_pipeline(x, I915_VKX_ID_PUSH_PIPELINE);
	i915_vkx_bind_vertices(x);
	i915_vkx_bind_indices(x, I915_VKX_INDEX32_OFFSET, VK_INDEX_TYPE_UINT32);

	/* Records one push and one draw for each cell. */
	kern_memset(block, 0, sizeof(block));
	for (cell = 0U; cell < 64U; cell++) {
		/* The cell's offset: its column and row in steps of 0.25. */
		column = cell % 8U;
		row = cell / 8U;
		block[0] = i915_vkx_steps[column];
		block[1] = i915_vkx_steps[row];

		/* The cell's colour at byte 112, opaque. */
		block[I915_VKX_PUSH_COLOR / 4U + 0U] = i915_vkx_level_bits[cell % 4U];
		block[I915_VKX_PUSH_COLOR / 4U + 1U] = i915_vkx_level_bits[(cell / 4U) % 4U];
		block[I915_VKX_PUSH_COLOR / 4U + 2U] = i915_vkx_level_bits[cell / 16U];
		block[I915_VKX_PUSH_COLOR / 4U + 3U] = I915_VKX_F_1;

		i915_vkx_push(x, block);
		i915_vkx_draw_indexed(x, 6U, 1U, 0U, 16, 0U);
	}

	i915_vkx_record(x, I915_VKX_OP_END_RENDER_PASS);

	/* Runs it and compares the target with the 64 coloured cells. */
	error = i915_vkx_finish(x, "GRID");
	if (error == 0) {
		i915_vkx_expect_clear(x);
		for (cell = 0U; cell < 64U; cell++) {
			/* The cell's pixel: red, green and blue bytes of its levels, opaque. */
			pixel = i915_vkx_level_bytes[cell % 4U] |
			    (i915_vkx_level_bytes[(cell / 4U) % 4U] << 8) |
			    (i915_vkx_level_bytes[cell / 16U] << 16) |
			    0xff000000U;
			column = cell % 8U;
			row = cell / 8U;
			i915_vkx_expect_rect(x, column * 8U, row * 8U, column * 8U + 8U, row * 8U + 8U, pixel);
		}

		error = i915_vkx_compare_target(x, "GRID");
	}

	i915_vkx_verdict(x, "GRID", error);
}

/*
 * Describes the mip steps' objects: the texture and the chain, 64x64 RGBA8
 * images of all 7 levels laid out as the executor lays out a created image;
 * the texturing pipeline; a view of every level and one of level 2 on; the
 * seven samplers and the eight sets that pair a view with a sampler.
 */
static void
i915_vkx_mip_objects_init(
	struct i915_vkx *x)
{
	/* The texture the draws sample, laid out by the executor's own layout. */
	x->texture.format = VK_FORMAT_R8G8B8A8_UNORM;
	x->texture.width = I915_VKX_MIP_SIZE;
	x->texture.height = I915_VKX_MIP_SIZE;
	x->texture.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
	x->texture.levels = I915_VKX_MIP_LEVELS;
	(void)drv_i915_gfx_image_layout(&x->texture);
	x->texture.memory = &x->memory;
	x->texture.offset = I915_VKX_TEXTURE_OFFSET;

	/* The chain the blits fill, level after level, laid out the same way. */
	x->chain.format = VK_FORMAT_R8G8B8A8_UNORM;
	x->chain.width = I915_VKX_MIP_SIZE;
	x->chain.height = I915_VKX_MIP_SIZE;
	x->chain.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
	x->chain.levels = I915_VKX_MIP_LEVELS;
	(void)drv_i915_gfx_image_layout(&x->chain);
	x->chain.memory = &x->memory;
	x->chain.offset = I915_VKX_CHAIN_OFFSET;

	/* The texturing shader borrows the generated words; its pipeline places vertices as the others do. */
	x->tex.words = (uint32_t *)(uintptr_t)i915_vkx_tex_frag;
	x->tex.word_count = sizeof(i915_vkx_tex_frag) / 4U;
	i915_vkx_pipeline_init(x, &x->tex_pipeline, &x->tex, 0);

	/* A view of every level of the texture. */
	x->texture_view.image = &x->texture;
	x->texture_view.format = VK_FORMAT_R8G8B8A8_UNORM;
	x->texture_view.base_level = 0U;
	x->texture_view.level_count = I915_VKX_MIP_LEVELS;

	/* A view of level 2 on, whose first level is 16x16. */
	x->later_view.image = &x->texture;
	x->later_view.format = VK_FORMAT_R8G8B8A8_UNORM;
	x->later_view.base_level = 2U;
	x->later_view.level_count = I915_VKX_MIP_LEVELS - 2U;

	/* The nearest level over the whole LOD range; LOD fixed at 1.5 and blended; the nearest level with bias 2. */
	i915_vkx_mip_sampler_init(&x->nearest_sampler, VK_SAMPLER_MIPMAP_MODE_NEAREST, I915_VKX_F_0, I915_VKX_F_0, I915_VKX_F_16);
	i915_vkx_mip_sampler_init(&x->forced_sampler, VK_SAMPLER_MIPMAP_MODE_LINEAR, I915_VKX_F_0, I915_VKX_F_ONE_AND_HALF, I915_VKX_F_ONE_AND_HALF);
	i915_vkx_mip_sampler_init(&x->bias_sampler, VK_SAMPLER_MIPMAP_MODE_NEAREST, I915_VKX_F_2, I915_VKX_F_0, I915_VKX_F_16);

	/* Linear blending over the whole LOD range; the least LOD held at 5 (nearest), 5.5 (blended) and 6 (nearest). */
	i915_vkx_mip_sampler_init(&x->linear_sampler, VK_SAMPLER_MIPMAP_MODE_LINEAR, I915_VKX_F_0, I915_VKX_F_0, I915_VKX_F_16);
	i915_vkx_mip_sampler_init(&x->lod5_sampler, VK_SAMPLER_MIPMAP_MODE_NEAREST, I915_VKX_F_0, I915_VKX_F_5, I915_VKX_F_16);
	i915_vkx_mip_sampler_init(&x->lod5_half_sampler, VK_SAMPLER_MIPMAP_MODE_LINEAR, I915_VKX_F_0, I915_VKX_F_FIVE_AND_HALF, I915_VKX_F_16);
	i915_vkx_mip_sampler_init(&x->lod6_sampler, VK_SAMPLER_MIPMAP_MODE_NEAREST, I915_VKX_F_0, I915_VKX_F_6, I915_VKX_F_16);

	/* The sets: binding 0 is the one sampled image of the texturing shader. */
	x->nearest_set.slots[0].view = &x->texture_view;
	x->nearest_set.slots[0].sampler = &x->nearest_sampler;
	x->forced_set.slots[0].view = &x->texture_view;
	x->forced_set.slots[0].sampler = &x->forced_sampler;
	x->bias_set.slots[0].view = &x->texture_view;
	x->bias_set.slots[0].sampler = &x->bias_sampler;
	x->later_set.slots[0].view = &x->later_view;
	x->later_set.slots[0].sampler = &x->nearest_sampler;
	x->linear_set.slots[0].view = &x->texture_view;
	x->linear_set.slots[0].sampler = &x->linear_sampler;
	x->lod5_set.slots[0].view = &x->texture_view;
	x->lod5_set.slots[0].sampler = &x->lod5_sampler;
	x->lod5_half_set.slots[0].view = &x->texture_view;
	x->lod5_half_set.slots[0].sampler = &x->lod5_half_sampler;
	x->lod6_set.slots[0].view = &x->texture_view;
	x->lod6_set.slots[0].sampler = &x->lod6_sampler;
}

/* Describes a sampler with linear filters that clamps to the edge, with a mipmap mode, a bias and a LOD range as float bits. */
static void
i915_vkx_mip_sampler_init(
	struct i915_gfx_sampler *sampler,
	uint32_t mipmap_mode,
	uint32_t lod_bias,
	uint32_t min_lod,
	uint32_t max_lod)
{
	/* Linear within a level, clamped to the edge. */
	kern_memset(sampler, 0, sizeof(*sampler));
	sampler->mag_filter = VK_FILTER_LINEAR;
	sampler->min_filter = VK_FILTER_LINEAR;
	sampler->address_u = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
	sampler->address_v = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;

	/* How the level is chosen. */
	sampler->mipmap_mode = mipmap_mode;
	sampler->lod_bias = lod_bias;
	sampler->min_lod = min_lod;
	sampler->max_lod = max_lod;
}

/*
 * Writes the four vertices of an axis-aligned quad between NDC steps
 * (left, top) and (right, bottom) whose colour is the texture coordinate:
 * (0, 0) at the top left, (1, 1) at the bottom right.
 */
static void
i915_vkx_texquad_write(
	uint32_t *words,
	unsigned left,
	unsigned top,
	unsigned right,
	unsigned bottom)
{
	unsigned corner;
	unsigned x;
	unsigned y;
	uint32_t u;
	uint32_t v;

	/* Writes the corners in turn: top left, top right, bottom right, bottom left. */
	for (corner = 0U; corner < 4U; corner++) {
		/* The right corners are the second and third, the bottom ones the third and fourth. */
		x = left;
		u = I915_VKX_F_0;
		if (corner == 1U || corner == 2U) {
			x = right;
			u = I915_VKX_F_1;
		}
		y = top;
		v = I915_VKX_F_0;
		if (corner >= 2U) {
			y = bottom;
			v = I915_VKX_F_1;
		}

		/* The position (x, y, 0, 1), then the coordinate (u, v, 0, 1). */
		words[corner * 8U + 0U] = i915_vkx_ndc[x];
		words[corner * 8U + 1U] = i915_vkx_ndc[y];
		words[corner * 8U + 2U] = I915_VKX_F_0;
		words[corner * 8U + 3U] = I915_VKX_F_1;
		words[corner * 8U + 4U] = u;
		words[corner * 8U + 5U] = v;
		words[corner * 8U + 6U] = I915_VKX_F_0;
		words[corner * 8U + 7U] = I915_VKX_F_1;
	}
}

/* Reports the width and the height of a level of the mip steps' square images. */
static uint32_t
i915_vkx_level_extent(
	uint32_t level)
{
	uint32_t extent;

	/* Halves the side once for each level, down to one texel. */
	extent = I915_VKX_MIP_SIZE >> level;
	if (extent == 0U)
		extent = 1U;

	/* Succeeded: the side of the level. */
	return extent;
}

/* Appends a VkImageSubresourceLayers of one colour level: [aspect][level][first layer][layers]. */
static void
i915_vkx_subresource(
	struct i915_vkx *x,
	uint32_t level)
{
	/* The colour aspect of the level's one layer. */
	i915_vkx_put32(x, VK_IMAGE_ASPECT_COLOR_BIT);
	i915_vkx_put32(x, level);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 1U);
}

/*
 * Appends a vkCmdCopyBufferToImage from the source buffer, or a
 * vkCmdCopyImageToBuffer into the destination buffer, of one whole level
 * packed at `buffer_offset`: [buffer][image][layout] or [image][layout]
 * [buffer], then [1][1]{offset, row length, image height, level, image
 * offset, extent}.
 */
static void
i915_vkx_level_copy(
	struct i915_vkx *x,
	uint32_t opcode,
	uint64_t image,
	uint32_t level,
	uint64_t buffer_offset)
{
	uint32_t extent;

	/* The buffer and the image in the direction's order. */
	i915_vkx_record(x, opcode);
	if (opcode == I915_VKX_OP_COPY_BUFFER_TO_IMAGE) {
		i915_vkx_put64(x, I915_VKX_ID_SOURCE);
		i915_vkx_put64(x, image);
		i915_vkx_put32(x, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);
	} else {
		i915_vkx_put64(x, image);
		i915_vkx_put32(x, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);
		i915_vkx_put64(x, I915_VKX_ID_DESTINATION);
	}

	/* One region: the buffer offset, packed rows, the level at (0, 0), the level's extent. */
	extent = i915_vkx_level_extent(level);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, buffer_offset);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_subresource(x, level);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, extent);
	i915_vkx_put32(x, extent);
	i915_vkx_put32(x, 1U);
}

/*
 * Appends a vkCmdBlitImage of the whole of level - 1 into the whole of
 * `level` of the same image with a linear filter: [src][layout][dst]
 * [layout][1][1]{src level, [2] corners, dst level, [2] corners}[filter].
 */
static void
i915_vkx_level_blit(
	struct i915_vkx *x,
	uint64_t image,
	uint32_t level)
{
	/* The image twice, as source and destination. */
	i915_vkx_record(x, I915_VKX_OP_BLIT_IMAGE);
	i915_vkx_put64(x, image);
	i915_vkx_put32(x, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);
	i915_vkx_put64(x, image);
	i915_vkx_put32(x, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);

	/* The source: the level above, from (0, 0, 0) to its far corner. */
	i915_vkx_subresource(x, level - 1U);
	i915_vkx_put64(x, 2U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, i915_vkx_level_extent(level - 1U));
	i915_vkx_put32(x, i915_vkx_level_extent(level - 1U));
	i915_vkx_put32(x, 1U);

	/* The destination: the level, from (0, 0, 0) to its far corner. */
	i915_vkx_subresource(x, level);
	i915_vkx_put64(x, 2U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, i915_vkx_level_extent(level));
	i915_vkx_put32(x, i915_vkx_level_extent(level));
	i915_vkx_put32(x, 1U);

	/* The filter. */
	i915_vkx_put32(x, VK_FILTER_LINEAR);
}

/* Appends vkCmdBindDescriptorSets of one set as set 0: [bind point][layout][first][1][1]{set}[0][0]. */
static void
i915_vkx_bind_set(
	struct i915_vkx *x,
	uint64_t set)
{
	/* The graphics bind point, no layout, set 0, one set, no dynamic offsets. */
	i915_vkx_record(x, I915_VKX_OP_BIND_DESCRIPTOR_SETS);
	i915_vkx_put32(x, VK_PIPELINE_BIND_POINT_GRAPHICS);
	i915_vkx_put64(x, 0U);
	i915_vkx_put32(x, 0U);
	i915_vkx_put32(x, 1U);
	i915_vkx_put64(x, 1U);
	i915_vkx_put64(x, set);
	i915_vkx_put32(x, 0U);
	i915_vkx_put64(x, 0U);
}

/*
 * Fills each level of the source buffer's staging area with the level's
 * colour and appends the per-level copies that upload them into the
 * texture, level 0 first.
 */
static void
i915_vkx_texture_fill(
	struct i915_vkx *x)
{
	uint32_t *staging;
	uint64_t offset;
	uint32_t level;
	uint32_t texels;
	uint32_t index;

	/* Stages every level, packed one after another, and uploads it. */
	staging = (uint32_t *)(void *)(x->cpu + I915_VKX_SOURCE_OFFSET);
	offset = 0U;
	for (level = 0U; level < I915_VKX_MIP_LEVELS; level++) {
		/* Fills the level's texels with its colour. */
		texels = i915_vkx_level_extent(level) * i915_vkx_level_extent(level);
		for (index = 0U; index < texels; index++)
			staging[offset / 4U + index] = i915_vkx_level_colors[level];

		/* Uploads the level from where it is staged. */
		i915_vkx_level_copy(x, I915_VKX_OP_COPY_BUFFER_TO_IMAGE, I915_VKX_ID_TEXTURE, level, offset);
		offset += (uint64_t)texels * 4U;
	}

	/* Writes the staged levels back to memory before the GPU reads them. */
	drv_i915_gt_clflush(staging, (size_t)offset);
}

/* Reports the pixel halfway between two pixels, channel by channel, rounded half up. */
static uint32_t
i915_vkx_blend(
	uint32_t first,
	uint32_t second)
{
	uint32_t pixel;
	uint32_t shift;
	uint32_t channel;

	/* Averages each of the four bytes. */
	pixel = 0U;
	for (shift = 0U; shift < 32U; shift += 8U) {
		channel = (((first >> shift) & 0xffU) + ((second >> shift) & 0xffU) + 1U) / 2U;
		pixel |= channel << shift;
	}

	/* Succeeded: the blended pixel. */
	return pixel;
}

/* Decides whether every byte of a pixel is within the mip tolerance of the expected pixel's byte. */
static int
i915_vkx_near(
	uint32_t pixel,
	uint32_t expected)
{
	uint32_t shift;
	uint32_t have;
	uint32_t want;

	/* Compares each of the four bytes. */
	for (shift = 0U; shift < 32U; shift += 8U) {
		have = (pixel >> shift) & 0xffU;
		want = (expected >> shift) & 0xffU;
		if (have > want + I915_VKX_MIP_TOLERANCE)
			return 0;
		if (want > have + I915_VKX_MIP_TOLERANCE)
			return 0;
	}

	/* Succeeded: every byte is near. */
	return 1;
}

/* Compares the target with the expected image, each byte within the mip tolerance; EIO with the first difference logged. */
static int
i915_vkx_compare_near(
	struct i915_vkx *x,
	const char *what)
{
	const uint32_t *pixels;
	unsigned differ;
	unsigned first;
	unsigned index;
	int near;

	/* Reads the target through the CPU view, past any line the CPU still caches. */
	pixels = (const uint32_t *)(const void *)(x->cpu + I915_VKX_TARGET_OFFSET);
	drv_i915_gt_clflush(pixels, I915_VKX_SIZE * I915_VKX_SIZE * 4U);

	/* Counts the pixels that are not near and notes the first. */
	differ = 0U;
	first = 0U;
	for (index = 0U; index < I915_VKX_SIZE * I915_VKX_SIZE; index++) {
		near = i915_vkx_near(pixels[index], x->expected[index]);
		if (near == 0) {
			if (differ == 0U)
				first = index;
			differ++;
		}
	}

	/* Says where the image differs. */
	if (differ != 0U) {
		kern_logf("i915: vkx: %s: %u of %u pixels differ; first at (%u,%u): 0x%08x, expected 0x%08x\n",
			  what,
			  differ,
			  I915_VKX_SIZE * I915_VKX_SIZE,
			  first % I915_VKX_SIZE,
			  first / I915_VKX_SIZE,
			  pixels[first],
			  x->expected[first]);
		return EIO;
	}

	/* Succeeded: every pixel is near its expected value. */
	return 0;
}

/*
 * MIP-NEAREST: the texture's seven levels are uploaded by per-level copies,
 * each in its own colour, and sampled with the nearest level through quads
 * of 32, 16 and 8 pixels: the texture minified two, four and eight times
 * shows levels 1, 2 and 3.
 */
static void
i915_vkx_step_mip_nearest(
	struct i915_vkx *x)
{
	int error;

	/* Records the upload, then the pass with the three quads sampled nearest. */
	i915_vkx_begin(x);
	i915_vkx_texture_fill(x);
	i915_vkx_begin_pass(x);
	i915_vkx_bind_pipeline(x, I915_VKX_ID_TEX_PIPELINE);
	i915_vkx_bind_vertices(x);
	i915_vkx_bind_indices(x, I915_VKX_INDEX32_OFFSET, VK_INDEX_TYPE_UINT32);
	i915_vkx_bind_set(x, I915_VKX_ID_SET_NEAREST);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST, 0U);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 4, 0U);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 8, 0U);
	i915_vkx_record(x, I915_VKX_OP_END_RENDER_PASS);

	/* Runs it and compares the target with the three quads in the colours of levels 1, 2 and 3. */
	error = i915_vkx_finish(x, "MIP-NEAREST");
	if (error == 0) {
		i915_vkx_expect_clear(x);
		i915_vkx_expect_rect(x, 0U, 0U, 32U, 32U, i915_vkx_level_colors[1]);
		i915_vkx_expect_rect(x, 32U, 0U, 48U, 16U, i915_vkx_level_colors[2]);
		i915_vkx_expect_rect(x, 48U, 0U, 56U, 8U, i915_vkx_level_colors[3]);
		error = i915_vkx_compare_near(x, "MIP-NEAREST");
	}

	i915_vkx_verdict(x, "MIP-NEAREST", error);
}

/*
 * MIP-LINEAR: a sampler whose LOD range is [1.5, 1.5] blends levels 1 and
 * 2 half and half with the linear mip filter; a sampler with LOD bias 2
 * reads level 3 through a quad that shows level 1 unbiased; a view of level
 * 2 on reads its first level (the texture's level 2) through a quad of that
 * level's size.  The linear mip filter over the whole LOD range shows level
 * 2 alone through a quad minified exactly four times; a least LOD of 5 and
 * of 6 shows the two smallest levels (2x2 and 1x1) through quads that are
 * minified only eight times, and a least LOD of 5.5 blends them.
 */
static void
i915_vkx_step_mip_linear(
	struct i915_vkx *x)
{
	int error;

	/* Records the upload, then the pass with one quad for each sampler and view. */
	i915_vkx_begin(x);
	i915_vkx_texture_fill(x);
	i915_vkx_begin_pass(x);
	i915_vkx_bind_pipeline(x, I915_VKX_ID_TEX_PIPELINE);
	i915_vkx_bind_vertices(x);
	i915_vkx_bind_indices(x, I915_VKX_INDEX32_OFFSET, VK_INDEX_TYPE_UINT32);

	/* The 32-pixel quad at the top left with the LOD held at 1.5. */
	i915_vkx_bind_set(x, I915_VKX_ID_SET_FORCED);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST, 0U);

	/* The 32-pixel quad at the bottom right with bias 2. */
	i915_vkx_bind_set(x, I915_VKX_ID_SET_BIAS);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 12, 0U);

	/* The 16-pixel quad at the left through the view of level 2 on. */
	i915_vkx_bind_set(x, I915_VKX_ID_SET_LATER);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 16, 0U);

	/* The 16-pixel quad at the top with linear blending at its natural LOD of 2. */
	i915_vkx_bind_set(x, I915_VKX_ID_SET_LINEAR);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 4, 0U);

	/* The three 8-pixel quads at the top right with the least LOD at 5, 5.5 and 6. */
	i915_vkx_bind_set(x, I915_VKX_ID_SET_LOD5);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 8, 0U);
	i915_vkx_bind_set(x, I915_VKX_ID_SET_LOD5_HALF);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 20, 0U);
	i915_vkx_bind_set(x, I915_VKX_ID_SET_LOD6);
	i915_vkx_draw_indexed(x, 6U, 1U, 0U, (int32_t)I915_VKX_TEXQUAD_FIRST + 24, 0U);
	i915_vkx_record(x, I915_VKX_OP_END_RENDER_PASS);

	/*
	 * Runs it and compares: the blend of levels 1 and 2, level 3, level 2;
	 * level 2; level 5, the blend of levels 5 and 6, level 6.
	 */
	error = i915_vkx_finish(x, "MIP-LINEAR");
	if (error == 0) {
		i915_vkx_expect_clear(x);
		i915_vkx_expect_rect(x, 0U, 0U, 32U, 32U, i915_vkx_blend(i915_vkx_level_colors[1], i915_vkx_level_colors[2]));
		i915_vkx_expect_rect(x, 32U, 32U, 64U, 64U, i915_vkx_level_colors[3]);
		i915_vkx_expect_rect(x, 0U, 32U, 16U, 48U, i915_vkx_level_colors[2]);
		i915_vkx_expect_rect(x, 32U, 0U, 48U, 16U, i915_vkx_level_colors[2]);
		i915_vkx_expect_rect(x, 48U, 0U, 56U, 8U, i915_vkx_level_colors[5]);
		i915_vkx_expect_rect(x, 56U, 0U, 64U, 8U, i915_vkx_blend(i915_vkx_level_colors[5], i915_vkx_level_colors[6]));
		i915_vkx_expect_rect(x, 56U, 8U, 64U, 16U, i915_vkx_level_colors[6]);
		error = i915_vkx_compare_near(x, "MIP-LINEAR");
	}

	i915_vkx_verdict(x, "MIP-LINEAR", error);
}

/*
 * MIP-BLIT: level 0 of the chain is uploaded with a pattern, each further
 * level is made by a linear vkCmdBlitImage from the level above in the same
 * image, and every level is copied out.  Level 0 must come back exactly;
 * every texel of level n + 1 must be the box filter (the rounded mean of
 * the 2x2 texels above it) of level n as it came back, each byte within the
 * mip tolerance.
 */
static void
i915_vkx_step_mip_blit(
	struct i915_vkx *x)
{
	const uint32_t *above;
	const uint32_t *level_texels;
	uint32_t *staging;
	uint32_t *readback;
	uint64_t offset;
	uint64_t above_offset;
	uint32_t level;
	uint32_t extent;
	uint32_t column;
	uint32_t row;
	uint32_t texel;
	uint32_t shift;
	uint32_t sum;
	uint32_t expected;
	uint32_t pattern;
	unsigned differ;
	unsigned first_level;
	unsigned first_texel;
	uint32_t first_have;
	uint32_t first_want;
	int near;
	int error;

	/* Stages level 0: red across, green down, blue a coarse diagonal ripple, opaque. */
	staging = (uint32_t *)(void *)(x->cpu + I915_VKX_SOURCE_OFFSET);
	for (row = 0U; row < I915_VKX_MIP_SIZE; row++) {
		for (column = 0U; column < I915_VKX_MIP_SIZE; column++) {
			staging[row * I915_VKX_MIP_SIZE + column] = (column * 4U) |
			    ((row * 4U) << 8) |
			    ((((column * 3U + row * 5U) & 63U) * 4U) << 16) |
			    0xff000000U;
		}
	}
	drv_i915_gt_clflush(staging, I915_VKX_MIP_SIZE * I915_VKX_MIP_SIZE * 4U);

	/* Clears the readback area so that a level never written cannot pass. */
	readback = (uint32_t *)(void *)(x->cpu + I915_VKX_DESTINATION_OFFSET);
	kern_memset(readback, 0, I915_VKX_COPY_BYTES);
	drv_i915_gt_clflush(readback, I915_VKX_COPY_BYTES);

	/* Records the upload of level 0 and the blit of every further level from the one above. */
	i915_vkx_begin(x);
	i915_vkx_level_copy(x, I915_VKX_OP_COPY_BUFFER_TO_IMAGE, I915_VKX_ID_CHAIN, 0U, 0U);
	for (level = 1U; level < I915_VKX_MIP_LEVELS; level++)
		i915_vkx_level_blit(x, I915_VKX_ID_CHAIN, level);

	/* Records the copy of every level out, packed one after another. */
	offset = 0U;
	for (level = 0U; level < I915_VKX_MIP_LEVELS; level++) {
		i915_vkx_level_copy(x, I915_VKX_OP_COPY_IMAGE_TO_BUFFER, I915_VKX_ID_CHAIN, level, offset);
		offset += (uint64_t)i915_vkx_level_extent(level) * i915_vkx_level_extent(level) * 4U;
	}

	/* Runs it. */
	error = i915_vkx_finish(x, "MIP-BLIT");
	if (error != 0) {
		i915_vkx_verdict(x, "MIP-BLIT", error);
		return;
	}

	/* Reads the levels back past any line the CPU still caches. */
	drv_i915_gt_clflush(readback, (size_t)offset);

	/* Level 0 comes back exactly as staged. */
	differ = 0U;
	first_level = 0U;
	first_texel = 0U;
	first_have = 0U;
	first_want = 0U;
	for (texel = 0U; texel < I915_VKX_MIP_SIZE * I915_VKX_MIP_SIZE; texel++) {
		pattern = staging[texel];
		if (readback[texel] != pattern) {
			if (differ == 0U) {
				first_texel = texel;
				first_have = readback[texel];
				first_want = pattern;
			}
			differ++;
		}
	}

	/* Every further level is the box filter of the level above it as it came back. */
	above_offset = 0U;
	offset = (uint64_t)I915_VKX_MIP_SIZE * I915_VKX_MIP_SIZE * 4U;
	for (level = 1U; level < I915_VKX_MIP_LEVELS; level++) {
		/* Locates the level and the level above in the readback. */
		above = readback + above_offset / 4U;
		level_texels = readback + offset / 4U;
		extent = i915_vkx_level_extent(level);

		/* Compares every texel with the rounded mean of the four above it. */
		for (row = 0U; row < extent; row++) {
			for (column = 0U; column < extent; column++) {
				/* Averages each byte of the 2x2 texels above. */
				expected = 0U;
				for (shift = 0U; shift < 32U; shift += 8U) {
					sum = ((above[(row * 2U) * extent * 2U + column * 2U] >> shift) & 0xffU) +
					    ((above[(row * 2U) * extent * 2U + column * 2U + 1U] >> shift) & 0xffU) +
					    ((above[(row * 2U + 1U) * extent * 2U + column * 2U] >> shift) & 0xffU) +
					    ((above[(row * 2U + 1U) * extent * 2U + column * 2U + 1U] >> shift) & 0xffU);
					expected |= ((sum + 2U) / 4U) << shift;
				}

				/* Counts a texel that is not near and notes the first. */
				near = i915_vkx_near(level_texels[row * extent + column], expected);
				if (near == 0) {
					if (differ == 0U) {
						first_level = level;
						first_texel = row * extent + column;
						first_have = level_texels[row * extent + column];
						first_want = expected;
					}
					differ++;
				}
			}
		}

		/* Moves on: this level is the next one's level above. */
		above_offset = offset;
		offset += (uint64_t)extent * extent * 4U;
	}

	/* Says where the chain differs. */
	if (differ != 0U) {
		kern_logf("i915: vkx: MIP-BLIT: %u texels differ; first in level %u at texel %u: 0x%08x, expected 0x%08x\n",
			  differ,
			  first_level,
			  first_texel,
			  first_have,
			  first_want);
		error = EIO;
	}

	i915_vkx_verdict(x, "MIP-BLIT", error);
}
