/* xzedwm - minimal reparenting window manager. SPDX-License-Identifier: Zlib */
#include <X11/Xlib.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#define MAX_FRAMES 32
#define MAX_XPM_COLORS 64
struct frame { Window client,frame; GC gc; int x,y; unsigned width,height; };
static struct frame frames[MAX_FRAMES];static unsigned frame_count;
struct xpm_color { char key;unsigned long pixel; };
static char*quoted(char*line){char*a=strchr(line,'"'),*b;if(!a)return 0;b=strrchr(a+1,'"');if(!b)return 0;*b=0;return a+1;}
static int xpm_header(char*s,unsigned*w,unsigned*h,unsigned*n,unsigned*cpp){unsigned*v[4]={w,h,n,cpp};unsigned i;char*end;for(i=0;i<4;i++){unsigned long value;while(*s==' '||*s=='\t')s++;value=strtoul(s,&end,10);if(end==s)return 0;*v[i]=(unsigned)value;s=end;}return 1;}
static int load_xpm(Display*d,Window root,const char*path){FILE*f=fopen(path,"r");char line[1024],*q,*pixels=0;unsigned w=0,h=0,n=0,cpp=0,i,y,rw=0,rh=0,b=0,depth=0;int rx=0,ry=0,ok=0;Window rr;struct xpm_color colors[MAX_XPM_COLORS];XRectangle*rects=0;GC gc=0;if(!f)return 0;while(fgets(line,sizeof(line),f)&&(q=quoted(line))==0);if(!q||!xpm_header(q,&w,&h,&n,&cpp)||!w||!h||!n||n>MAX_XPM_COLORS||cpp!=1||w>256||h>256)goto out;for(i=0;i<n;i++){char*hash;if(!fgets(line,sizeof(line),f)||(q=quoted(line))==0)goto out;colors[i].key=q[0];hash=strchr(q,'#');colors[i].pixel=hash?strtoul(hash+1,0,16):0;}pixels=malloc((size_t)w*h);rects=malloc((size_t)w*h*sizeof(*rects));if(!pixels||!rects)goto out;for(y=0;y<h;y++){if(!fgets(line,sizeof(line),f)||(q=quoted(line))==0||strlen(q)<w)goto out;memcpy(pixels+(size_t)y*w,q,w);}if(!XGetGeometry(d,root,&rr,&rx,&ry,&rw,&rh,&b,&depth))goto out;gc=XCreateGC(d,root,0,0);XSetForeground(d,gc,colors[0].pixel);XFillRectangle(d,root,gc,0,0,rw,rh);for(i=0;i<n;i++){int count=0;for(y=0;y<h;y++){unsigned x=0;while(x<w){unsigned start=x;if(pixels[(size_t)y*w+x]!=colors[i].key){x++;continue;}while(x<w&&pixels[(size_t)y*w+x]==colors[i].key)x++;rects[count++]=(XRectangle){(short)(start*rw/w),(short)(y*rh/h),(unsigned short)(x*rw/w-start*rw/w),(unsigned short)((y+1)*rh/h-y*rh/h)};}}if(count){XSetForeground(d,gc,colors[i].pixel);XFillRectangles(d,root,gc,rects,count);}}ok=1;out:if(gc)XFreeGC(d,gc);free(rects);free(pixels);fclose(f);return ok;}
static void load_background(Display*d,Window root){FILE*f=fopen("/etc/Xzed/xzedwm.conf","r");char line[512],path[400]={0};if(!f)return;while(fgets(line,sizeof(line),f)){char*p=line;while(*p==' '||*p=='\t')p++;if(!strncmp(p,"background=",11)){size_t n;strncpy(path,p+11,sizeof(path)-1);n=strlen(path);while(n&&(path[n-1]=='\n'||path[n-1]=='\r'||path[n-1]==' '||path[n-1]=='\t'))path[--n]=0;break;}}fclose(f);if(path[0]&&!load_xpm(d,root,path))fprintf(stderr,"xzedwm: cannot load background %s\n",path);}
static struct frame*by_frame(Window w){unsigned i;for(i=0;i<frame_count;i++)if(frames[i].frame==w)return &frames[i];return 0;}
static void decorate(Display*d,struct frame*f){XSetForeground(d,f->gc,0x182838);XFillRectangle(d,f->frame,f->gc,0,0,f->width+4,20);XSetForeground(d,f->gc,0xa0b8c8);XFillRectangle(d,f->frame,f->gc,0,0,f->width+4,2);XFillRectangle(d,f->frame,f->gc,0,0,2,f->height+22);XFillRectangle(d,f->frame,f->gc,f->width+2,0,2,f->height+22);XFillRectangle(d,f->frame,f->gc,0,f->height+20,f->width+4,2);}
static void manage(Display*d,Window root,Window client){Window r;int x,y;unsigned w,h,b,depth;struct frame*f;if(frame_count==MAX_FRAMES||!XGetGeometry(d,client,&r,&x,&y,&w,&h,&b,&depth))return;f=&frames[frame_count++];memset(f,0,sizeof(*f));f->client=client;f->x=x;f->y=y;f->width=w;f->height=h;f->frame=XCreateSimpleWindow(d,root,x,y,w+4,h+22,0,0,0x304858);f->gc=XCreateGC(d,f->frame,0,0);XSelectInput(d,f->frame,ExposureMask|ButtonPressMask|ButtonReleaseMask|PointerMotionMask|StructureNotifyMask);XReparentWindow(d,client,f->frame,2,20);XMapWindow(d,client);XMapWindow(d,f->frame);decorate(d,f);}
int main(int argc,char**argv){Display*d=XOpenDisplay(0);Window root;XEvent e;struct frame*drag=0;int dx=0,dy=0;extern char**environ;if(!d){fprintf(stderr,"xzedwm: cannot open display\n");return 1;}root=DefaultRootWindow(d);XSelectInput(d,root,SubstructureRedirectMask|SubstructureNotifyMask);load_background(d,root);if(argc>1){pid_t p=fork();if(p==0){execve(argv[1],argv+1,environ);_exit(127);}}
	for(;;){if(XNextEvent(d,&e)<0)break;if(e.type==MapRequest)manage(d,root,e.xmaprequest.window);else if(e.type==Expose){struct frame*f=by_frame(e.xexpose.window);if(f)decorate(d,f);}else if(e.type==ButtonPress){struct frame*f=by_frame(e.xbutton.window);if(f&&e.xbutton.keycode==1){drag=f;dx=e.xbutton.x_root-f->x;dy=e.xbutton.y_root-f->y;}}else if(e.type==MotionNotify&&drag){drag->x=e.xmotion.x_root-dx;drag->y=e.xmotion.y_root-dy;XMoveResizeWindow(d,drag->frame,drag->x,drag->y,drag->width+4,drag->height+22);}else if(e.type==ButtonRelease)drag=0;}
	XCloseDisplay(d);return 0;}
