# zedBSD minimal X11 window manager
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
$(eval $(call ZEDBSD_USERLAND_PACKAGE,xzedwm,xzedwm,*,n,basic,userland/X11/xzedwm/main.c userland/X11/libX11/xlib.c,y,X11,,))
