#!/usr/bin/env python3
# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
"""Extract only AAC-LC normative Huffman numbers from the pinned archive.

No source is executed or unpacked. No FFmpeg lookup structures, comments,
algorithms, identifiers or floating point approximations enter the output.
The symbol index belongs to the AAC codebook; entries are stored in increasing
code length and codeword order, independently of the input representation.
"""

import argparse
import hashlib
import re
import tarfile
from pathlib import Path

ARCHIVE_SHA256 = "8c3850283eb25fa026482078a04051e0be17347b09ef81a0849bec15a96e002e"
SOURCE_SHA256 = "dc26f9316026cd807617db09c72424ae2b19b07a1d9c19a45cc05ab9617a32ce"
MEMBER = "ffmpeg-9.0.2/libavcodec/aactab.c"
SPECTRAL_COUNTS = (81, 81, 81, 81, 81, 81, 64, 64, 169, 169, 289)
ROOT = Path(__file__).resolve().parents[3]


def numbers(source, name, count):
    """Accept one literal integer initializer and reject any C expression."""
    pattern = (r"\b" + re.escape(name) + r"\s*\[\s*" + str(count)
               + r"\s*\]\s*=\s*\{([^{}]*)\}\s*;")
    matches = re.findall(pattern, source)
    if len(matches) != 1:
        raise ValueError(f"{name}: expected one fixed-size initializer")
    content = re.sub(r"/\*.*?\*/|//[^\n]*", "", matches[0], flags=re.S)
    fields = content.strip().rstrip(",").split(",")
    values = []
    for field in fields:
        token = field.strip()
        if re.fullmatch(r"(?:0[xX][0-9a-fA-F]+|[0-9]+)", token) is None:
            raise ValueError(f"{name}: nonliteral field")
        values.append(int(token, 16 if token.lower().startswith("0x") else 10))
    if len(values) != count:
        raise ValueError(f"{name}: unexpected element count")
    return values


def validate(words, lengths):
    """Check finite codewords, prefix exclusion and the complete Kraft sum."""
    trie = {}
    for symbol, (word, length) in enumerate(zip(words, lengths, strict=True)):
        if not 1 <= length <= 32 or not 0 <= word < 1 << length:
            raise ValueError("invalid codeword width")
        node = trie
        for shift in range(length - 1, -1, -1):
            if "symbol" in node:
                raise ValueError("existing codeword is a prefix")
            node = node.setdefault((word >> shift) & 1, {})
        if node:
            raise ValueError("duplicate codeword or prefix")
        node["symbol"] = symbol
    longest = max(lengths)
    if sum(1 << (longest - width) for width in lengths) != 1 << longest:
        raise ValueError("incomplete codebook")
    for symbol, (word, length) in enumerate(zip(words, lengths, strict=True)):
        node = trie
        for shift in range(length - 1, -1, -1):
            node = node[(word >> shift) & 1]
        if node["symbol"] != symbol:
            raise ValueError("symbol correspondence changed")


def render(source):
    """Emit fresh C declarations containing the validated numeric facts."""
    books = [(numbers(source, "ff_aac_scalefactor_code", 121),
              numbers(source, "ff_aac_scalefactor_bits", 121))]
    for index, count in enumerate(SPECTRAL_COUNTS, 1):
        books.append((numbers(source, f"codes{index}", count),
                      numbers(source, f"bits{index}", count)))
    lines = ["/*", " * zedBSD", " * Copyright (C) 2026 Awe Morris",
             " *", " * SPDX-License-Identifier: Zlib", " */", "", "/*",
             " * AAC-LC Huffman numeric facts: scalefactor and spectral codebooks.",
             " * Generated by plan/ws202/tests/gen-aac-huffman.py; values only.",
             " * ISO/IEC 14496-3 AAC; MPEG-2 AAC ISO/IEC 13818-7 Annex A.",
             " * Intermediate transcription: ffmpeg-9.0.2/libavcodec/aactab.c.",
             f" * Archive SHA-256: {ARCHIVE_SHA256}",
             f" * Source SHA-256: {SOURCE_SHA256}",
             " * No implementation code or optimized decoding tables are copied.",
             " */", "", '#include "aac-huffman.h"', ""]
    for index, (words, lengths) in enumerate(books):
        validate(words, lengths)
        lines += [f"/* Codebook {index}, sorted by length and word; symbols keep their AAC indices. */",
                  f"static const struct media_aac_codeword aac_words_{index}[{len(words)}] = {{"]
        entries = sorted((length, word, symbol) for symbol, (word, length)
                         in enumerate(zip(words, lengths, strict=True)))
        for length, word, symbol in entries:
            lines.append(f"\t{{ 0x{word:x}U, {symbol}U, {length}U }},")
        lines += ["};", ""]
    lines += ["/* Codebooks 0 through 11: scalefactor, then spectral; immutable for library lifetime. */",
              "const struct media_aac_codebook media_aac_huffman_books[12] = {"]
    for index, (words, _) in enumerate(books):
        lines.append(f"\t{{ aac_words_{index}, {len(words)}U }},")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    archive = args.archive.read_bytes()
    if hashlib.sha256(archive).hexdigest() != ARCHIVE_SHA256:
        raise ValueError("archive SHA-256 mismatch")
    with tarfile.open(args.archive, "r:xz") as bundle:
        member = bundle.getmember(MEMBER)
        if not member.isfile() or member.size > 2 * 1024 * 1024:
            raise ValueError("unexpected data member")
        stream = bundle.extractfile(member)
        if stream is None:
            raise ValueError("missing AAC data")
        with stream:
            source = stream.read()
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
        raise ValueError("AAC data SHA-256 mismatch")
    output = render(source.decode("utf-8"))
    destination = ROOT / "userland/desktop/libmedia/aac-huffman.c"
    if args.check:
        if destination.read_text() != output:
            raise ValueError("generated numeric data differs")
    else:
        destination.write_text(output)
    print("AAC-LC Huffman: 12 codebooks; counts, widths, prefix, Kraft, symbols PASS")


if __name__ == "__main__":
    main()
