#!/usr/bin/env python3
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
"""Extract only normative AAC-LC integer band/TNS facts, never source code."""
import argparse
import hashlib
import re
import tarfile
from pathlib import Path

ARCHIVE_SHA = "8c3850283eb25fa026482078a04051e0be17347b09ef81a0849bec15a96e002e"
SOURCE_SHA = "dc26f9316026cd807617db09c72424ae2b19b07a1d9c19a45cc05ab9617a32ce"
MEMBER = "ffmpeg-9.0.2/libavcodec/aactab.c"
ROOT = Path(__file__).resolve().parents[3]
LONG = (96, 96, 64, 48, 48, 32, 24, 24, 16, 16, 16, 8, 8)
SHORT = (96, 96, 96, 48, 48, 48, 24, 24, 16, 16, 16, 8, 8)
COUNTS = {1024: {96: 42, 64: 48, 48: 50, 32: 52, 24: 48, 16: 44, 8: 41},
          128: {96: 13, 48: 15, 24: 16, 16: 16, 8: 16}}

def numbers(source, name, count):
    matches = re.findall(r"\b" + re.escape(name) + r"\s*\[\s*(?:" + str(count) + r")?\s*\]\s*=\s*\{([^{}]*)\}\s*;", source)
    if len(matches) != 1:
        raise ValueError(name + ": ambiguous initializer")
    content = re.sub(r"/\*.*?\*/|//[^\n]*", "", matches[0], flags=re.S)
    fields = content.strip().rstrip(",").split(",")
    if len(fields) != count:
        raise ValueError(name + ": count mismatch")
    if any(re.fullmatch(r"\s*[0-9]+\s*", field) is None for field in fields):
        raise ValueError(name + ": nonliteral numeric fact")
    return [int(field) for field in fields]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if hashlib.sha256(args.archive.read_bytes()).hexdigest() != ARCHIVE_SHA:
        raise ValueError("archive mismatch")
    with tarfile.open(args.archive, "r:xz") as bundle:
        with bundle.extractfile(MEMBER) as stream:
            raw = stream.read()
    if hashlib.sha256(raw).hexdigest() != SOURCE_SHA:
        raise ValueError("numeric source mismatch")
    source = raw.decode()
    count = {n: numbers(source, f"ff_aac_num_swb_{n}", 13) for n in COUNTS}
    tns = {n: numbers(source, f"ff_tns_max_bands_{n}", 13) for n in COUNTS}
    lines = ["/*", " * zedBSD", " * Copyright (C) 2026 Awe Morris", " *", " * SPDX-License-Identifier: Zlib", " */", "", "/*", " * AAC band/TNS normative integer facts; values only, no implementation copied.", " * ISO/IEC 14496-3; intermediate numeric transcription: " + MEMBER + ".", " * Archive SHA-256: " + ARCHIVE_SHA, " * Source SHA-256: " + SOURCE_SHA, " * Generated by plan/ws202/tests/gen-aac-bands.py.", " */", "", '#include "aac-bands.h"', ""]
    for n, rates in COUNTS.items():
        for rate, size in rates.items():
            offsets = numbers(source, f"swb_offset_{n}_{rate}", size)
            if offsets[0] != 0 or offsets[-1] != n:
                raise ValueError("band endpoint")
            if any(b <= a or b % 4 for a, b in zip(offsets, offsets[1:])):
                raise ValueError("band order/alignment")
            lines += [f"/* Immutable {n}-coefficient band boundaries for the {rate} kHz group. */", f"static const uint16_t bands_{n}_{rate}[{size}] = {{", "\t" + ", ".join(str(x) + "U" for x in offsets), "};", ""]
    lines += ["/* All thirteen normative frequency indices; immutable for decoder lifetimes. */", "const struct media_aac_bands media_aac_bands[13] = {"]
    for i, (lo, sh) in enumerate(zip(LONG, SHORT)):
        if count[1024][i] + 1 != COUNTS[1024][lo] or count[128][i] + 1 != COUNTS[128][sh]:
            raise ValueError("normative frequency grouping")
        lines.append(f"\t{{ bands_1024_{lo}, bands_128_{sh}, {count[1024][i]}U, {count[128][i]}U, {tns[1024][i]}U, {tns[128][i]}U }},")
    lines += ["};", ""]
    output = "\n".join(lines)
    dest = ROOT / "userland/desktop/libmedia/aac-bands.c"
    if args.check:
        if dest.read_text() != output:
            raise ValueError("generated facts differ")
    else:
        dest.write_text(output)
    print("AAC band/TNS integers: 13 frequencies, endpoints, alignment, counts PASS")

if __name__ == "__main__":
    main()
