include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,uncompress,uncompress,*,y,basic,userland/base/compress/main.c userland/base/common/lzw.c,y,base,,))
