#!/usr/bin/env python3
"""Generate zedBSD's Unicode simple-case-fold table from CaseFolding.txt."""

import pathlib
import sys


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-unicode-casefold.py CaseFolding.txt output.inc")
    source = pathlib.Path(sys.argv[1])
    output = pathlib.Path(sys.argv[2])
    version = "unknown"
    pairs: list[tuple[int, int]] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        if line.startswith("# CaseFolding-"):
            version = line[2:].strip()
        fields = line.split("#", 1)[0].strip().split(";")
        if len(fields) < 3:
            continue
        status = fields[1].strip()
        mapping = fields[2].strip().split()
        if status not in ("C", "S") or len(mapping) != 1:
            continue
        pairs.append((int(fields[0].strip(), 16), int(mapping[0], 16)))
    pairs.sort()
    ranges: list[tuple[int, int, int, int]] = []
    index = 0
    while index < len(pairs):
        start, target = pairs[index]
        delta = target - start
        step = 1
        if index + 1 < len(pairs):
            next_source, next_target = pairs[index + 1]
            candidate = next_source - start
            if candidate in (1, 2) and next_target - next_source == delta:
                step = candidate
        end = start
        scan = index + 1
        while (scan < len(pairs) and pairs[scan][0] == end + step and
               pairs[scan][1] - pairs[scan][0] == delta):
            end = pairs[scan][0]
            scan += 1
        ranges.append((start, end, delta, step))
        index = scan
    lines = [
        "/* Generated by scripts/generate-unicode-casefold.py from",
        f" * Unicode {version}; statuses C and S only.  Do not edit. */",
        "static const struct fat_casefold_range fat_casefold_ranges[] = {",
    ]
    for start, end, delta, step in ranges:
        encoded_end = end | (0x80000000 if step == 2 else 0)
        lines.append(f"\t{{ 0x{start:06x}U, 0x{encoded_end:08x}U, {delta} }},")
    lines.append("};")
    output.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")
    print(f"{output}: {len(pairs)} mappings in {len(ranges)} ranges ({version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
