#!/usr/bin/env python3
"""Small, dependency-free menu configurator for zedBSD."""
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

from __future__ import annotations

import argparse
import curses
import re
from pathlib import Path

PLATFORMS = [
    ("i386", "pcat", "pcat", "i386 PC/AT compatible"),
    ("amd64", "amd64", "pcat", "x86_64 PC/AT compatible"),
    ("pc98", "pc98", "pc98", "NEC PC-9800"),
    ("rpi4", "arm64", "rpi4", "Raspberry Pi 4 Arm64"),
    ("sun4u", "sparcv9", "sun4u", "SPARC V9 sun4u"),
    ("x68k", "x68k", "x68k", "Sharp X68000 MC68030"),
]

ARCHITECTURES = [
    ("i386", "i386 32-bit"),
    ("amd64", "x86_64 64-bit"),
    ("arm64", "Arm64"),
    ("sparcv9", "SPARC V9 64-bit"),
    ("m68k", "Motorola 68000 family"),
]

PLATFORM_ARCHITECTURE = {
    "i386": "i386",
    "pc98": "i386",
    "amd64": "amd64",
    "rpi4": "arm64",
    "sun4u": "sparcv9",
    "x68k": "m68k",
}

BOARD_LABELS = {
    "pcat": "IBM PC/AT compatible",
    "pc98": "NEC PC-9800",
    "rpi4": "Raspberry Pi 4",
    "sun4u": "sun4u",
    "x68k": "Sharp X68000",
}

DEFAULTS = {
    "ZEDBSD_PLATFORM": "i386",
    "CONFIG_DRIVER_NE2000": "y",
    "CONFIG_DRIVER_LGY98": "n",
    "CONFIG_DRIVER_GRAPHICS": "y",
    "CONFIG_KERNEL_LOCKDEP": "n",
    "CONFIG_KERNEL_TEST_CHECKPOINTS": "n",
    "CONFIG_BUF_CACHE_KIB": "0",
}


def platform_record(name: str):
    return next((item for item in PLATFORMS if item[0] == name), PLATFORMS[0])


def architecture_for_platform(name: str) -> str:
    return PLATFORM_ARCHITECTURE[name]


def platforms_for_architecture(architecture: str):
    return [item for item in PLATFORMS
            if architecture_for_platform(item[0]) == architecture]


def load(path: Path) -> dict[str, str]:
    values = dict(DEFAULTS)
    if not path.exists():
        return values
    pattern = re.compile(r"^([A-Z][A-Z0-9_]*)\s*(?::=|=)\s*([^#\s]+)")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            values[match.group(1)] = match.group(2)
    if values["ZEDBSD_PLATFORM"] not in {item[0] for item in PLATFORMS}:
        values["ZEDBSD_PLATFORM"] = "i386"
    return values


def normalize(values: dict[str, str]) -> None:
    platform = values["ZEDBSD_PLATFORM"]
    values["CONFIG_DRIVER_NE2000"] = (
        values["CONFIG_DRIVER_NE2000"] if platform in ("i386", "amd64") else "n")
    values["CONFIG_DRIVER_LGY98"] = (
        values["CONFIG_DRIVER_LGY98"] if platform == "pc98" else "n")
    if platform not in ("i386", "amd64", "pc98"):
        values["CONFIG_DRIVER_GRAPHICS"] = "n"
    if platform != "amd64":
        values["CONFIG_KERNEL_TEST_CHECKPOINTS"] = "n"


def save(path: Path, values: dict[str, str]) -> None:
    normalize(values)
    platform, make_arch, board, _ = platform_record(values["ZEDBSD_PLATFORM"])
    architecture = architecture_for_platform(platform)
    text = [
        "# Automatically generated by ./build.sh menuconfig.  Do not edit.",
        f"ZEDBSD_PLATFORM := {platform}",
        f"ZEDBSD_ARCHITECTURE := {architecture}",
        f"ZEDBSD_BOARD := {board}",
        f"ZEDBSD_MAKE_ARCH := {make_arch}",
        "",
    ]
    for key in DEFAULTS:
        if key != "ZEDBSD_PLATFORM":
            text.append(f"{key} := {values[key]}")
    path.write_text("\n".join(text) + "\n", encoding="utf-8")


def rows(values: dict[str, str]):
    platform = values["ZEDBSD_PLATFORM"]
    required = {
        "i386": "PC/AT IDE",
        "amd64": "PC/AT IDE",
        "pc98": "PC-98 IDE",
        "rpi4": "BCM2711 SDHCI",
        "sun4u": "CMD646 IDE",
        "x68k": "MB89352/SPC SCSI",
    }[platform]
    result = [
        ("architecture", "ZEDBSD_PLATFORM", "Architecture"),
        ("board", "ZEDBSD_PLATFORM", "Board"),
        ("fixed", "", f"Built-in storage driver: {required}"),
    ]
    if platform in ("i386", "amd64"):
        result.append(("bool", "CONFIG_DRIVER_NE2000", "ISA NE2000 network driver"))
    if platform == "pc98":
        result.append(("bool", "CONFIG_DRIVER_LGY98", "LGY-98 network driver"))
    if platform in ("i386", "amd64", "pc98"):
        result.append(("bool", "CONFIG_DRIVER_GRAPHICS", "Graphics device driver"))
    result += [
        ("bool", "CONFIG_KERNEL_LOCKDEP", "Kernel lock-order diagnostics"),
        ("cache", "CONFIG_BUF_CACHE_KIB", "Buffer cache limit"),
    ]
    if platform == "amd64":
        result.append(("bool", "CONFIG_KERNEL_TEST_CHECKPOINTS",
                       "Kernel test checkpoints (diagnostic)"))
    return result


def value_text(kind: str, key: str, values: dict[str, str]) -> str:
    if kind == "architecture":
        architecture = architecture_for_platform(values[key])
        return next(label for name, label in ARCHITECTURES
                    if name == architecture)
    if kind == "board":
        return BOARD_LABELS[platform_record(values[key])[2]]
    if kind == "bool":
        return "[*]" if values[key] == "y" else "[ ]"
    if kind == "cache":
        return "automatic" if values[key] == "0" else values[key] + " KiB"
    return "---"


def change(kind: str, key: str, values: dict[str, str], direction: int = 1) -> None:
    if kind == "bool":
        values[key] = "n" if values[key] == "y" else "y"
    elif kind == "cache":
        choices = ["0", "256", "1024", "4096", "16384"]
        current = values[key] if values[key] in choices else "0"
        values[key] = choices[(choices.index(current) + direction) % len(choices)]


def select_from_list(screen, title: str, options: list[tuple[str, str]],
                     current: str) -> str | None:
    selected = next((index for index, item in enumerate(options)
                     if item[0] == current), 0)
    offset = 0
    while True:
        screen_height, screen_width = screen.getmaxyx()
        height = min(max(7, len(options) + 4), max(5, screen_height - 2))
        width = min(max(42, len(title) + 8,
                        max(len(label) for _, label in options) + 8),
                    max(20, screen_width - 2))
        top = max(0, (screen_height - height) // 2)
        left = max(0, (screen_width - width) // 2)
        window = curses.newwin(height, width, top, left)
        window.keypad(True)
        window.erase()
        window.box()
        window.addnstr(0, 2, f" {title} ", max(0, width - 4), curses.A_BOLD)
        visible = height - 3
        if selected < offset:
            offset = selected
        elif selected >= offset + visible:
            offset = selected - visible + 1
        for row, (_, label) in enumerate(options[offset:offset + visible]):
            index = offset + row
            marker = "(*)" if index == selected else "( )"
            attr = curses.A_REVERSE if index == selected else curses.A_NORMAL
            window.addnstr(2 + row, 2, f"{marker} {label}", width - 4, attr)
        window.refresh()
        keycode = window.getch()
        if keycode in (curses.KEY_UP, ord("k")):
            selected = (selected - 1) % len(options)
        elif keycode in (curses.KEY_DOWN, ord("j")):
            selected = (selected + 1) % len(options)
        elif keycode in (10, 13, ord(" ")):
            return options[selected][0]
        elif keycode in (27, ord("q"), ord("Q")):
            return None


def select_architecture(screen, values: dict[str, str]) -> None:
    current_platform = values["ZEDBSD_PLATFORM"]
    current_architecture = architecture_for_platform(current_platform)
    selected = select_from_list(screen, "Architecture", ARCHITECTURES,
                                current_architecture)
    if selected is None or selected == current_architecture:
        return
    values["ZEDBSD_PLATFORM"] = platforms_for_architecture(selected)[0][0]
    normalize(values)


def select_board(screen, values: dict[str, str]) -> None:
    current_platform = values["ZEDBSD_PLATFORM"]
    architecture = architecture_for_platform(current_platform)
    candidates = platforms_for_architecture(architecture)
    options = [(item[0], BOARD_LABELS[item[2]]) for item in candidates]
    selected = select_from_list(screen, "Board", options, current_platform)
    if selected is not None:
        values["ZEDBSD_PLATFORM"] = selected
        normalize(values)


def tui(screen, values: dict[str, str], output: Path) -> None:
    curses.curs_set(0)
    selected = 0
    while True:
        screen.erase()
        height, width = screen.getmaxyx()
        title = " zedBSD Configuration "
        screen.addnstr(0, max(0, (width - len(title)) // 2), title,
                       max(0, width - 1), curses.A_REVERSE | curses.A_BOLD)
        screen.addnstr(2, 2, "Arrow keys navigate; Space/Enter changes a value.",
                       max(0, width - 4))
        current_rows = rows(values)
        selected = min(selected, len(current_rows) - 1)
        for index, (kind, key, label) in enumerate(current_rows):
            marker = ">" if index == selected else " "
            value = value_text(kind, key, values)
            line = f"{marker} {value:<28} {label}"
            attr = curses.A_REVERSE if index == selected else curses.A_NORMAL
            if 4 + index < height - 3:
                screen.addnstr(4 + index, 2, line, max(0, width - 4), attr)
        footer = "<S> Save    <Q> Save and exit    <Esc> Exit without saving"
        screen.addnstr(height - 2, 2, footer, max(0, width - 4), curses.A_REVERSE)
        screen.refresh()
        keycode = screen.getch()
        if keycode in (curses.KEY_UP, ord("k")):
            selected = (selected - 1) % len(current_rows)
        elif keycode in (curses.KEY_DOWN, ord("j")):
            selected = (selected + 1) % len(current_rows)
        elif keycode in (curses.KEY_LEFT,):
            kind, key = current_rows[selected][:2]
            if kind == "cache":
                change(kind, key, values, -1)
        elif keycode in (curses.KEY_RIGHT, ord(" "), 10, 13):
            kind, key = current_rows[selected][:2]
            if kind == "architecture":
                select_architecture(screen, values)
            elif kind == "board":
                select_board(screen, values)
            else:
                change(kind, key, values, 1)
        elif keycode in (ord("s"), ord("S")):
            save(output, values)
        elif keycode in (ord("q"), ord("Q")):
            save(output, values)
            return
        elif keycode == 27:
            return


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--defaults", action="store_true",
                        help="write defaults without opening the TUI")
    args = parser.parse_args()
    values = dict(DEFAULTS) if args.defaults else load(args.output)
    if args.defaults:
        save(args.output, values)
    else:
        curses.wrapper(tui, values, args.output)


if __name__ == "__main__":
    main()
