/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * AAC band/TNS normative integer facts; values only, no implementation copied.
 * ISO/IEC 14496-3; intermediate numeric transcription: ffmpeg-9.0.2/libavcodec/aactab.c.
 * Archive SHA-256: 8c3850283eb25fa026482078a04051e0be17347b09ef81a0849bec15a96e002e
 * Source SHA-256: dc26f9316026cd807617db09c72424ae2b19b07a1d9c19a45cc05ab9617a32ce
 * Generated by plan/ws202/tests/gen-aac-bands.py.
 */

#include "aac-bands.h"

/* Immutable 1024-coefficient band boundaries for the 96 kHz group. */
static const uint16_t bands_1024_96[42] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 32U, 36U, 40U, 44U, 48U, 52U, 56U, 64U, 72U, 80U, 88U, 96U, 108U, 120U, 132U, 144U, 156U, 172U, 188U, 212U, 240U, 276U, 320U, 384U, 448U, 512U, 576U, 640U, 704U, 768U, 832U, 896U, 960U, 1024U
};

/* Immutable 1024-coefficient band boundaries for the 64 kHz group. */
static const uint16_t bands_1024_64[48] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 32U, 36U, 40U, 44U, 48U, 52U, 56U, 64U, 72U, 80U, 88U, 100U, 112U, 124U, 140U, 156U, 172U, 192U, 216U, 240U, 268U, 304U, 344U, 384U, 424U, 464U, 504U, 544U, 584U, 624U, 664U, 704U, 744U, 784U, 824U, 864U, 904U, 944U, 984U, 1024U
};

/* Immutable 1024-coefficient band boundaries for the 48 kHz group. */
static const uint16_t bands_1024_48[50] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 32U, 36U, 40U, 48U, 56U, 64U, 72U, 80U, 88U, 96U, 108U, 120U, 132U, 144U, 160U, 176U, 196U, 216U, 240U, 264U, 292U, 320U, 352U, 384U, 416U, 448U, 480U, 512U, 544U, 576U, 608U, 640U, 672U, 704U, 736U, 768U, 800U, 832U, 864U, 896U, 928U, 1024U
};

/* Immutable 1024-coefficient band boundaries for the 32 kHz group. */
static const uint16_t bands_1024_32[52] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 32U, 36U, 40U, 48U, 56U, 64U, 72U, 80U, 88U, 96U, 108U, 120U, 132U, 144U, 160U, 176U, 196U, 216U, 240U, 264U, 292U, 320U, 352U, 384U, 416U, 448U, 480U, 512U, 544U, 576U, 608U, 640U, 672U, 704U, 736U, 768U, 800U, 832U, 864U, 896U, 928U, 960U, 992U, 1024U
};

/* Immutable 1024-coefficient band boundaries for the 24 kHz group. */
static const uint16_t bands_1024_24[48] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 32U, 36U, 40U, 44U, 52U, 60U, 68U, 76U, 84U, 92U, 100U, 108U, 116U, 124U, 136U, 148U, 160U, 172U, 188U, 204U, 220U, 240U, 260U, 284U, 308U, 336U, 364U, 396U, 432U, 468U, 508U, 552U, 600U, 652U, 704U, 768U, 832U, 896U, 960U, 1024U
};

/* Immutable 1024-coefficient band boundaries for the 16 kHz group. */
static const uint16_t bands_1024_16[44] = {
	0U, 8U, 16U, 24U, 32U, 40U, 48U, 56U, 64U, 72U, 80U, 88U, 100U, 112U, 124U, 136U, 148U, 160U, 172U, 184U, 196U, 212U, 228U, 244U, 260U, 280U, 300U, 320U, 344U, 368U, 396U, 424U, 456U, 492U, 532U, 572U, 616U, 664U, 716U, 772U, 832U, 896U, 960U, 1024U
};

/* Immutable 1024-coefficient band boundaries for the 8 kHz group. */
static const uint16_t bands_1024_8[41] = {
	0U, 12U, 24U, 36U, 48U, 60U, 72U, 84U, 96U, 108U, 120U, 132U, 144U, 156U, 172U, 188U, 204U, 220U, 236U, 252U, 268U, 288U, 308U, 328U, 348U, 372U, 396U, 420U, 448U, 476U, 508U, 544U, 580U, 620U, 664U, 712U, 764U, 820U, 880U, 944U, 1024U
};

/* Immutable 128-coefficient band boundaries for the 96 kHz group. */
static const uint16_t bands_128_96[13] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 32U, 40U, 48U, 64U, 92U, 128U
};

/* Immutable 128-coefficient band boundaries for the 48 kHz group. */
static const uint16_t bands_128_48[15] = {
	0U, 4U, 8U, 12U, 16U, 20U, 28U, 36U, 44U, 56U, 68U, 80U, 96U, 112U, 128U
};

/* Immutable 128-coefficient band boundaries for the 24 kHz group. */
static const uint16_t bands_128_24[16] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 36U, 44U, 52U, 64U, 76U, 92U, 108U, 128U
};

/* Immutable 128-coefficient band boundaries for the 16 kHz group. */
static const uint16_t bands_128_16[16] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 32U, 40U, 48U, 60U, 72U, 88U, 108U, 128U
};

/* Immutable 128-coefficient band boundaries for the 8 kHz group. */
static const uint16_t bands_128_8[16] = {
	0U, 4U, 8U, 12U, 16U, 20U, 24U, 28U, 36U, 44U, 52U, 60U, 72U, 88U, 108U, 128U
};

/* All thirteen normative frequency indices; immutable for decoder lifetimes. */
const struct media_aac_bands media_aac_bands[13] = {
	{ bands_1024_96, bands_128_96, 41U, 12U, 31U, 9U },
	{ bands_1024_96, bands_128_96, 41U, 12U, 31U, 9U },
	{ bands_1024_64, bands_128_96, 47U, 12U, 34U, 10U },
	{ bands_1024_48, bands_128_48, 49U, 14U, 40U, 14U },
	{ bands_1024_48, bands_128_48, 49U, 14U, 42U, 14U },
	{ bands_1024_32, bands_128_48, 51U, 14U, 51U, 14U },
	{ bands_1024_24, bands_128_24, 47U, 15U, 46U, 14U },
	{ bands_1024_24, bands_128_24, 47U, 15U, 46U, 14U },
	{ bands_1024_16, bands_128_16, 43U, 15U, 42U, 14U },
	{ bands_1024_16, bands_128_16, 43U, 15U, 42U, 14U },
	{ bands_1024_16, bands_128_16, 43U, 15U, 42U, 14U },
	{ bands_1024_8, bands_128_8, 40U, 15U, 39U, 14U },
	{ bands_1024_8, bands_128_8, 40U, 15U, 39U, 14U },
};
