include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,cflow,cflow,*,y,basic,userland/base/cflow/main.c userland/base/common/c_parser.c,y,base,,))
