/* Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib */
#include "userland/common/command.h"
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define CHMOD_PATH_CAPACITY 1024U
#define CHMOD_DEPTH_LIMIT 64

static int join_path(const char*a,const char*b,char*out,size_t cap){size_t x=strlen(a),y=strlen(b);int slash=x&&a[x-1]!='/';if(x+(size_t)slash+y+1U>cap){errno=ENAMETOOLONG;return 0;}memcpy(out,a,x);if(slash)out[x++]='/';memcpy(out+x,b,y+1U);return 1;}
static mode_t class_mask(int who){mode_t mask=0;if(who&1)mask|=S_IRWXU|S_ISUID;if(who&2)mask|=S_IRWXG|S_ISGID;if(who&4)mask|=S_IRWXO|S_ISVTX;return mask;}
static mode_t copied_bits(mode_t mode,char source,int who){mode_t triad=source=='u'?(mode&S_IRWXU)>>6:source=='g'?(mode&S_IRWXG)>>3:mode&S_IRWXO;mode_t out=0;if(who&1)out|=triad<<6;if(who&2)out|=triad<<3;if(who&4)out|=triad;return out;}
static int symbolic_mode(const char*spec,mode_t original,mode_t umask_value,int directory,mode_t*result){const char*p=spec;mode_t mode=original;while(*p){int who=0,explicit_who=0;char operation;mode_t bits=0,affected;while(*p=='u'||*p=='g'||*p=='o'||*p=='a'){explicit_who=1;if(*p=='u')who|=1;else if(*p=='g')who|=2;else if(*p=='o')who|=4;else who=7;p++;}if(!who)who=7;operation=*p++;if(operation!='+'&&operation!='-'&&operation!='=')return 0;while(*p&&*p!=','){switch(*p){case'r':if(who&1)bits|=S_IRUSR;if(who&2)bits|=S_IRGRP;if(who&4)bits|=S_IROTH;break;case'w':if(who&1)bits|=S_IWUSR;if(who&2)bits|=S_IWGRP;if(who&4)bits|=S_IWOTH;break;case'x':if(who&1)bits|=S_IXUSR;if(who&2)bits|=S_IXGRP;if(who&4)bits|=S_IXOTH;break;case'X':if(directory||(original&(S_IXUSR|S_IXGRP|S_IXOTH))){if(who&1)bits|=S_IXUSR;if(who&2)bits|=S_IXGRP;if(who&4)bits|=S_IXOTH;}break;case's':if(who&1)bits|=S_ISUID;if(who&2)bits|=S_ISGID;break;case't':if(who&4)bits|=S_ISVTX;break;case'u':case'g':case'o':bits|=copied_bits(mode,*p,who);break;default:return 0;}p++;}affected=class_mask(who);if(!explicit_who)bits&=~umask_value;if(operation=='+')mode|=bits;else if(operation=='-')mode&=~bits;else{mode&=~affected;mode|=bits;}if(*p==','){p++;if(!*p)return 0;}}*result=mode;return 1;}
static int apply_path(const char*path,const char*spec,int numeric,mode_t numeric_mode,mode_t mask,int recursive,int depth){struct stat status;mode_t mode;int ok=1;if(depth>CHMOD_DEPTH_LIMIT){errno=ELOOP;command_error("chmod",path);return 0;}if(lstat(path,&status)){command_error("chmod",path);return 0;}if(S_ISLNK(status.st_mode))return 1;if(numeric)mode=numeric_mode;else if(!symbolic_mode(spec,status.st_mode,mask,S_ISDIR(status.st_mode),&mode)){fprintf(stderr,"chmod: invalid mode: %s\n",spec);return 0;}if(chmod(path,mode)){command_error("chmod",path);ok=0;}if(recursive&&S_ISDIR(status.st_mode)){DIR*d=opendir(path);struct dirent*entry;if(!d){command_error("chmod",path);return 0;}while((entry=readdir(d))!=NULL){char child[CHMOD_PATH_CAPACITY];if(!strcmp(entry->d_name,".")||!strcmp(entry->d_name,".."))continue;if(!join_path(path,entry->d_name,child,sizeof(child))||!apply_path(child,spec,numeric,numeric_mode,mask,1,depth+1))ok=0;}if(closedir(d)){command_error("chmod",path);ok=0;}}return ok;}
int main(int argc,char**argv){int recursive=0,index=1,failed=0,numeric;unsigned parsed=0;mode_t mask;const char*spec;if(index<argc&&!strcmp(argv[index],"-R")){recursive=1;index++;}if(index<argc&&!strcmp(argv[index],"--"))index++;if(index+1>=argc){fprintf(stderr,"usage: chmod [-R] mode file...\n");return 1;}spec=argv[index++];numeric=command_parse_mode(spec,&parsed)==0;mask=umask(0);(void)umask(mask);for(;index<argc;index++)if(!apply_path(argv[index],spec,numeric,(mode_t)parsed,mask,recursive,0))failed=1;return failed;}
