# zedBSD persistent network configuration.
version: 1

interfaces:
  lo0:
    type: loopback
    enabled: true
    ipv4:
      dhcp: false
      addresses:
        - address: 127.0.0.1
          prefix-length: 8

dns:
  mode: dhcp
