version: 1
hostname: zedbsd

services:
  cron:
    enabled: true
  getty_console:
    enabled: true
  net:
    enabled: true
  networkd:
    enabled: true
  ntpdate:
    enabled: false
    settings:
      servers: ""
  syslogd:
    enabled: true
