/* Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib */
#include "userland/net/dhcp.h"
#include "userland/net/netutil.h"

#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <net/route.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

struct snapshot {
	int flags;
	struct in_addr address, mask, broadcast;
};

static int
if_request(int descriptor, const char *name, unsigned long command,
	struct ifreq *request)
{
	if (netutil_ifreq(request, name) != 0) return -1;
	return ioctl(descriptor, command, request);
}

static int
get_address(int descriptor, const char *name, unsigned long command,
	struct in_addr *address)
{
	struct ifreq request;
	if (if_request(descriptor, name, command, &request) != 0) return -1;
	*address = ((struct sockaddr_in *)&request.ifr_addr)->sin_addr;
	return 0;
}

static int
set_address(int descriptor, const char *name, unsigned long command,
	struct in_addr address)
{
	struct ifreq request;
	struct sockaddr_in *inet;
	if (netutil_ifreq(&request, name) != 0) return -1;
	inet = (struct sockaddr_in *)&request.ifr_addr;
	inet->sin_family = AF_INET; inet->sin_addr = address;
	return ioctl(descriptor, command, &request);
}

static int
select_interface(int descriptor, char name[IFNAMSIZ])
{
	struct ifreq *items, request;
	unsigned count, index, candidates = 0;
	if (netutil_interfaces(descriptor, &items, &count) != 0) return -1;
	for (index = 0; index < count; index++) {
		if (if_request(descriptor, items[index].ifr_name, SIOCGIFFLAGS,
		    &request) == 0 && (request.ifr_flags & IFF_BROADCAST) != 0) {
			strncpy(name, items[index].ifr_name, IFNAMSIZ - 1U); candidates++;
		}
	}
	free(items);
	if (candidates != 1U) { errno = candidates == 0 ? ENODEV : EBUSY; return -1; }
	return 0;
}

static uint32_t
transaction_id(const uint8_t mac[6])
{
	uint32_t value = (uint32_t)netutil_monotonic_us(); unsigned i;
	for (i = 0; i < 6U; i++) value = value * 33U ^ mac[i];
	return value;
}

static void
sockaddr_value(struct sockaddr *address, uint32_t value)
{
	struct sockaddr_in *inet = (struct sockaddr_in *)address;
	memset(address, 0, sizeof(*address)); inet->sin_family = AF_INET; inet->sin_addr.s_addr = value;
}

static void
delete_dynamic_default(int descriptor, uint32_t ifindex)
{
	struct rtentry entry;
	unsigned ordinal = 0;
	for (;;) {
		memset(&entry, 0, sizeof(entry)); entry.rt_index = ordinal;
		if (ioctl(descriptor, SIOCGRTENTRY, &entry) != 0) break;
		if ((entry.rt_flags & RTF_DYNAMIC) != 0 && entry.rt_ifindex == ifindex &&
		    ((struct sockaddr_in *)&entry.rt_dst)->sin_addr.s_addr == 0 &&
		    ((struct sockaddr_in *)&entry.rt_genmask)->sin_addr.s_addr == 0) {
			(void)ioctl(descriptor, SIOCDELRT, &entry); continue;
		}
		ordinal++;
	}
}

static int
write_resolver(const char *interface, const struct dhcp_lease *lease)
{
	char buffer[256], address[16]; size_t used = 0; unsigned index;
	int descriptor;
	used += (size_t)snprintf(buffer + used, sizeof(buffer) - used,
	    "# Generated by dhcpcd for %s\n", interface);
	for (index = 0; index < lease->dns_count && used < sizeof(buffer); index++) {
		struct in_addr value = { lease->dns_servers[index] };
		inet_ntop(AF_INET, &value, address, sizeof(address));
		used += (size_t)snprintf(buffer + used, sizeof(buffer) - used,
		    "nameserver %s\n", address);
	}
	if (used >= sizeof(buffer)) return -1;
	descriptor = open("/etc/resolv.conf", O_WRONLY | O_CREAT | O_TRUNC, 0644);
	if (descriptor < 0) return -1;
	{ size_t offset = 0; while (offset < used) { ssize_t count = write(descriptor, buffer + offset, used - offset); if (count <= 0) { close(descriptor); return -1; } offset += (size_t)count; } }
	return close(descriptor);
}

static int usage(void) { puts("usage: dhcpcd [-v] [-t seconds] [interface]"); return 2; }

int
main(int argc, char **argv)
{
	struct snapshot saved;
	struct ifreq request;
	struct sockaddr_in client, server, source;
	struct dhcp_lease offer, lease;
	struct timeval receive_timeout = { 1, 0 };
	uint8_t packet[600], mac[6];
	char interface[IFNAMSIZ] = {0}, text[16];
	uint32_t xid, timeout_seconds = 15, ifindex;
	uint64_t deadline;
	size_t packet_length;
	int control, socket_, verbose = 0, arg = 1, got_offer = 0, got_ack = 0;

	while (arg < argc && argv[arg][0] == '-') {
		if (strcmp(argv[arg], "-v") == 0) { verbose = 1; arg++; }
		else if (strcmp(argv[arg], "-t") == 0 && arg + 1 < argc) { char *end; unsigned long v = strtoul(argv[arg + 1], &end, 10); if (*end != '\0' || v == 0 || v > 3600U) return usage(); timeout_seconds = (uint32_t)v; arg += 2; }
		else return usage();
	}
	if (arg + 1 < argc) return usage();
	if (arg < argc) { if (strlen(argv[arg]) >= IFNAMSIZ) return usage(); strcpy(interface, argv[arg]); }
	control = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
	if (control < 0) { printf("dhcpcd: socket: %s\n", strerror(errno)); return 1; }
	if (interface[0] == '\0' && select_interface(control, interface) != 0) { printf("dhcpcd: select interface: %s\n", strerror(errno)); close(control); return 1; }
	if (if_request(control, interface, SIOCGIFFLAGS, &request) != 0) goto fail;
	saved.flags = request.ifr_flags;
	(void)get_address(control, interface, SIOCGIFADDR, &saved.address);
	(void)get_address(control, interface, SIOCGIFNETMASK, &saved.mask);
	(void)get_address(control, interface, SIOCGIFBRDADDR, &saved.broadcast);
	request.ifr_flags |= IFF_UP;
	if (ioctl(control, SIOCSIFFLAGS, &request) != 0 ||
	    if_request(control, interface, SIOCGIFHWADDR, &request) != 0 ||
	    netutil_ifindex(control, interface, &ifindex) != 0) goto fail;
	memcpy(mac, request.ifr_hwaddr, sizeof(mac));
	socket_ = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
	if (socket_ < 0) goto fail;
	{ int enabled = 1; if (setsockopt(socket_, SOL_SOCKET, SO_BINDTODEVICE, interface, (socklen_t)strlen(interface) + 1U) != 0 || setsockopt(socket_, SOL_SOCKET, SO_BROADCAST, &enabled, sizeof(enabled)) != 0 || setsockopt(socket_, SOL_SOCKET, SO_RCVTIMEO, &receive_timeout, sizeof(receive_timeout)) != 0) goto socket_fail; }
	memset(&client, 0, sizeof(client)); client.sin_family = AF_INET; client.sin_port = htons(68); client.sin_addr.s_addr = INADDR_ANY;
	if (bind(socket_, (struct sockaddr *)&client, sizeof(client)) != 0) goto socket_fail;
	memset(&server, 0, sizeof(server)); server.sin_family = AF_INET; server.sin_port = htons(67); server.sin_addr.s_addr = INADDR_BROADCAST;
	xid = transaction_id(mac); deadline = netutil_monotonic_us() + (uint64_t)timeout_seconds * 1000000U;
	while (netutil_monotonic_us() < deadline && !got_offer) {
		if (dhcp_build(packet, sizeof(packet), &packet_length, DHCP_DISCOVER, xid, mac, 0, 0) != 0 || sendto(socket_, packet, packet_length, 0, (struct sockaddr *)&server, sizeof(server)) < 0) goto socket_fail;
		if (verbose) printf("dhcpcd: %s: broadcasting discover\n", interface);
		for (;;) { socklen_t slen = sizeof(source); ssize_t count = recvfrom(socket_, packet, sizeof(packet), 0, (struct sockaddr *)&source, &slen); if (count < 0) break; if (source.sin_port == htons(67) && dhcp_parse(packet, (size_t)count, xid, mac, &offer) == 0 && offer.message_type == DHCP_OFFER && offer.server_identifier != 0) { got_offer = 1; break; } }
	}
	if (!got_offer) { errno = ETIMEDOUT; goto socket_fail; }
	{ struct in_addr value = { offer.address }; inet_ntop(AF_INET, &value, text, sizeof(text)); printf("dhcpcd: %s: offered %s", interface, text); value.s_addr = offer.server_identifier; inet_ntop(AF_INET, &value, text, sizeof(text)); printf(" by %s\n", text); }
	while (netutil_monotonic_us() < deadline && !got_ack) {
		if (dhcp_build(packet, sizeof(packet), &packet_length, DHCP_REQUEST, xid, mac, offer.address, offer.server_identifier) != 0 || sendto(socket_, packet, packet_length, 0, (struct sockaddr *)&server, sizeof(server)) < 0) goto socket_fail;
		for (;;) { socklen_t slen = sizeof(source); ssize_t count = recvfrom(socket_, packet, sizeof(packet), 0, (struct sockaddr *)&source, &slen); if (count < 0) break; if (source.sin_port == htons(67) && dhcp_parse(packet, (size_t)count, xid, mac, &lease) == 0) { if (lease.message_type == DHCP_NAK) { errno = EACCES; goto socket_fail; } if (lease.message_type == DHCP_ACK && lease.netmask != 0) { got_ack = 1; break; } } }
	}
	if (!got_ack) { errno = ETIMEDOUT; goto socket_fail; }
	{ struct in_addr value;
	  value.s_addr = lease.netmask; if (set_address(control, interface, SIOCSIFNETMASK, value) != 0) goto socket_fail;
	  value.s_addr = lease.broadcast; if (set_address(control, interface, SIOCSIFBRDADDR, value) != 0) goto socket_fail;
	  value.s_addr = lease.address; if (set_address(control, interface, SIOCSIFADDR, value) != 0) goto socket_fail; }
	delete_dynamic_default(control, ifindex);
	if (lease.router_count != 0) { struct rtentry route; memset(&route, 0, sizeof(route)); route.rt_flags = RTF_UP | RTF_GATEWAY | RTF_DYNAMIC; route.rt_ifindex = ifindex; sockaddr_value(&route.rt_dst, 0); sockaddr_value(&route.rt_genmask, 0); sockaddr_value(&route.rt_gateway, lease.routers[0]); if (ioctl(control, SIOCADDRT, &route) != 0) goto socket_fail; }
	{ struct in_addr value = { lease.address }; unsigned prefix = 0; struct in_addr mask = { lease.netmask }; netutil_mask_prefix(mask, &prefix); inet_ntop(AF_INET, &value, text, sizeof(text)); printf("dhcpcd: %s: address %s/%u\n", interface, text, prefix); }
	if (lease.router_count != 0) { struct in_addr value = { lease.routers[0] }; inet_ntop(AF_INET, &value, text, sizeof(text)); printf("dhcpcd: %s: default route %s\n", interface, text); }
	if (lease.dns_count != 0) { unsigned i; for (i = 0; i < lease.dns_count; i++) { struct in_addr value = { lease.dns_servers[i] }; inet_ntop(AF_INET, &value, text, sizeof(text)); printf("dhcpcd: %s: dns %s\n", interface, text); } if (write_resolver(interface, &lease) != 0) printf("dhcpcd: warning: cannot write /etc/resolv.conf: %s\n", strerror(errno)); }
	printf("dhcpcd: %s: lease %u seconds\n", interface, lease.lease_time);
	close(socket_); close(control); return 0;
socket_fail:
	printf("dhcpcd: %s: %s\n", interface, strerror(errno)); close(socket_);
	(void)set_address(control, interface, SIOCSIFNETMASK, saved.mask); (void)set_address(control, interface, SIOCSIFBRDADDR, saved.broadcast); (void)set_address(control, interface, SIOCSIFADDR, saved.address); if (if_request(control, interface, SIOCGIFFLAGS, &request) == 0) { request.ifr_flags = saved.flags; (void)ioctl(control, SIOCSIFFLAGS, &request); }
	close(control); return 1;
fail:
	printf("dhcpcd: %s: %s\n", interface, strerror(errno)); close(control); return 1;
}
