/* -*- coding: utf-8; tab-width: 8; indent-tabs-mode: t; -*- */

/*
 * zedBSD
 * Copyright (C) 2026 Awe Morris
 *
 * SPDX-License-Identifier: Zlib
 */

/*
 * Exercises networkd's global managed-WLAN policy state.
 */

#include "userland/base/networkd/managed-wlan.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void expect(int, const char *);
static struct rtm_ifinfo make_event(uint64_t, uint64_t, uint32_t, uint32_t, uint32_t);
static struct networkd_managed_l3 make_l3_snapshot(uint32_t);
static void test_policy_lifetime(void);
static void test_l3_ownership(void);
static void test_route_events(void);

static int fixture_errno;

/*
 * Provides the test libc error slot.
 */
int *
__libc_errno_location(
	void)
{
	/* Returns the deterministic fixture error slot. */
	return &fixture_errno;
}

/*
 * Runs the managed-WLAN policy fixture.
 */
int
main(
	void)
{
	/* Exercises each independent policy boundary. */
	test_policy_lifetime();
	test_l3_ownership();
	test_route_events();

	/* Reports successful completion. */
	puts("networkd-managed-wlan-test: PASS");
	return 0;
}

/* Requires one fixture condition. */
static void
expect(
	int condition,
	const char *message)
{
	/* Terminates the fixture at the first failed invariant. */
	if (!condition) {
		fprintf(stderr, "networkd-managed-wlan-test: %s\n", message);
		exit(1);
	}
}

/* Constructs one canonical fixed-width interface event. */
static struct rtm_ifinfo
make_event(
	uint64_t sequence,
	uint64_t generation,
	uint32_t ifindex,
	uint32_t transition,
	uint32_t flags)
{
	struct rtm_ifinfo record;

	/* Initializes the complete event ABI record. */
	memset(&record, 0, sizeof(record));
	record.rtm_version = RTM_VERSION;
	record.rtm_type = RTM_IFINFO;
	record.rtm_length = sizeof(record);
	record.rtm_sequence = sequence;
	record.rtm_device_generation = generation;
	record.rtm_ifindex = ifindex;
	record.rtm_transition = transition;
	record.rtm_flags = flags;

	/* Returns the completed event. */
	return record;
}

/* Constructs one exact owned L3 snapshot. */
static struct networkd_managed_l3
make_l3_snapshot(
	uint32_t ifindex)
{
	static const char resolver[] =
	    "# Generated by dhcpc for wlan0\nnameserver 192.0.2.53\n";
	struct networkd_managed_l3 snapshot;

	/* Initializes the address, route, and resolver ownership token. */
	memset(&snapshot, 0, sizeof(snapshot));
	snapshot.address = 0x020200c0U;
	snapshot.netmask = 0x00ffffffU;
	snapshot.broadcast = 0xff0200c0U;
	snapshot.ipv4_owned = 1;
	snapshot.default_route_present = 1;
	snapshot.default_route_owned = 1;
	snapshot.default_route.flags = RTF_UP | RTF_GATEWAY | RTF_DYNAMIC;
	snapshot.default_route.ifindex = ifindex;
	snapshot.default_route.gateway = 0x010200c0U;
	snapshot.resolver_present = 1;
	snapshot.resolver_owned = 1;
	snapshot.resolver_length = sizeof(resolver) - 1U;
	memcpy(snapshot.resolver, resolver, snapshot.resolver_length);

	/* Returns the completed ownership token. */
	return snapshot;
}

/* Exercises owner replacement and the one-connection invariant. */
static void
test_policy_lifetime(
	void)
{
	static const char first_ssid[] = "first profile";
	static const char second_ssid[] = "second profile";
	struct networkd_managed_wlan managed;

	/* Initializes the unique global policy in disabled state. */
	networkd_managed_wlan_init(&managed);
	expect(managed.state == NETWORKD_WLAN_DISABLED &&
	    !managed.owner_valid && managed.connection.interface[0] == '\0',
	    "initial disabled state");

	/* Captures and replaces only an authenticated inactive policy owner. */
	expect(networkd_managed_wlan_enable(&managed, (uid_t)1000) == 0,
	    "enable user policy");
	expect(managed.state == NETWORKD_WLAN_AUTO_SEARCHING &&
	    networkd_managed_wlan_owner_matches(&managed, (uid_t)1000),
	    "first active owner");
	expect(networkd_managed_wlan_enable(&managed, (uid_t)1001) == 0,
	    "replace inactive owner");
	expect(!networkd_managed_wlan_owner_matches(&managed, (uid_t)1000) &&
	    networkd_managed_wlan_owner_matches(&managed, (uid_t)1001),
	    "replacement owner identity");

	/* Retains the first profile/radio pair selected by stable outer ordering. */
	expect(networkd_managed_wlan_begin_connect(
	    &managed,
	    "wlan2",
	    12U,
	    40U,
	    first_ssid,
	    sizeof(first_ssid) - 1U) == 0,
	    "begin first selected connection");
	expect(managed.state == NETWORKD_WLAN_CONNECTING &&
	    strcmp(managed.connection.interface, "wlan2") == 0 &&
	    managed.connection.ssid_length == sizeof(first_ssid) - 1U &&
	    memcmp(managed.connection.ssid, first_ssid,
	    sizeof(first_ssid) - 1U) == 0,
	    "selected profile and radio retained");

	/* Rejects a second profile/radio even if it would otherwise rank later. */
	fixture_errno = 0;
	expect(networkd_managed_wlan_begin_connect(
	    &managed,
	    "wlan0",
	    10U,
	    40U,
	    second_ssid,
	    sizeof(second_ssid) - 1U) == -1 && fixture_errno == EBUSY,
	    "one global connection");
	expect(strcmp(managed.connection.interface, "wlan2") == 0 &&
	    memcmp(managed.connection.ssid, first_ssid,
	    sizeof(first_ssid) - 1U) == 0,
	    "failed replacement preserves first selection");

	/* Prevents owner or disable transitions from losing an active token. */
	fixture_errno = 0;
	expect(networkd_managed_wlan_enable(&managed, (uid_t)0) == -1 &&
	    fixture_errno == EBUSY,
	    "active owner replacement refused");
	fixture_errno = 0;
	expect(networkd_managed_wlan_disable(&managed) == -1 &&
	    fixture_errno == EBUSY,
	    "active disable refused");

	/* Enters explicit manual-disconnect state after external retirement. */
	expect(networkd_managed_wlan_finish_connection(
	    &managed,
	    NETWORKD_WLAN_MANUAL_DISCONNECTED) == 0,
	    "finish manual connection");
	expect(managed.state == NETWORKD_WLAN_MANUAL_DISCONNECTED &&
	    managed.connection.interface[0] == '\0' &&
	    networkd_managed_wlan_owner_matches(&managed, (uid_t)1001),
	    "manual disconnect preserves owner only");

	/* Admits a saved manual profile through explicit first-radio selection. */
	expect(networkd_managed_wlan_begin_connect(
	    &managed,
	    "wlan0",
	    10U,
	    50U,
	    second_ssid,
	    sizeof(second_ssid) - 1U) == 0,
	    "begin explicit manual profile");
	expect(strcmp(managed.connection.interface, "wlan0") == 0 &&
	    memcmp(managed.connection.ssid, second_ssid,
	    sizeof(second_ssid) - 1U) == 0,
	    "manual profile selection retained");
	expect(networkd_managed_wlan_finish_connection(
	    &managed,
	    NETWORKD_WLAN_MANUAL_DISCONNECTED) == 0,
	    "retire explicit manual profile");

	/* Clears the policy owner only after all connection state is idle. */
	expect(networkd_managed_wlan_disable(&managed) == 0,
	    "disable inactive policy");
	expect(managed.state == NETWORKD_WLAN_DISABLED &&
	    !managed.owner_valid && managed.owner_uid == (uid_t)0,
	    "disable clears owner");
	expect(networkd_managed_wlan_enable(&managed, (uid_t)0) == 0 &&
	    networkd_managed_wlan_owner_matches(&managed, (uid_t)0),
	    "root policy owner");
}

/* Exercises exact L3 ownership and fail-closed cleanup planning. */
static void
test_l3_ownership(
	void)
{
	static const char ssid[] = "test network";
	struct networkd_managed_wlan managed;
	struct networkd_managed_l3_cleanup cleanup;
	struct networkd_managed_l3 snapshot;
	struct networkd_managed_l3 current;

	/* Establishes one connected policy with an exact L3 token. */
	networkd_managed_wlan_init(&managed);
	expect(networkd_managed_wlan_enable(&managed, (uid_t)1000) == 0,
	    "enable L3 policy");
	expect(networkd_managed_wlan_begin_connect(
	    &managed,
	    "wlan0",
	    7U,
	    10U,
	    ssid,
	    sizeof(ssid) - 1U) == 0,
	    "begin L3 connection");
	snapshot = make_l3_snapshot(7U);
	expect(networkd_managed_wlan_commit_l3(&managed, &snapshot) == 0,
	    "commit exact L3 token");
	expect(managed.state == NETWORKD_WLAN_CONNECTED &&
	    managed.connection.owns_l3,
	    "connected L3 state");

	/* Authorizes cleanup only for the exact current owned values. */
	current = snapshot;
	expect(networkd_managed_wlan_plan_l3_cleanup(
	    &managed,
	    7U,
	    &current,
	    &cleanup) == 0,
	    "exact L3 cleanup plan");
	expect(cleanup.clear_ipv4 && cleanup.delete_default_route &&
	    cleanup.unlink_resolver && !cleanup.degraded,
	    "exact L3 cleanup operations");

	/* Preserves an address which another actor changed. */
	current = snapshot;
	current.address++;
	fixture_errno = 0;
	expect(networkd_managed_wlan_plan_l3_cleanup(
	    &managed,
	    7U,
	    &current,
	    &cleanup) == -1 && fixture_errno == ESTALE,
	    "external IPv4 change");
	expect(!cleanup.clear_ipv4 && cleanup.delete_default_route &&
	    cleanup.unlink_resolver && cleanup.degraded,
	    "changed IPv4 preserved");

	/* Preserves a default route which another actor changed. */
	current = snapshot;
	current.default_route.gateway++;
	fixture_errno = 0;
	expect(networkd_managed_wlan_plan_l3_cleanup(
	    &managed,
	    7U,
	    &current,
	    &cleanup) == -1 && fixture_errno == ESTALE,
	    "external route change");
	expect(cleanup.clear_ipv4 && !cleanup.delete_default_route &&
	    cleanup.unlink_resolver && cleanup.degraded,
	    "changed route preserved");

	/* Preserves resolver contents which another actor changed. */
	current = snapshot;
	current.resolver[0] = '!';
	fixture_errno = 0;
	expect(networkd_managed_wlan_plan_l3_cleanup(
	    &managed,
	    7U,
	    &current,
	    &cleanup) == -1 && fixture_errno == ESTALE,
	    "external resolver change");
	expect(cleanup.clear_ipv4 && cleanup.delete_default_route &&
	    !cleanup.unlink_resolver && cleanup.degraded,
	    "changed resolver preserved");

	/* Preserves every resource after an interface identity change. */
	current = snapshot;
	fixture_errno = 0;
	expect(networkd_managed_wlan_plan_l3_cleanup(
	    &managed,
	    8U,
	    &current,
	    &cleanup) == -1 && fixture_errno == ENODEV,
	    "ifindex reuse");
	expect(!cleanup.clear_ipv4 && !cleanup.delete_default_route &&
	    !cleanup.unlink_resolver && cleanup.degraded,
	    "reused interface resources preserved");
}

/* Exercises exact event identity and RF recovery state transitions. */
static void
test_route_events(
	void)
{
	static const char ssid[] = "test network";
	struct networkd_managed_wlan managed;
	struct networkd_managed_l3 snapshot;
	struct rtm_ifinfo notice;
	enum networkd_managed_wlan_action action;

	/* Establishes one selected and connected global interface. */
	networkd_managed_wlan_init(&managed);
	expect(networkd_managed_wlan_enable(&managed, (uid_t)1000) == 0,
	    "enable event policy");
	expect(networkd_managed_wlan_begin_connect(
	    &managed,
	    "wlan0",
	    7U,
	    10U,
	    ssid,
	    sizeof(ssid) - 1U) == 0,
	    "begin event connection");
	snapshot = make_l3_snapshot(7U);
	expect(networkd_managed_wlan_commit_l3(&managed, &snapshot) == 0,
	    "commit event connection");

	/* Ignores floor and unrelated-interface events. */
	notice = make_event(10U, 31U, 7U, RTM_IFINFO_CARRIER_DOWN, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_NONE, "floor event ignored");
	notice = make_event(11U, 31U, 9U, RTM_IFINFO_CARRIER_DOWN, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_NONE,
	    "unselected radio event ignored");

	/* Coalesces one matching carrier loss into one recovery operation. */
	notice = make_event(12U, 31U, 7U, RTM_IFINFO_CARRIER_DOWN, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_RECOVER &&
	    managed.state == NETWORKD_WLAN_RECONNECTING,
	    "one RF recovery");
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_NONE,
	    "duplicate carrier loss coalesced");
	networkd_managed_wlan_recovery_complete(&managed, 1);
	expect(managed.state == NETWORKD_WLAN_CONNECTED &&
	    managed.connection.owns_l3 &&
	    managed.connection.ssid_length == sizeof(ssid) - 1U,
	    "successful recovery preserves connection");

	/* Returns failed recovery to auto search without retaining connection data. */
	notice = make_event(13U, 31U, 7U, RTM_IFINFO_CARRIER_DOWN, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_RECOVER,
	    "second physical loss");
	networkd_managed_wlan_recovery_complete(&managed, 0);
	expect(managed.state == NETWORKD_WLAN_AUTO_SEARCHING &&
	    networkd_managed_wlan_owner_matches(&managed, (uid_t)1000) &&
	    managed.connection.interface[0] == '\0' &&
	    managed.connection.ssid_length == 0U &&
	    managed.connection.l3.resolver_length == 0U,
	    "failed recovery resumes owner auto search");

	/* Requires a resnapshot after overflow only while policy is enabled. */
	notice = make_event(
	    14U,
	    32U,
	    7U,
	    RTM_IFINFO_CARRIER_DOWN,
	    RTM_IFINFO_F_OVERFLOW);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_RESNAPSHOT,
	    "enabled overflow resnapshot");
	expect(networkd_managed_wlan_disable(&managed) == 0,
	    "disable after recovery failure");
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_NONE,
	    "disabled overflow ignored");

	/* Binds one device generation and rejects stale-generation removal. */
	expect(networkd_managed_wlan_enable(&managed, (uid_t)1000) == 0,
	    "reenable event policy");
	expect(networkd_managed_wlan_begin_connect(
	    &managed,
	    "wlan0",
	    7U,
	    20U,
	    ssid,
	    sizeof(ssid) - 1U) == 0,
	    "restart event connection");
	snapshot = make_l3_snapshot(7U);
	expect(networkd_managed_wlan_commit_l3(&managed, &snapshot) == 0,
	    "recommit event connection");
	notice = make_event(21U, 41U, 7U, RTM_IFINFO_CARRIER_UP, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_NONE &&
	    managed.connection.device_generation == 41U,
	    "bind device generation");
	notice = make_event(22U, 99U, 7U, RTM_IFINFO_REMOVAL, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_NONE,
	    "stale generation removal ignored");
	notice = make_event(23U, 41U, 7U, RTM_IFINFO_REMOVAL, 0U);
	action = networkd_managed_wlan_event(&managed, &notice);
	expect(action == NETWORKD_WLAN_ACTION_RETIRE,
	    "matching removal retires connection");
	expect(networkd_managed_wlan_finish_connection(
	    &managed,
	    NETWORKD_WLAN_AUTO_SEARCHING) == 0 &&
	    managed.state == NETWORKD_WLAN_AUTO_SEARCHING,
	    "removal returns to global discovery");
}
