# Shared explicit production native Vulkan sources; sourced by bounded WS141 host fixtures.
ws141_vulkan_sources="
src/drivers/gpu/bcm2711/vulkan-object.c
src/drivers/gpu/bcm2711/vulkan-session.c
src/drivers/gpu/bcm2711/vulkan-stream.c
src/drivers/gpu/bcm2711/vulkan-dispatch.c
src/drivers/gpu/bcm2711/vulkan-device.c
src/drivers/gpu/bcm2711/vulkan-sync.c
src/drivers/gpu/bcm2711/vulkan-queue.c
src/drivers/gpu/bcm2711/render-worker.c
src/drivers/gpu/bcm2711/render-runtime.c
src/drivers/gpu/bcm2711/vulkan-query.c
src/drivers/gpu/bcm2711/vulkan-memory.c
src/drivers/gpu/bcm2711/vulkan-resource.c
src/drivers/gpu/bcm2711/vulkan-input.c
src/drivers/gpu/bcm2711/vulkan-layout.c
src/drivers/gpu/bcm2711/vulkan-layout-compat.c
src/drivers/gpu/bcm2711/vulkan-descriptor-pool.c
src/drivers/gpu/bcm2711/vulkan-descriptor-sets.c
src/drivers/gpu/bcm2711/vulkan-descriptor-update.c
src/drivers/gpu/bcm2711/vulkan-target.c
src/drivers/gpu/bcm2711/vulkan-pipeline-build.c
src/drivers/gpu/bcm2711/vulkan-pipeline-state.c
src/drivers/gpu/bcm2711/vulkan-pipeline.c
src/drivers/gpu/bcm2711/vulkan-pipeline-decode.c
src/drivers/gpu/bcm2711/vulkan-command-pool.c
src/drivers/gpu/bcm2711/vulkan-command-batch.c
src/drivers/gpu/bcm2711/vulkan-command-buffer.c
src/drivers/gpu/bcm2711/vulkan-barrier.c
src/drivers/gpu/bcm2711/vulkan-barrier-decode.c
src/drivers/gpu/bcm2711/vulkan-barrier-validate.c
src/drivers/gpu/bcm2711/vulkan-record.c
src/drivers/gpu/bcm2711/vulkan-record-decode.c
src/drivers/gpu/bcm2711/vulkan-record-validate.c
src/drivers/gpu/bcm2711/vulkan-draw.c
src/drivers/gpu/bcm2711/vulkan-draw-validate.c
src/drivers/gpu/bcm2711/vulkan-prepared.c
src/drivers/gpu/bcm2711/vulkan-uniform.c
src/drivers/gpu/bcm2711/native-viewport.c
src/drivers/gpu/bcm2711/native-storage.c
src/drivers/gpu/bcm2711/native-shader.c
src/drivers/gpu/bcm2711/native-texture.c
src/drivers/gpu/bcm2711/vulkan-native-draw.c
src/drivers/gpu/bcm2711/vulkan-native-bin.c
src/drivers/gpu/bcm2711/native-bin.c
src/drivers/gpu/bcm2711/native-pass.c
src/drivers/gpu/bcm2711/vulkan-native-pass.c
src/drivers/gpu/bcm2711/vulkan-native-execute.c
src/drivers/gpu/bcm2711/vulkan-native-job.c
src/drivers/gpu/bcm2711/native-colour.c
src/drivers/gpu/bcm2711/vulkan-buffer-copy.c
src/drivers/gpu/bcm2711/vulkan-transfer.c
src/drivers/gpu/bcm2711/vulkan-native-image.c
src/drivers/gpu/bcm2711/shader.c
src/drivers/gpu/bcm2711/shader-analyze.c
src/drivers/gpu/bcm2711/shader-lower.c
src/drivers/gpu/bcm2711/shader-output.c
src/drivers/gpu/bcm2711/qpu.c
src/drivers/gpu/i915/compiler/spirv.c
src/drivers/gpu/i915/render/codec.c
"
