version=1
mode=extended
anchor=zedbsd-port-v1:pci:0000:00:02.0:dp:TC2
place=zedbsd-port-v1:pci:0000:00:02.0:edp:A 0 0
place=zedbsd-port-v1:pci:0000:00:02.0:dp:TC2 0 0
off=zedbsd-port-v1:pci:0000:00:02.0:edp:A
