#!/bin/sh
# ws177-p045 and p046 (case R): networkd's and dhcpc's IPv6 edge cases on a zedBSD guest of
# plan/ws130/tests/config-amd64-ipv6.mk, the segment of ws130's ipv6-p008-dnsmasq.sh: a second USB network adapter on
# a host tap, on a bridge with a veth into the network namespace zb6, where dnsmasq sends Router Advertisements (M
# and O, the prefix fd00:6::/64 with A, and here a default router for 600 seconds, the RDNSS fd00:6::53 and the
# search list zb6.test) and leases fd00:6::100-1ff for two minutes.  The first adapter stays on QEMU's user network
# (its router fe80::2 advertises fec0::/64 and a default route) for SSH.
#  1. The second interface (MAC 52:54:00:33:00:02) up; networkd restarted; a stateful lease and a SLAAC address.
#  2. p045: route -6 show has one default route only (two routers advertise one: the preferred interface's).
#  3. p045: resolv.conf rewritten as dhcpc's DHCPv4 does ("# Generated by dhcpc for IF1", nameserver 10.0.2.3):
#     within 15 seconds networkd puts "nameserver fd00:6::53" back after it and the first line stays.
#  4. p046: /var/db/dhcpc/IF2.dhcp6 has "obtained", "t2" and "valid" lines.
#  5. p046: the record's server made another and T2 past (t2 0): dhcpc -6 -v IF2 says "rebind taken", dnsmasq's
#     log has a DHCPREBIND, and the record names dnsmasq's server again.
#  6. p046: an address fd00:6::77/128 put on IF2 by hand and named in the record, the lease made over (valid 1,
#     obtained 1): dhcpc -6 -v IF2 solicits, says "previous address fd00:6::77/128 removed", and ifconfig has no
#     fd00:6::77.
#  7. p046: dhcpc -6 -D -v IF2: "decline ADDRESS/128 answered" and another leased address (dnsmasq's DHCPDECLINE).
#  8. p046: dhcpc -6 -r -v IF2: "release ADDRESS/128 answered", no "dhcp" address left, the record gone
#     (dnsmasq's DHCPRELEASE).
#  9. p045: the stable SLAAC address S of IF2 taken off and given to the namespace (nodad): within 25 seconds the next
#     advertisement's S fails duplicate address detection and networkd makes another stable address (not S).
# 10. p045: QMP set_link net1 off: when the guest sees the carrier go (IF2 without RUNNING), its "autoconf" addresses
#     go and no default route is on IF2; set_link on brings them back.  When the guest does not see the carrier
#     (usb-net may not tell it), the step is "not judged".
# 11. IPv4 on the first adapter unchanged: ping -c 1 10.0.2.2.
# PASS: every "ok" line and the last line ipv6-r-dnsmasq: PASS ("not judged" lines are not failures).  The host's part
# needs sudo (ip, dnsmasq); the guest runs under its own runtime directory, and both are taken down at the end.
# net commit's removal of static IPv6 addresses and routes (p045, backlog-p1 17) is host-only: net's console has no
# IPv6 grammar to make a candidate drop one (plan/ws177/tests/host-ipv6-r.sh).
#
#   plan/tools/guest/test-image.sh plan/ws130/tests/config-amd64-ipv6.mk BUILD
#   plan/ws177/tests/ipv6-r-dnsmasq.sh IMAGE [OUTDIR]
# Each run gets a new directory behind OUTDIR (plan/tools/fresh-out.sh); nothing on the host is removed.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
set -u
cd "$(dirname -- "$0")/../../.."
image=${1:?usage: ipv6-r-dnsmasq.sh IMAGE [OUTDIR]}
out=${2:-build/ws177-ipv6-r-dnsmasq}
. plan/tools/fresh-out.sh
fresh_out "$out"
GUEST_RUNTIME=$(pwd)/$out/run
export GUEST_RUNTIME
guest() { timeout 120 python3 plan/tools/guest/guest.py run "$1" 2>&1 | tr -d '\r'; }
status=0
ok() { echo "ok: $1"; }
bad() { echo "FAIL: $1"; status=1; }
dnsmasq_pid=

# QMP: one command to the guest's monitor.
qmp() {
	python3 - "$GUEST_RUNTIME/qmp.sock" "$1" <<'EOF'
import json, socket, sys
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect(sys.argv[1])
f = s.makefile("rw")
f.readline()
for command in ({"execute": "qmp_capabilities"}, json.loads(sys.argv[2])):
	f.write(json.dumps(command) + "\n")
	f.flush()
	while True:
		answer = json.loads(f.readline())
		if "return" in answer or "error" in answer:
			print(json.dumps(answer))
			break
EOF
}

# The host's segment taken down: dnsmasq, the guest, the links and the namespace.
teardown() {
	python3 plan/tools/guest/guest.py stop >/dev/null 2>&1
	[ -n "$dnsmasq_pid" ] && sudo kill "$dnsmasq_pid" 2>/dev/null
	sudo ip link del zbtap0 2>/dev/null
	sudo ip link del zbbr0 2>/dev/null
	sudo ip netns del zb6 2>/dev/null
}
trap teardown EXIT

# The segment: a bridge with the tap and a veth into the namespace, fd00:6::1 there.
teardown
sudo ip netns add zb6 || exit 1
sudo ip link add zbbr0 type bridge
sudo sysctl -q -w net.ipv6.conf.zbbr0.disable_ipv6=1
sudo ip link set zbbr0 up
sudo ip tuntap add dev zbtap0 mode tap user "$(id -un)"
sudo sysctl -q -w net.ipv6.conf.zbtap0.disable_ipv6=1
sudo ip link set zbtap0 master zbbr0 up
sudo ip link add zbv0 type veth peer name zbv1
sudo sysctl -q -w net.ipv6.conf.zbv0.disable_ipv6=1
sudo ip link set zbv0 master zbbr0 up
sudo ip link set zbv1 netns zb6
sudo ip -n zb6 link set lo up
sudo ip -n zb6 link set zbv1 up
sudo ip -n zb6 addr add fd00:6::1/64 dev zbv1 nodad

# dnsmasq: advertisements every 10 seconds with a router lifetime of 600, stateful DHCPv6, its DNS server and search list.
sudo ip netns exec zb6 /usr/sbin/dnsmasq --no-daemon --conf-file=/dev/null --port=0 --interface=zbv1 \
	--bind-interfaces --enable-ra --ra-param=zbv1,10,600 --dhcp-range=fd00:6::100,fd00:6::1ff,slaac,64,2m \
	--dhcp-option=option6:dns-server,[fd00:6::53] --dhcp-option=option6:domain-search,zb6.test --leasefile-ro \
	--log-dhcp --log-facility=- > "$out/dnsmasq.log" 2>&1 &
dnsmasq_pid=$!

# The guest with the second adapter on the tap.
python3 plan/tools/guest/guest.py start "$image" --qemu-extra "-netdev tap,id=net1,ifname=zbtap0,script=no,downscript=no \
-device usb-net,bus=xhci.0,port=5,id=ecm1,netdev=net1,mac=52:54:00:33:00:02" || exit 1
python3 plan/tools/guest/guest.py wait --timeout 240 || { bad "the guest did not come up"; exit 1; }

# 1. The interfaces, the second up, networkd started again; its lease and SLAAC address.
iface=$(guest "ifconfig -a | awk '/^[a-z]+[0-9]+:/ {name = substr(\$1, 1, length(\$1) - 1)} /ether 52:54:00:33:00:02/ {print name}'" |
    tail -1)
first=$(guest "ifconfig -a | sed -n 's/^\([a-z]*[0-9]*\): flags=.*UP.*/\1/p' | grep -v '^lo' | grep -v '^$iface\$' | head -1" | tail -1)
echo "interfaces: $first (user network), $iface (dnsmasq)"
[ -n "$iface" ] && ok "the second adapter: $iface" || { bad "no second adapter"; exit 1; }
guest "ifconfig $iface up; sleep 2; service restart networkd >/dev/null 2>&1; sleep 20; echo waited" >/dev/null
guest "ifconfig $iface" > "$out/ifconfig-1.txt"
cat "$out/ifconfig-1.txt"
grep -q 'inet6 fd00:6::1[0-9a-f][0-9a-f] prefixlen 128 dhcp$' "$out/ifconfig-1.txt" && ok "the DHCPv6 address" ||
    bad "DHCPv6 address"
stable=$(sed -n 's/.*inet6 \(fd00:6::[0-9a-f:]*\) prefixlen 64 autoconf$/\1/p' "$out/ifconfig-1.txt" | head -1)
[ -n "$stable" ] && ok "the stable SLAAC address: $stable" || bad "SLAAC address"

# 2. One default route.
guest "route -6 show" > "$out/route-2.txt"
cat "$out/route-2.txt"
defaults=$(grep -c '^default' "$out/route-2.txt")
[ "$defaults" = 1 ] && ok "one IPv6 default route" || bad "IPv6 default routes: $defaults"

# 3. The RDNSS server put back after DHCPv4's rewrite, its first line kept.
guest "printf '# Generated by dhcpc for $first\nnameserver 10.0.2.3\n' > /etc/resolv.conf.t && mv /etc/resolv.conf.t /etc/resolv.conf; sleep 15; cat /etc/resolv.conf" > "$out/resolv-3.txt"
cat "$out/resolv-3.txt"
head -1 "$out/resolv-3.txt" | grep -q "^# Generated by dhcpc for $first" && ok "resolv.conf: dhcpc's first line kept" ||
    bad "resolv.conf: first line"
grep -q '^nameserver 10.0.2.3$' "$out/resolv-3.txt" && grep -q '^nameserver fd00:6::53$' "$out/resolv-3.txt" &&
    ok "resolv.conf: fd00:6::53 back after 10.0.2.3" || bad "resolv.conf: RDNSS not back"

# 4. The record's times.
guest "cat /var/db/dhcpc/$iface.dhcp6" > "$out/record-4.txt"
cat "$out/record-4.txt"
grep -q '^obtained [0-9]*$' "$out/record-4.txt" && grep -q '^t2 [0-9]*$' "$out/record-4.txt" &&
    grep -q '^valid [0-9]*$' "$out/record-4.txt" && ok "record: obtained, t2, valid" || bad "record times"
server=$(sed -n 's/^server //p' "$out/record-4.txt")

# 5. A Rebind past T2 (the record's server another, which dnsmasq would not answer a Renew for).
guest "sed -e 's/^server .*/server 00040011223344556677889900aabbccddee/' -e 's/^t2 .*/t2 0/' -e 's/^valid .*/valid 4294967295/' /var/db/dhcpc/$iface.dhcp6 > /tmp/r.dhcp6 && cp /tmp/r.dhcp6 /var/db/dhcpc/$iface.dhcp6; dhcpc -6 -v $iface; echo exit=\$?; cat /var/db/dhcpc/$iface.dhcp6" > "$out/rebind-5.txt"
cat "$out/rebind-5.txt"
grep -q "^dhcpc: $iface: rebind taken" "$out/rebind-5.txt" && ok "rebind taken" || bad "rebind"
grep -q 'DHCPREBIND(zbv1)' "$out/dnsmasq.log" && ok "dnsmasq saw a Rebind" || bad "dnsmasq: no Rebind"
[ -n "$server" ] && grep -q "^server $server\$" "$out/rebind-5.txt" && ok "the record names dnsmasq again" ||
    bad "the record's server"

# 6. The address before taken off when another is leased.
guest "ifconfig $iface inet6 fd00:6::77/128; sed -e 's/^address .*/address fd00:6::77/' -e 's/^valid .*/valid 1/' -e 's/^obtained .*/obtained 1/' /var/db/dhcpc/$iface.dhcp6 > /tmp/r.dhcp6 && cp /tmp/r.dhcp6 /var/db/dhcpc/$iface.dhcp6; dhcpc -6 -v $iface; echo exit=\$?; ifconfig $iface" > "$out/previous-6.txt"
cat "$out/previous-6.txt"
grep -q "^dhcpc: $iface: previous address fd00:6::77/128 removed" "$out/previous-6.txt" &&
    ! grep -q 'inet6 fd00:6::77 ' "$out/previous-6.txt" && ok "the previous address removed" || bad "previous address"

# 7. Decline.
guest "dhcpc -6 -D -v $iface; echo exit=\$?" > "$out/decline-7.txt"
cat "$out/decline-7.txt"
grep -q "^dhcpc: $iface: decline fd00:6::[0-9a-f]*/128 answered" "$out/decline-7.txt" &&
    grep -q "^dhcpc: $iface: address fd00:6::[0-9a-f]*/128 " "$out/decline-7.txt" && ok "declined, another leased" ||
    bad "decline"
grep -q 'DHCPDECLINE(zbv1)' "$out/dnsmasq.log" && ok "dnsmasq saw a Decline" || bad "dnsmasq: no Decline"

# 8. Release.
guest "dhcpc -6 -r -v $iface; echo exit=\$?; ifconfig $iface; ls /var/db/dhcpc/" > "$out/release-8.txt"
cat "$out/release-8.txt"
grep -q "^dhcpc: $iface: release fd00:6::[0-9a-f]*/128 answered" "$out/release-8.txt" && ok "released" || bad "release"
! grep -q 'prefixlen 128 dhcp$' "$out/release-8.txt" && ! grep -q "^$iface.dhcp6\$" "$out/release-8.txt" &&
    ok "no DHCPv6 address or record left" || bad "after the release"
grep -q 'DHCPRELEASE(zbv1)' "$out/dnsmasq.log" && ok "dnsmasq saw a Release" || bad "dnsmasq: no Release"

# 9. A duplicate stable address made again.
if [ -n "$stable" ]; then
	guest "ifconfig $iface -inet6 $stable/64; echo off" >/dev/null
	sudo ip -n zb6 addr add "$stable/64" dev zbv1 nodad
	guest "sleep 25; ifconfig $iface" > "$out/dad-9.txt"
	cat "$out/dad-9.txt"
	again=$(sed -n 's/.*inet6 \(fd00:6::[0-9a-f:]*\) prefixlen 64 autoconf$/\1/p' "$out/dad-9.txt" | head -1)
	[ -n "$again" ] && [ "$again" != "$stable" ] && ok "another stable address after the duplicate: $again" ||
	    bad "stable address after the duplicate: '$again'"
	! grep -q "inet6 $stable " "$out/dad-9.txt" && ok "the duplicate taken off" || bad "the duplicate still there"
	sudo ip -n zb6 addr del "$stable/64" dev zbv1
fi

# 10. The carrier lost and back.
qmp '{"execute": "set_link", "arguments": {"name": "net1", "up": false}}' > "$out/qmp-10.txt"
guest "sleep 3; ifconfig $iface; route -6 show" > "$out/carrier-10.txt"
cat "$out/qmp-10.txt" "$out/carrier-10.txt"
if grep -q "^$iface: flags=.*RUNNING" "$out/carrier-10.txt"; then
	echo "not judged: the guest did not see the carrier go"
else
	! grep -q 'prefixlen 64 .*autoconf' "$out/carrier-10.txt" && ok "carrier down: the SLAAC addresses gone" ||
	    bad "carrier down: SLAAC addresses left"
	! grep -q "^default .* $iface\$" "$out/carrier-10.txt" && ok "carrier down: no default route on $iface" ||
	    bad "carrier down: a default route on $iface"
	qmp '{"execute": "set_link", "arguments": {"name": "net1", "up": true}}' >> "$out/qmp-10.txt"
	guest "sleep 15; ifconfig $iface" > "$out/carrier-10-up.txt"
	grep -q 'inet6 fd00:6::.* prefixlen 64 autoconf$' "$out/carrier-10-up.txt" && ok "carrier up: SLAAC back" ||
	    bad "carrier up: no SLAAC"
fi

# 11. IPv4 unchanged.
guest 'ping -c 1 10.0.2.2 >/dev/null 2>&1 && echo yes' | tail -1 | grep -q yes && ok "IPv4 still works" || bad "IPv4"

[ $status = 0 ] && echo "ipv6-r-dnsmasq: PASS" || echo "ipv6-r-dnsmasq: FAIL"
exit $status
