# PC/AT i386 build composition.
include platform/pcat/vmunix.mk
include platform/pcat/bootloader.mk
include platform/pcat/rootfs.mk
include platform/pcat/disk-image.mk
include platform/pcat/run.mk
include platform/pcat/toolchain.mk
