# The network a harness guest needs: one wired interface, addressed by the
# emulator's own DHCP server.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
version: 1

interfaces:
  lo0:
    type: loopback
    enabled: true
    ipv4:
      dhcp: false
      addresses:
        - address: 127.0.0.1
          prefix-length: 8
  ue0:
    type: ethernet
    enabled: true
    ipv4:
      dhcp: true
      dhcp-timeout: 20

dns:
  mode: dhcp
