# X68000 build composition.
include platform/x68k/vmunix.mk
include platform/x68k/bootloader.mk
include platform/x68k/rootfs.mk
include platform/x68k/disk-image.mk
include platform/x68k/run.mk
include platform/x68k/toolchain.mk
