include $(dir $(lastword $(MAKEFILE_LIST)))../package.mk

# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib

$(eval $(call ZEDBSD_USERLAND_PACKAGE,uuencode,uuencode,*,y,basic,userland/base/uuencode/main.c userland/base/common/uucodec.c,y,base,,))
